// <auto-generated>
// Generated by tools/async-linq-codegen/generate_subscribe_overloads.py. Do not edit by hand;
// change the generator and rerun it.
// </auto-generated>
using System;
using System.Threading;

namespace Onity.Unity.Async
{
    public static partial class OnityAsyncEnumerableExtensions
    {
        /// <summary>Subscribes to the stream and invokes an action for each item.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Action invoked synchronously for each item.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable Subscribe<T>(this IOnityAsyncEnumerable<T> source, Action<T> onNext)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAction(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, null, null);
        }

        /// <summary>Subscribes to the stream and invokes an action for each item.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Action invoked synchronously for each item.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void Subscribe<T>(this IOnityAsyncEnumerable<T> source, Action<T> onNext,
            CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAction(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, null, null, cancellationToken);
        }

        /// <summary>Subscribes to the stream and starts a fire-and-forget async handler for each
        /// item.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler started for each item without being awaited, so handlers may
        /// overlap.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable Subscribe<T>(this IOnityAsyncEnumerable<T> source, Func<T, OnityTaskVoid> onNext)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromVoid(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, null, null);
        }

        /// <summary>Subscribes to the stream and starts a fire-and-forget async handler for each
        /// item.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler started for each item without being awaited, so handlers may
        /// overlap.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void Subscribe<T>(this IOnityAsyncEnumerable<T> source, Func<T, OnityTaskVoid> onNext,
            CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromVoid(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, null, null, cancellationToken);
        }

        /// <summary>Subscribes to the stream and starts a fire-and-forget async handler that receives the
        /// subscription token for each item.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler started for each item without being awaited; it receives the
        /// subscription token.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable Subscribe<T>(this IOnityAsyncEnumerable<T> source,
            Func<T, CancellationToken, OnityTaskVoid> onNext)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromVoidWithToken(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, null, null);
        }

        /// <summary>Subscribes to the stream and starts a fire-and-forget async handler that receives the
        /// subscription token for each item.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler started for each item without being awaited; it receives the
        /// subscription token.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void Subscribe<T>(this IOnityAsyncEnumerable<T> source,
            Func<T, CancellationToken, OnityTaskVoid> onNext, CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromVoidWithToken(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, null, null, cancellationToken);
        }

        /// <summary>Subscribes to the stream and invokes an action for each item and reports failures to a
        /// callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Action invoked synchronously for each item.</param>
        /// <param name="onError">Receives a stream failure other than cancellation.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable Subscribe<T>(this IOnityAsyncEnumerable<T> source, Action<T> onNext,
            Action<Exception> onError)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onError, nameof(onError));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAction(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, onError, null);
        }

        /// <summary>Subscribes to the stream and invokes an action for each item and reports failures to a
        /// callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Action invoked synchronously for each item.</param>
        /// <param name="onError">Receives a stream failure other than cancellation.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void Subscribe<T>(this IOnityAsyncEnumerable<T> source, Action<T> onNext,
            Action<Exception> onError, CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onError, nameof(onError));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAction(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, onError, null, cancellationToken);
        }

        /// <summary>Subscribes to the stream and starts a fire-and-forget async handler for each item and
        /// reports failures to a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler started for each item without being awaited, so handlers may
        /// overlap.</param>
        /// <param name="onError">Receives a stream failure other than cancellation.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable Subscribe<T>(this IOnityAsyncEnumerable<T> source, Func<T, OnityTaskVoid> onNext,
            Action<Exception> onError)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onError, nameof(onError));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromVoid(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, onError, null);
        }

        /// <summary>Subscribes to the stream and starts a fire-and-forget async handler for each item and
        /// reports failures to a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler started for each item without being awaited, so handlers may
        /// overlap.</param>
        /// <param name="onError">Receives a stream failure other than cancellation.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void Subscribe<T>(this IOnityAsyncEnumerable<T> source, Func<T, OnityTaskVoid> onNext,
            Action<Exception> onError, CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onError, nameof(onError));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromVoid(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, onError, null, cancellationToken);
        }

        /// <summary>Subscribes to the stream and invokes an action for each item and reports normal completion
        /// to a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Action invoked synchronously for each item.</param>
        /// <param name="onCompleted">Invoked once after normal completion and upstream cleanup.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable Subscribe<T>(this IOnityAsyncEnumerable<T> source, Action<T> onNext,
            Action onCompleted)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onCompleted, nameof(onCompleted));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAction(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, null, onCompleted);
        }

        /// <summary>Subscribes to the stream and invokes an action for each item and reports normal completion
        /// to a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Action invoked synchronously for each item.</param>
        /// <param name="onCompleted">Invoked once after normal completion and upstream cleanup.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void Subscribe<T>(this IOnityAsyncEnumerable<T> source, Action<T> onNext, Action onCompleted,
            CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onCompleted, nameof(onCompleted));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAction(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, null, onCompleted, cancellationToken);
        }

        /// <summary>Subscribes to the stream and starts a fire-and-forget async handler for each item and
        /// reports normal completion to a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler started for each item without being awaited, so handlers may
        /// overlap.</param>
        /// <param name="onCompleted">Invoked once after normal completion and upstream cleanup.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable Subscribe<T>(this IOnityAsyncEnumerable<T> source, Func<T, OnityTaskVoid> onNext,
            Action onCompleted)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onCompleted, nameof(onCompleted));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromVoid(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, null, onCompleted);
        }

        /// <summary>Subscribes to the stream and starts a fire-and-forget async handler for each item and
        /// reports normal completion to a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler started for each item without being awaited, so handlers may
        /// overlap.</param>
        /// <param name="onCompleted">Invoked once after normal completion and upstream cleanup.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void Subscribe<T>(this IOnityAsyncEnumerable<T> source, Func<T, OnityTaskVoid> onNext,
            Action onCompleted, CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onCompleted, nameof(onCompleted));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromVoid(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, null, onCompleted, cancellationToken);
        }

        /// <summary>Subscribes to the stream and forwards items, failure and completion to an
        /// observer.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="observer">Receives OnNext for each item, OnError for a failure other than cancellation
        /// and OnCompleted after normal completion and upstream cleanup.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or observer is null.</exception>
        public static IDisposable Subscribe<T>(this IOnityAsyncEnumerable<T> source, IObserver<T> observer)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(observer, nameof(observer));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAction(observer.OnNext);
            return OnityAsyncSubscribeCore.Start(
                source, handler, observer.OnError, observer.OnCompleted);
        }

        /// <summary>Subscribes to the stream and forwards items, failure and completion to an
        /// observer.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="observer">Receives OnNext for each item, OnError for a failure other than cancellation
        /// and OnCompleted after normal completion and upstream cleanup.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or observer is null.</exception>
        public static void Subscribe<T>(this IOnityAsyncEnumerable<T> source, IObserver<T> observer,
            CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(observer, nameof(observer));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAction(observer.OnNext);
            OnityAsyncSubscribeCore.Start(
                source, handler, observer.OnError, observer.OnCompleted, cancellationToken);
        }

        /// <summary>Subscribes to the stream and awaits an async handler for each item.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler awaited before the next item is requested.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws or faults is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable SubscribeAwait<T>(this IOnityAsyncEnumerable<T> source, Func<T, OnityTask> onNext)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAwait(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, null, null);
        }

        /// <summary>Subscribes to the stream and awaits an async handler for each item.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler awaited before the next item is requested.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws or faults is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void SubscribeAwait<T>(this IOnityAsyncEnumerable<T> source, Func<T, OnityTask> onNext,
            CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAwait(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, null, null, cancellationToken);
        }

        /// <summary>Subscribes to the stream and awaits an async handler that receives the subscription token
        /// for each item.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler awaited before the next item is requested; it receives the subscription
        /// token.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws or faults is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable SubscribeAwait<T>(this IOnityAsyncEnumerable<T> source,
            Func<T, CancellationToken, OnityTask> onNext)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAwaitWithToken(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, null, null);
        }

        /// <summary>Subscribes to the stream and awaits an async handler that receives the subscription token
        /// for each item.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler awaited before the next item is requested; it receives the subscription
        /// token.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws or faults is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void SubscribeAwait<T>(this IOnityAsyncEnumerable<T> source,
            Func<T, CancellationToken, OnityTask> onNext, CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAwaitWithToken(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, null, null, cancellationToken);
        }

        /// <summary>Subscribes to the stream and awaits an async handler for each item and reports failures to
        /// a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler awaited before the next item is requested.</param>
        /// <param name="onError">Receives a stream failure other than cancellation.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws or faults is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable SubscribeAwait<T>(this IOnityAsyncEnumerable<T> source, Func<T, OnityTask> onNext,
            Action<Exception> onError)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onError, nameof(onError));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAwait(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, onError, null);
        }

        /// <summary>Subscribes to the stream and awaits an async handler for each item and reports failures to
        /// a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler awaited before the next item is requested.</param>
        /// <param name="onError">Receives a stream failure other than cancellation.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws or faults is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void SubscribeAwait<T>(this IOnityAsyncEnumerable<T> source, Func<T, OnityTask> onNext,
            Action<Exception> onError, CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onError, nameof(onError));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAwait(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, onError, null, cancellationToken);
        }

        /// <summary>Subscribes to the stream and awaits an async handler that receives the subscription token
        /// for each item and reports failures to a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler awaited before the next item is requested; it receives the subscription
        /// token.</param>
        /// <param name="onError">Receives a stream failure other than cancellation.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws or faults is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable SubscribeAwait<T>(this IOnityAsyncEnumerable<T> source,
            Func<T, CancellationToken, OnityTask> onNext, Action<Exception> onError)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onError, nameof(onError));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAwaitWithToken(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, onError, null);
        }

        /// <summary>Subscribes to the stream and awaits an async handler that receives the subscription token
        /// for each item and reports failures to a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler awaited before the next item is requested; it receives the subscription
        /// token.</param>
        /// <param name="onError">Receives a stream failure other than cancellation.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws or faults is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void SubscribeAwait<T>(this IOnityAsyncEnumerable<T> source,
            Func<T, CancellationToken, OnityTask> onNext, Action<Exception> onError,
            CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onError, nameof(onError));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAwaitWithToken(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, onError, null, cancellationToken);
        }

        /// <summary>Subscribes to the stream and awaits an async handler for each item and reports normal
        /// completion to a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler awaited before the next item is requested.</param>
        /// <param name="onCompleted">Invoked once after normal completion and upstream cleanup.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws or faults is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable SubscribeAwait<T>(this IOnityAsyncEnumerable<T> source, Func<T, OnityTask> onNext,
            Action onCompleted)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onCompleted, nameof(onCompleted));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAwait(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, null, onCompleted);
        }

        /// <summary>Subscribes to the stream and awaits an async handler for each item and reports normal
        /// completion to a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler awaited before the next item is requested.</param>
        /// <param name="onCompleted">Invoked once after normal completion and upstream cleanup.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws or faults is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void SubscribeAwait<T>(this IOnityAsyncEnumerable<T> source, Func<T, OnityTask> onNext,
            Action onCompleted, CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onCompleted, nameof(onCompleted));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAwait(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, null, onCompleted, cancellationToken);
        }

        /// <summary>Subscribes to the stream and awaits an async handler that receives the subscription token
        /// for each item and reports normal completion to a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler awaited before the next item is requested; it receives the subscription
        /// token.</param>
        /// <param name="onCompleted">Invoked once after normal completion and upstream cleanup.</param>
        /// <returns>A disposable that cancels the subscription token and so stops the stream cooperatively;
        /// disposing it after the subscription ended does nothing.</returns>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws or faults is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static IDisposable SubscribeAwait<T>(this IOnityAsyncEnumerable<T> source,
            Func<T, CancellationToken, OnityTask> onNext, Action onCompleted)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onCompleted, nameof(onCompleted));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAwaitWithToken(onNext);
            return OnityAsyncSubscribeCore.Start(source, handler, null, onCompleted);
        }

        /// <summary>Subscribes to the stream and awaits an async handler that receives the subscription token
        /// for each item and reports normal completion to a callback.</summary>
        /// <typeparam name="T">Item type.</typeparam>
        /// <param name="source">Reusable upstream description.</param>
        /// <param name="onNext">Handler awaited before the next item is requested; it receives the subscription
        /// token.</param>
        /// <param name="onCompleted">Invoked once after normal completion and upstream cleanup.</param>
        /// <param name="cancellationToken">Token that stops the subscription cooperatively; it is also the
        /// token the stream is enumerated with.</param>
        /// <remarks>
        /// The enumeration starts synchronously on the calling thread and continues wherever the stream
        /// completes its moves; no thread or context hop is added, so a synchronous stream is consumed before
        /// this call returns. A handler that throws or faults is reported as an unobserved exception
        /// (OperationCanceledException is ignored) and the next item is still delivered. Cancellation ends the
        /// subscription silently; any other stream failure goes to onError, or is reported as an unobserved
        /// exception when no onError was supplied. Upstream cleanup is awaited before onCompleted or onError
        /// runs, and a cleanup failure replaces the normal completion.
        /// </remarks>
        /// <exception cref="ArgumentNullException">Source or a callback is null.</exception>
        public static void SubscribeAwait<T>(this IOnityAsyncEnumerable<T> source,
            Func<T, CancellationToken, OnityTask> onNext, Action onCompleted, CancellationToken cancellationToken)
        {
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(onNext, nameof(onNext));
            OnityLinqCore.NotNull(onCompleted, nameof(onCompleted));
            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAwaitWithToken(onNext);
            OnityAsyncSubscribeCore.Start(source, handler, null, onCompleted, cancellationToken);
        }
    }
}
