#!/usr/bin/env python3
"""Generates the AI-readable documentation copy that ships inside the Onity UPM package.

Users install Onity from GitHub (the `upm` branch, or `?path=/Packages/com.onity.framework`), so only the
package folder reaches their project. The guides under `docs/` and the agent skill under `.agents/skills/`
live outside it. This script derives a copy under `Packages/com.onity.framework/Documentation~/`, a folder
that Unity ignores (no .meta files, nothing imported or compiled), where AI coding assistants can read it.

`docs/` and `.agents/skills/` stay the single source of truth. Never edit `Documentation~/` by hand: the
whole folder belongs to this script, and files it does not generate are removed.

Layout (source -> `Documentation~/`):

    docs/Onity-AI-Usage-Guide.md           AI/Onity-AI-Usage-Guide.md
    .agents/skills/onity-use/SKILL.md      AI/skills/onity-use/SKILL.md
    docs/Getting-Started.md                Getting-Started.md
    docs/guide/*.md                        guide/*.md
    docs/Migration/*.md                    Migration/*.md
    docs/reference/**/*.md                 reference/**/*.md

Everything else under docs/ (Plan, benchmarks, assets, ADR, site configuration) is not shipped.

Transformations applied to each file:

  * Jekyll front matter is removed. The skill keeps its front matter, which is the skill's own metadata.
  * A one-line HTML comment naming the source file is added at the top (after the skill's front matter).
  * Relative links are rewritten. A link to a shipped file becomes a relative `.md` path inside
    `Documentation~/` (`guide/reactive.html#x` -> `../guide/reactive.md#x`). A link to a docs-site page or
    asset that is not shipped becomes an absolute docs-site URL, and a link to any other repository file
    becomes a GitHub URL. Links into the package folder become package-relative paths. The skill is copied
    out of the package into user projects, so its links always become absolute URLs.
  * Jekyll Liquid link forms (`{{ site.baseurl }}/x.html`, `{% link x.md %}`) are resolved the same way, and
    `{% raw %}` tags are dropped. Any other Liquid is an error, because the package copy is never rendered.

Usage:

    python tools/docs/sync-package-docs.py          # write the package copy
    python tools/docs/sync-package-docs.py --check  # exit 1 when the committed copy is stale

The output depends only on the sources, so it is reproducible. Files are written with LF line endings;
the check ignores carriage returns added by a Git checkout. Generation writes nothing and exits 2 when a
link cannot be resolved.

The check also verifies the hand-written entry points at the package root (README.md, AGENTS.md,
CLAUDE.md, llms.txt): every `Documentation~/...` path they mention must exist, and llms.txt must list
every shipped file.
"""

from __future__ import annotations

import argparse
import posixpath
import re
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple
from urllib.parse import quote

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]

SCRIPT_PATH = "tools/docs/sync-package-docs.py"
PACKAGE_PATH = "Packages/com.onity.framework"
OUTPUT_FOLDER = "Documentation~"
DOCS_FOLDER = "docs"
SITE_CONFIG = "docs/_config.yml"

# Used when docs/_config.yml does not define the value.
DEFAULT_SITE_URL = "https://furkantokkan.github.io"
DEFAULT_BASE_URL = "/Onity"
DEFAULT_REPOSITORY = "furkantokkan/Onity"
DEFAULT_BRANCH = "main"

GENERATED_HEADER = (
    "<!-- Generated by " + SCRIPT_PATH + " from {source}. "
    "Do not edit; change the source and re-run the script. -->"
)

# Hand-written files at the package root that point at the shipped copy.
ENTRY_POINTS = ("README.md", "AGENTS.md", "CLAUDE.md", "llms.txt")
INDEX_FILE = "llms.txt"

BYTE_ORDER_MARK = chr(0xFEFF)


@dataclass(frozen=True)
class Entry:
    """One file shipped in Documentation~."""

    source: str  # repository-relative path, forward slashes
    output: str  # path relative to Documentation~
    keep_front_matter: bool = False  # the front matter is metadata the consumer reads, not Jekyll's
    portable: bool = False  # copied out of the package, so links must not depend on its layout


SINGLE_FILES = (
    Entry("docs/Onity-AI-Usage-Guide.md", "AI/Onity-AI-Usage-Guide.md"),
    Entry(".agents/skills/onity-use/SKILL.md", "AI/skills/onity-use/SKILL.md",
          keep_front_matter=True, portable=True),
    Entry("docs/Getting-Started.md", "Getting-Started.md"),
)

# (folder under docs/, include subfolders). Each file keeps its path relative to docs/.
FOLDERS = (("guide", False), ("Migration", False), ("reference", True))


class LinkError(Exception):
    """A link that cannot be resolved to a shipped file, a docs-site page or a repository file."""


# ----------------------------------------------------------------------------------------------
# Site configuration and link targets
# ----------------------------------------------------------------------------------------------

def config_scalar(text: str, key: str) -> Optional[str]:
    """Value of a top-level `key: value` line; None when the key is absent, "" when it is empty."""
    match = re.search(r"^" + re.escape(key) + r":[ \t]*(?:\"([^\"]*)\"|'([^']*)'|([^#\r\n]*))", text, re.M)
    if not match:
        return None
    return next((group for group in match.groups() if group is not None), "").strip()


def config_list(text: str, key: str) -> List[str]:
    lines = text.splitlines()
    items: List[str] = []
    for index, line in enumerate(lines):
        if not re.match(r"^" + re.escape(key) + r":[ \t]*(#.*)?$", line):
            continue
        for item in lines[index + 1:]:
            match = re.match(r"^[ \t]+-[ \t]+(?:\"([^\"]*)\"|'([^']*)'|([^#\s]+))", item)
            if match:
                items.append(next(group for group in match.groups() if group is not None))
            elif item.strip() == "" or item.lstrip().startswith("#"):
                continue
            else:
                break
        break
    return items


@dataclass(frozen=True)
class Site:
    """Where the Jekyll docs site and the GitHub repository live, read from docs/_config.yml."""

    url: str  # site URL plus base path, no trailing slash
    base_path: str
    repository: str
    branch: str
    excludes: Tuple[str, ...]

    @staticmethod
    def load(root: Path) -> "Site":
        config = root / SITE_CONFIG
        text = config.read_text(encoding="utf-8") if config.is_file() else ""
        site_url = (config_scalar(text, "url") or DEFAULT_SITE_URL).rstrip("/")
        configured_base = config_scalar(text, "baseurl")
        base_path = (DEFAULT_BASE_URL if configured_base is None else configured_base).strip("/")
        base_path = "/" + base_path if base_path else ""
        return Site(
            url=site_url + base_path,
            base_path=base_path,
            repository=config_scalar(text, "repository") or DEFAULT_REPOSITORY,
            branch=config_scalar(text, "gh_edit_branch") or DEFAULT_BRANCH,
            excludes=tuple(config_list(text, "exclude")),
        )

    def serves(self, relative: str) -> bool:
        """True when Jekyll publishes the docs-relative path."""
        if any(part.startswith(("_", ".")) for part in relative.split("/")):
            return False
        for pattern in self.excludes:
            excluded = pattern.rstrip("/")
            if relative == excluded or relative.startswith(excluded + "/"):
                return False
        return True

    def page_url(self, relative: str, is_page: bool) -> str:
        """URL of a docs-relative file. A Markdown file with front matter is rendered as an HTML page."""
        if is_page:
            relative = relative[:-len(".md")] + ".html"
            if relative == "index.html" or relative.endswith("/index.html"):
                relative = relative[:-len("index.html")]
        return self.url + "/" + quote(relative, safe="/")

    def repository_url(self, path: str, is_directory: bool) -> str:
        kind = "tree" if is_directory else "blob"
        return f"https://github.com/{self.repository}/{kind}/{self.branch}/{quote(path, safe='/')}"


def has_front_matter(path: Path) -> bool:
    with path.open("rb") as handle:
        return handle.read(4) in (b"---\n", b"---\r")


def relative_posix(target: str, start_directory: str) -> str:
    """Relative path from a directory to a file; both are forward-slash paths under one root."""
    target_parts = target.split("/")
    start_parts = [part for part in start_directory.split("/") if part]
    common = 0
    while (common < len(start_parts) and common < len(target_parts) - 1
           and start_parts[common] == target_parts[common]):
        common += 1
    return "/".join([".."] * (len(start_parts) - common) + target_parts[common:])


EXTERNAL_DESTINATION = re.compile(r"^(?:[A-Za-z][A-Za-z0-9+.\-]*:|//)")
LIQUID_LINK_TAG = re.compile(r"\{%-?\s*link\s+(\S+?)\s*-?%\}")
LIQUID_OUTPUT = re.compile(r"\{\{-?\s*(.*?)\s*-?\}\}")
LIQUID_FILTERED_PATH = re.compile(r"""^(['"])(.*?)\1\s*\|\s*(?:relative_url|absolute_url)$""")
LIQUID_SITE_VALUES = ("site.url", "site.baseurl", "site.url | append: site.baseurl")
LIQUID_RAW_TAG = re.compile(r"\{%-?\s*(?:end)?raw\s*-?%\}")


def resolve_liquid(path: str) -> str:
    """Turns a Jekyll Liquid link into a site-absolute path, or raises LinkError."""
    path = LIQUID_LINK_TAG.sub(lambda match: "/" + match.group(1).lstrip("/"), path)

    def output(match: "re.Match[str]") -> str:
        expression = match.group(1)
        if expression in LIQUID_SITE_VALUES:
            return ""
        filtered = LIQUID_FILTERED_PATH.match(expression)
        if filtered:
            return filtered.group(2)
        raise LinkError(f"unsupported Liquid expression '{{{{ {expression} }}}}' in a link")

    path = LIQUID_OUTPUT.sub(output, path)
    if "{%" in path or "{{" in path:
        raise LinkError(f"unsupported Liquid tag in link '{path}'")
    if not path.startswith("/"):
        path = "/" + path
    return path


class Resolver:
    """Rewrites link destinations of one shipped file."""

    def __init__(self, root: Path, entries: List[Entry], site: Site) -> None:
        self.root = root
        self.site = site
        self.shipped: Dict[str, Entry] = {entry.source: entry for entry in entries}
        self.statistics: Counter = Counter()

    def rewrite(self, entry: Entry, destination: str) -> str:
        if not destination or destination.startswith("#") or EXTERNAL_DESTINATION.match(destination):
            return destination

        path, hash_mark, fragment = destination.partition("#")
        path, question_mark, query = path.partition("?")
        suffix = question_mark + query + hash_mark + fragment
        if not path:
            return destination
        if "{{" in path or "{%" in path:
            path = resolve_liquid(path)

        if path.startswith("/"):
            site_path = path
            base = self.site.base_path
            if base and (site_path == base or site_path.startswith(base + "/")):
                site_path = site_path[len(base):]
            target = posixpath.normpath(DOCS_FOLDER + "/" + site_path.lstrip("/"))
        else:
            target = posixpath.normpath(posixpath.join(posixpath.dirname(entry.source), path))
        if target == ".." or target.startswith("../"):
            raise LinkError(f"link '{destination}' points outside the repository")

        is_directory = path.endswith("/") or (self.root / target).is_dir()
        if is_directory:
            candidates = [target + "/index.md"]
        elif target.endswith(".html"):
            candidates = [target[:-len(".html")] + ".md", target]
        else:
            candidates = [target, target + ".md"]

        if not entry.portable:
            for candidate in candidates:
                if candidate in self.shipped:
                    self.statistics["package-relative"] += 1
                    output = self.shipped[candidate].output
                    return relative_posix(output, posixpath.dirname(entry.output)) + hash_mark + fragment

        found = next((candidate for candidate in candidates if (self.root / candidate).exists()), None)
        if found is None and (self.root / target).is_dir():
            found = target
        if found is None:
            raise LinkError(f"link '{destination}' does not match a file ({target})")
        return self.external(entry, found, suffix, hash_mark + fragment)

    def external(self, entry: Entry, found: str, suffix: str, fragment: str) -> str:
        """Link to a file that is not shipped in Documentation~. The suffix is the query plus the
        fragment; a package-relative link keeps only the fragment."""
        full = self.root / found
        package_prefix = PACKAGE_PATH + "/"
        if not entry.portable and found.startswith(package_prefix):
            self.statistics["package-relative"] += 1
            output_directory = OUTPUT_FOLDER + "/" + posixpath.dirname(entry.output)
            return relative_posix(found[len(package_prefix):], output_directory) + fragment

        docs_prefix = DOCS_FOLDER + "/"
        if found.startswith(docs_prefix) and full.is_file() and self.site.serves(found[len(docs_prefix):]):
            self.statistics["docs-site"] += 1
            relative = found[len(docs_prefix):]
            is_page = relative.endswith(".md") and has_front_matter(full)
            return self.site.page_url(relative, is_page) + suffix

        self.statistics["repository"] += 1
        return self.site.repository_url(found, full.is_dir()) + suffix


# ----------------------------------------------------------------------------------------------
# Markdown processing
# ----------------------------------------------------------------------------------------------

FENCE_OPEN = re.compile(r"^[ \t]*(`{3,}|~{3,})(.*)$")
FENCE_CLOSE = re.compile(r"^[ \t]*(`{3,}|~{3,})[ \t]*$")
REFERENCE_DEFINITION = re.compile(r"^ {0,3}\[(?:[^\]\\\n]|\\.)+\]:[ \t]*(?:<([^<>\n]*)>|(\S+))", re.M)
HTML_ATTRIBUTE = re.compile(r"""\b(?:href|src)[ \t]*=[ \t]*(?:"([^"\n]*)"|'([^'\n]*)')""", re.I)
LINK_TITLE_AND_CLOSE = re.compile(r"""[ \t\n]*(?:"[^"]*"|'[^']*'|\([^)]*\))?[ \t\n]*\)""")


def split_front_matter(text: str) -> Tuple[str, str]:
    """Returns (front matter block including its delimiter lines, body). The block is empty when absent."""
    lines = text.split("\n")
    if not lines or lines[0].rstrip() != "---":
        return "", text
    for index in range(1, len(lines)):
        if lines[index].rstrip() in ("---", "..."):
            return "\n".join(lines[:index + 1]) + "\n", "\n".join(lines[index + 1:])
    return "", text


def mask_code_spans(text: str) -> str:
    """Replaces inline code spans, backticks included, with NULs so link syntax inside them is ignored."""
    characters = list(text)
    length = len(text)
    index = 0
    while index < length:
        if text[index] != "`":
            index += 1
            continue
        start = index
        while index < length and text[index] == "`":
            index += 1
        run = index - start
        if start > 0 and text[start - 1] == "\\":
            continue
        close = -1
        search = index
        while search < length:
            if text[search] != "`":
                search += 1
                continue
            end = search
            while end < length and text[end] == "`":
                end += 1
            if end - search == run:
                close = end
                break
            search = end
        if close == -1:
            continue
        for position in range(start, close):
            characters[position] = "\0"
        index = close
    return "".join(characters)


def has_opening_bracket(masked: str, closing_index: int) -> bool:
    """True when the ']' at closing_index closes a '[' earlier in the paragraph."""
    depth = 1
    for index in range(closing_index - 1, -1, -1):
        character = masked[index]
        if character not in "[]":
            continue
        backslashes = 0
        while index - 1 - backslashes >= 0 and masked[index - 1 - backslashes] == "\\":
            backslashes += 1
        if backslashes % 2 == 1:
            continue
        depth += 1 if character == "]" else -1
        if depth == 0:
            return True
    return False


def destination_spans(masked: str) -> List[Tuple[int, int]]:
    """Spans of the link destinations in a masked paragraph: inline links, images, reference
    definitions and href/src attributes."""
    spans: Set[Tuple[int, int]] = set()
    length = len(masked)

    for marker in re.finditer(r"\]\(", masked):
        if not has_opening_bracket(masked, marker.start()):
            continue
        index = marker.end()
        while index < length and masked[index] in " \t":
            index += 1
        if index < length and masked[index] == "<":
            close = masked.find(">", index + 1)
            if close == -1 or "\n" in masked[index:close]:
                continue
            start, end = index + 1, close
            rest = close + 1
        else:
            depth = 0
            end = index
            while end < length:
                if masked.startswith(("{{", "{%"), end):
                    # Jekyll renders Liquid before Markdown, so an expression is part of the destination.
                    close = masked.find("}}" if masked[end + 1] == "{" else "%}", end + 2)
                    if close == -1:
                        break
                    end = close + 2
                    continue
                character = masked[end]
                if character in " \t\n":
                    break
                if character == "(":
                    depth += 1
                elif character == ")":
                    if depth == 0:
                        break
                    depth -= 1
                end += 1
            start = index
            rest = end
        if LINK_TITLE_AND_CLOSE.match(masked, rest):
            spans.add((start, end))

    for pattern in (REFERENCE_DEFINITION, HTML_ATTRIBUTE):
        for match in pattern.finditer(masked):
            group = next((number for number in (1, 2) if match.group(number) is not None), None)
            if group is not None:
                spans.add(match.span(group))

    return sorted(spans)


def rewrite_paragraph(entry: Entry, text: str, first_line: int, resolver: Resolver, errors: List[str]) -> str:
    masked = mask_code_spans(text)
    result = text
    for start, end in reversed(destination_spans(masked)):
        destination = text[start:end]
        try:
            replacement = resolver.rewrite(entry, destination)
        except LinkError as error:
            line = first_line + text.count("\n", 0, start)
            errors.append(f"{entry.source}:{line}: {error}")
            continue
        if replacement != destination:
            result = result[:start] + replacement + result[end:]

    leftover = mask_code_spans(result)
    for marker in ("{{", "{%"):
        position = leftover.find(marker)
        if position != -1:
            line = first_line + result.count("\n", 0, position)
            errors.append(f"{entry.source}:{line}: Liquid '{marker}' outside a code block or code span; "
                          "the package copy is not rendered, so escape it or remove it")
            break
    return result


def rewrite_links(entry: Entry, body: str, first_line: int, resolver: Resolver, errors: List[str]) -> str:
    """Rewrites links in the prose of a Markdown body. Fenced code blocks are copied unchanged."""
    output: List[str] = []
    paragraph: List[Tuple[int, str]] = []
    fence: Optional[Tuple[str, int]] = None

    def flush() -> None:
        if not paragraph:
            return
        text = "\n".join(line for _, line in paragraph)
        output.extend(rewrite_paragraph(entry, text, paragraph[0][0], resolver, errors).split("\n"))
        paragraph.clear()

    for offset, line in enumerate(body.split("\n")):
        number = first_line + offset
        if fence is not None:
            output.append(line)
            closing = FENCE_CLOSE.match(line)
            if closing and closing.group(1)[0] == fence[0] and len(closing.group(1)) >= fence[1]:
                fence = None
            continue
        opening = FENCE_OPEN.match(line)
        if opening and not (opening.group(1)[0] == "`" and "`" in opening.group(2)):
            flush()
            fence = (opening.group(1)[0], len(opening.group(1)))
            output.append(line)
        elif line.strip() == "":
            flush()
            output.append(line)
        else:
            paragraph.append((number, line))
    flush()
    return "\n".join(output)


def normalize_newlines(text: str) -> str:
    if text.startswith(BYTE_ORDER_MARK):
        text = text[1:]
    return text.replace("\r\n", "\n").replace("\r", "\n")


def transform(entry: Entry, text: str, resolver: Resolver, errors: List[str]) -> str:
    text = normalize_newlines(text)
    text = LIQUID_RAW_TAG.sub("", text)
    front_matter, body = split_front_matter(text)
    body = rewrite_links(entry, body, front_matter.count("\n") + 1, resolver, errors)
    body = body.lstrip("\n")
    header = GENERATED_HEADER.format(source=entry.source)
    if entry.keep_front_matter and front_matter:
        text = front_matter + "\n" + header + "\n\n" + body
    else:
        text = header + "\n\n" + body
    return text.rstrip("\n") + "\n"


# ----------------------------------------------------------------------------------------------
# Selection, comparison and entry-point validation
# ----------------------------------------------------------------------------------------------

def select_entries(root: Path, errors: List[str]) -> List[Entry]:
    entries: List[Entry] = []
    for entry in SINGLE_FILES:
        if (root / entry.source).is_file():
            entries.append(entry)
        else:
            errors.append(f"missing source file: {entry.source}")
    for folder, recursive in FOLDERS:
        base = root / DOCS_FOLDER / folder
        for path in sorted(base.glob("**/*.md" if recursive else "*.md")):
            if path.is_file():
                relative = path.relative_to(root / DOCS_FOLDER).as_posix()
                entries.append(Entry(f"{DOCS_FOLDER}/{relative}", relative))
    return sorted(entries, key=lambda entry: entry.output)


def build(root: Path) -> Tuple[Dict[str, str], List[str], Counter]:
    """Returns ({output path: file text}, errors, link statistics)."""
    errors: List[str] = []
    entries = select_entries(root, errors)
    resolver = Resolver(root, entries, Site.load(root))
    expected: Dict[str, str] = {}
    for entry in entries:
        text = (root / entry.source).read_bytes().decode("utf-8")
        expected[entry.output] = transform(entry, text, resolver, errors)
    return expected, errors, resolver.statistics


def read_normalized(path: Path) -> Optional[str]:
    try:
        return normalize_newlines(path.read_bytes().decode("utf-8"))
    except (OSError, UnicodeDecodeError):
        return None


def first_difference(current: str, expected: str) -> int:
    current_lines = current.split("\n")
    expected_lines = expected.split("\n")
    for index in range(min(len(current_lines), len(expected_lines))):
        if current_lines[index] != expected_lines[index]:
            return index + 1
    return min(len(current_lines), len(expected_lines)) + 1


def list_files(directory: Path) -> Dict[str, Path]:
    if not directory.is_dir():
        return {}
    return {path.relative_to(directory).as_posix(): path
            for path in sorted(directory.rglob("*")) if path.is_file()}


def validate_entry_points(root: Path, shipped: Dict[str, str]) -> List[str]:
    """The root files that point at Documentation~ must name only files that exist, and llms.txt
    must list every shipped file."""
    problems: List[str] = []
    package = root / PACKAGE_PATH
    pattern = re.compile(re.escape(OUTPUT_FOLDER) + r"/[A-Za-z0-9_.\-/]*[A-Za-z0-9_\-/]")
    for name in ENTRY_POINTS:
        path = package / name
        if not path.is_file():
            if name != "README.md":
                problems.append(f"missing: {PACKAGE_PATH}/{name}")
            continue
        text = normalize_newlines(path.read_text(encoding="utf-8"))
        mentioned = set(pattern.findall(text))
        for reference in sorted(mentioned):
            if not (package / reference).exists():
                problems.append(f"{PACKAGE_PATH}/{name} names {reference}, which does not exist")
        if name == INDEX_FILE:
            for output in sorted(shipped):
                if f"{OUTPUT_FOLDER}/{output}" not in mentioned:
                    problems.append(f"{PACKAGE_PATH}/{name} does not list {OUTPUT_FOLDER}/{output}")
    return problems


def remove_empty_directories(directory: Path) -> None:
    for path in sorted((p for p in directory.rglob("*") if p.is_dir()), key=lambda p: len(p.parts), reverse=True):
        if not any(path.iterdir()):
            path.rmdir()


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="Report stale, missing or extra files without writing; exit 1 if any.")
    parser.add_argument("--repo-root", default=None, help="Repository root (default: derived from this script).")
    arguments = parser.parse_args(argv)
    root = Path(arguments.repo_root).resolve() if arguments.repo_root else REPOSITORY_ROOT

    expected, errors, statistics = build(root)
    if errors:
        for error in errors:
            print(f"error: {error}")
        print("nothing was written")
        return 2

    output_root = root / PACKAGE_PATH / OUTPUT_FOLDER
    display = f"{PACKAGE_PATH}/{OUTPUT_FOLDER}"
    existing = list_files(output_root)
    problems: List[str] = []
    written = 0

    for relative, text in expected.items():
        path = output_root / relative
        current = read_normalized(path) if path.is_file() else None
        if current == text:
            continue
        if arguments.check:
            if current is None:
                problems.append(f"missing: {display}/{relative}")
            else:
                problems.append(f"stale: {display}/{relative} (first difference at line "
                                f"{first_difference(current, text)})")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(text.encode("utf-8"))
        written += 1
        print(f"wrote {display}/{relative}")

    removed = 0
    for relative in sorted(set(existing) - set(expected)):
        if arguments.check:
            problems.append(f"extra: {display}/{relative} is not generated from a source file")
        else:
            existing[relative].unlink()
            removed += 1
            print(f"removed {display}/{relative}")
    if removed:
        remove_empty_directories(output_root)

    out_of_date = bool(problems)
    entry_problems = validate_entry_points(root, expected)
    problems.extend(entry_problems)
    for problem in problems:
        print(problem)

    total = sum(len(text.encode("utf-8")) for text in expected.values())
    summary = f"{len(expected)} files, {total / 1024:.1f} KiB in {display}"
    if arguments.check:
        if out_of_date:
            print(f"Run python {SCRIPT_PATH} and commit the result.")
        if entry_problems:
            print("Fix the entry-point files listed above by hand; they are not generated.")
        if problems:
            return 1
        print(f"package docs are up to date ({summary})")
        return 0

    links = ", ".join(f"{count} {kind}" for kind, count in sorted(statistics.items()))
    print(f"{summary}; wrote {written}, removed {removed}; links rewritten: {links or 'none'}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
