// <auto-generated>
// Generated by tools/codegen/generate_onity_async_triggers.py. Do not edit by hand;
// change the generator and rerun it.
// </auto-generated>
using NUnit.Framework;
using Onity.Unity.Async.Triggers;
using UnityEngine;

namespace Onity.Tests.EditMode
{
    public sealed partial class OnityAsyncMessageTriggerEditModeTests
    {
        [Test]
        public void AnimatorIK_RaisesEveryWaitShape()
        {
            int layerIndex = 3;

            CheckValueMessage<OnityAsyncAnimatorIKTrigger, int>(
                "OnAnimatorIK",
                layerIndex, new object[] { layerIndex },
                gameObject => gameObject.GetAsyncAnimatorIKTrigger(),
                component => component.GetAsyncAnimatorIKTrigger(),
                trigger => trigger.OnAnimatorIKAsync(),
                (trigger, token) => trigger.OnAnimatorIKAsync(token),
                trigger => trigger.GetOnAnimatorIKAsyncHandler(),
                (trigger, token) => trigger.GetOnAnimatorIKAsyncHandler(token),
                handler => ((IOnityAsyncOnAnimatorIKHandler)handler).OnAnimatorIKAsync());
        }

        [Test]
        public void AnimatorMove_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncAnimatorMoveTrigger>(
                "OnAnimatorMove",
                gameObject => gameObject.GetAsyncAnimatorMoveTrigger(),
                component => component.GetAsyncAnimatorMoveTrigger(),
                trigger => trigger.OnAnimatorMoveAsync(),
                (trigger, token) => trigger.OnAnimatorMoveAsync(token),
                trigger => trigger.GetOnAnimatorMoveAsyncHandler(),
                (trigger, token) => trigger.GetOnAnimatorMoveAsyncHandler(token),
                handler => ((IOnityAsyncOnAnimatorMoveHandler)handler).OnAnimatorMoveAsync());
        }

        [Test]
        public void OnCanvasGroupChanged_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncOnCanvasGroupChangedTrigger>(
                "OnCanvasGroupChanged",
                gameObject => gameObject.GetAsyncOnCanvasGroupChangedTrigger(),
                component => component.GetAsyncOnCanvasGroupChangedTrigger(),
                trigger => trigger.OnCanvasGroupChangedAsync(),
                (trigger, token) => trigger.OnCanvasGroupChangedAsync(token),
                trigger => trigger.GetOnCanvasGroupChangedAsyncHandler(),
                (trigger, token) => trigger.GetOnCanvasGroupChangedAsyncHandler(token),
                handler => ((IOnityAsyncOnCanvasGroupChangedHandler)handler).OnCanvasGroupChangedAsync());
        }

        [Test]
        public void CollisionEnter2D_RaisesEveryWaitShape()
        {
            Collision2D coll = new Collision2D();

            CheckValueMessage<OnityAsyncCollisionEnter2DTrigger, Collision2D>(
                "OnCollisionEnter2D",
                coll, new object[] { coll },
                gameObject => gameObject.GetAsyncCollisionEnter2DTrigger(),
                component => component.GetAsyncCollisionEnter2DTrigger(),
                trigger => trigger.OnCollisionEnter2DAsync(),
                (trigger, token) => trigger.OnCollisionEnter2DAsync(token),
                trigger => trigger.GetOnCollisionEnter2DAsyncHandler(),
                (trigger, token) => trigger.GetOnCollisionEnter2DAsyncHandler(token),
                handler => ((IOnityAsyncOnCollisionEnter2DHandler)handler).OnCollisionEnter2DAsync());
        }

        [Test]
        public void CollisionExit2D_RaisesEveryWaitShape()
        {
            Collision2D coll = new Collision2D();

            CheckValueMessage<OnityAsyncCollisionExit2DTrigger, Collision2D>(
                "OnCollisionExit2D",
                coll, new object[] { coll },
                gameObject => gameObject.GetAsyncCollisionExit2DTrigger(),
                component => component.GetAsyncCollisionExit2DTrigger(),
                trigger => trigger.OnCollisionExit2DAsync(),
                (trigger, token) => trigger.OnCollisionExit2DAsync(token),
                trigger => trigger.GetOnCollisionExit2DAsyncHandler(),
                (trigger, token) => trigger.GetOnCollisionExit2DAsyncHandler(token),
                handler => ((IOnityAsyncOnCollisionExit2DHandler)handler).OnCollisionExit2DAsync());
        }

        [Test]
        public void CollisionStay2D_RaisesEveryWaitShape()
        {
            Collision2D coll = new Collision2D();

            CheckValueMessage<OnityAsyncCollisionStay2DTrigger, Collision2D>(
                "OnCollisionStay2D",
                coll, new object[] { coll },
                gameObject => gameObject.GetAsyncCollisionStay2DTrigger(),
                component => component.GetAsyncCollisionStay2DTrigger(),
                trigger => trigger.OnCollisionStay2DAsync(),
                (trigger, token) => trigger.OnCollisionStay2DAsync(token),
                trigger => trigger.GetOnCollisionStay2DAsyncHandler(),
                (trigger, token) => trigger.GetOnCollisionStay2DAsyncHandler(token),
                handler => ((IOnityAsyncOnCollisionStay2DHandler)handler).OnCollisionStay2DAsync());
        }

        [Test]
        public void CollisionEnter_RaisesEveryWaitShape()
        {
            Collision coll = new Collision();

            CheckValueMessage<OnityAsyncCollisionEnterTrigger, Collision>(
                "OnCollisionEnter",
                coll, new object[] { coll },
                gameObject => gameObject.GetAsyncCollisionEnterTrigger(),
                component => component.GetAsyncCollisionEnterTrigger(),
                trigger => trigger.OnCollisionEnterAsync(),
                (trigger, token) => trigger.OnCollisionEnterAsync(token),
                trigger => trigger.GetOnCollisionEnterAsyncHandler(),
                (trigger, token) => trigger.GetOnCollisionEnterAsyncHandler(token),
                handler => ((IOnityAsyncOnCollisionEnterHandler)handler).OnCollisionEnterAsync());
        }

        [Test]
        public void CollisionExit_RaisesEveryWaitShape()
        {
            Collision coll = new Collision();

            CheckValueMessage<OnityAsyncCollisionExitTrigger, Collision>(
                "OnCollisionExit",
                coll, new object[] { coll },
                gameObject => gameObject.GetAsyncCollisionExitTrigger(),
                component => component.GetAsyncCollisionExitTrigger(),
                trigger => trigger.OnCollisionExitAsync(),
                (trigger, token) => trigger.OnCollisionExitAsync(token),
                trigger => trigger.GetOnCollisionExitAsyncHandler(),
                (trigger, token) => trigger.GetOnCollisionExitAsyncHandler(token),
                handler => ((IOnityAsyncOnCollisionExitHandler)handler).OnCollisionExitAsync());
        }

        [Test]
        public void CollisionStay_RaisesEveryWaitShape()
        {
            Collision coll = new Collision();

            CheckValueMessage<OnityAsyncCollisionStayTrigger, Collision>(
                "OnCollisionStay",
                coll, new object[] { coll },
                gameObject => gameObject.GetAsyncCollisionStayTrigger(),
                component => component.GetAsyncCollisionStayTrigger(),
                trigger => trigger.OnCollisionStayAsync(),
                (trigger, token) => trigger.OnCollisionStayAsync(token),
                trigger => trigger.GetOnCollisionStayAsyncHandler(),
                (trigger, token) => trigger.GetOnCollisionStayAsyncHandler(token),
                handler => ((IOnityAsyncOnCollisionStayHandler)handler).OnCollisionStayAsync());
        }

        [Test]
        public void JointBreak_RaisesEveryWaitShape()
        {
            float breakForce = 12.5f;

            CheckValueMessage<OnityAsyncJointBreakTrigger, float>(
                "OnJointBreak",
                breakForce, new object[] { breakForce },
                gameObject => gameObject.GetAsyncJointBreakTrigger(),
                component => component.GetAsyncJointBreakTrigger(),
                trigger => trigger.OnJointBreakAsync(),
                (trigger, token) => trigger.OnJointBreakAsync(token),
                trigger => trigger.GetOnJointBreakAsyncHandler(),
                (trigger, token) => trigger.GetOnJointBreakAsyncHandler(token),
                handler => ((IOnityAsyncOnJointBreakHandler)handler).OnJointBreakAsync());
        }

        [Test]
        public void JointBreak2D_RaisesEveryWaitShape()
        {
            Joint2D brokenJoint = NewComponent<HingeJoint2D>();

            CheckValueMessage<OnityAsyncJointBreak2DTrigger, Joint2D>(
                "OnJointBreak2D",
                brokenJoint, new object[] { brokenJoint },
                gameObject => gameObject.GetAsyncJointBreak2DTrigger(),
                component => component.GetAsyncJointBreak2DTrigger(),
                trigger => trigger.OnJointBreak2DAsync(),
                (trigger, token) => trigger.OnJointBreak2DAsync(token),
                trigger => trigger.GetOnJointBreak2DAsyncHandler(),
                (trigger, token) => trigger.GetOnJointBreak2DAsyncHandler(token),
                handler => ((IOnityAsyncOnJointBreak2DHandler)handler).OnJointBreak2DAsync());
        }

        [Test]
        public void Update_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncUpdateTrigger>(
                "Update",
                gameObject => gameObject.GetAsyncUpdateTrigger(),
                component => component.GetAsyncUpdateTrigger(),
                trigger => trigger.UpdateAsync(),
                (trigger, token) => trigger.UpdateAsync(token),
                trigger => trigger.GetUpdateAsyncHandler(),
                (trigger, token) => trigger.GetUpdateAsyncHandler(token),
                handler => ((IOnityAsyncUpdateHandler)handler).UpdateAsync());
        }

        [Test]
        public void FixedUpdate_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncFixedUpdateTrigger>(
                "FixedUpdate",
                gameObject => gameObject.GetAsyncFixedUpdateTrigger(),
                component => component.GetAsyncFixedUpdateTrigger(),
                trigger => trigger.FixedUpdateAsync(),
                (trigger, token) => trigger.FixedUpdateAsync(token),
                trigger => trigger.GetFixedUpdateAsyncHandler(),
                (trigger, token) => trigger.GetFixedUpdateAsyncHandler(token),
                handler => ((IOnityAsyncFixedUpdateHandler)handler).FixedUpdateAsync());
        }

        [Test]
        public void LateUpdate_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncLateUpdateTrigger>(
                "LateUpdate",
                gameObject => gameObject.GetAsyncLateUpdateTrigger(),
                component => component.GetAsyncLateUpdateTrigger(),
                trigger => trigger.LateUpdateAsync(),
                (trigger, token) => trigger.LateUpdateAsync(token),
                trigger => trigger.GetLateUpdateAsyncHandler(),
                (trigger, token) => trigger.GetLateUpdateAsyncHandler(token),
                handler => ((IOnityAsyncLateUpdateHandler)handler).LateUpdateAsync());
        }

        [Test]
        public void ParticleCollision_RaisesEveryWaitShape()
        {
            GameObject other = NewObject();

            CheckValueMessage<OnityAsyncParticleCollisionTrigger, GameObject>(
                "OnParticleCollision",
                other, new object[] { other },
                gameObject => gameObject.GetAsyncParticleCollisionTrigger(),
                component => component.GetAsyncParticleCollisionTrigger(),
                trigger => trigger.OnParticleCollisionAsync(),
                (trigger, token) => trigger.OnParticleCollisionAsync(token),
                trigger => trigger.GetOnParticleCollisionAsyncHandler(),
                (trigger, token) => trigger.GetOnParticleCollisionAsyncHandler(token),
                handler => ((IOnityAsyncOnParticleCollisionHandler)handler).OnParticleCollisionAsync());
        }

        [Test]
        public void RectTransformDimensionsChange_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncRectTransformDimensionsChangeTrigger>(
                "OnRectTransformDimensionsChange",
                gameObject => gameObject.GetAsyncRectTransformDimensionsChangeTrigger(),
                component => component.GetAsyncRectTransformDimensionsChangeTrigger(),
                trigger => trigger.OnRectTransformDimensionsChangeAsync(),
                (trigger, token) => trigger.OnRectTransformDimensionsChangeAsync(token),
                trigger => trigger.GetOnRectTransformDimensionsChangeAsyncHandler(),
                (trigger, token) => trigger.GetOnRectTransformDimensionsChangeAsyncHandler(token),
                handler => ((IOnityAsyncOnRectTransformDimensionsChangeHandler)handler).OnRectTransformDimensionsChangeAsync());
        }

        [Test]
        public void RectTransformRemoved_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncRectTransformRemovedTrigger>(
                "OnRectTransformRemoved",
                gameObject => gameObject.GetAsyncRectTransformRemovedTrigger(),
                component => component.GetAsyncRectTransformRemovedTrigger(),
                trigger => trigger.OnRectTransformRemovedAsync(),
                (trigger, token) => trigger.OnRectTransformRemovedAsync(token),
                trigger => trigger.GetOnRectTransformRemovedAsyncHandler(),
                (trigger, token) => trigger.GetOnRectTransformRemovedAsyncHandler(token),
                handler => ((IOnityAsyncOnRectTransformRemovedHandler)handler).OnRectTransformRemovedAsync());
        }

        [Test]
        public void BeforeTransformParentChanged_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncBeforeTransformParentChangedTrigger>(
                "OnBeforeTransformParentChanged",
                gameObject => gameObject.GetAsyncBeforeTransformParentChangedTrigger(),
                component => component.GetAsyncBeforeTransformParentChangedTrigger(),
                trigger => trigger.OnBeforeTransformParentChangedAsync(),
                (trigger, token) => trigger.OnBeforeTransformParentChangedAsync(token),
                trigger => trigger.GetOnBeforeTransformParentChangedAsyncHandler(),
                (trigger, token) => trigger.GetOnBeforeTransformParentChangedAsyncHandler(token),
                handler => ((IOnityAsyncOnBeforeTransformParentChangedHandler)handler).OnBeforeTransformParentChangedAsync());
        }

        [Test]
        public void TransformParentChanged_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncTransformParentChangedTrigger>(
                "OnTransformParentChanged",
                gameObject => gameObject.GetAsyncTransformParentChangedTrigger(),
                component => component.GetAsyncTransformParentChangedTrigger(),
                trigger => trigger.OnTransformParentChangedAsync(),
                (trigger, token) => trigger.OnTransformParentChangedAsync(token),
                trigger => trigger.GetOnTransformParentChangedAsyncHandler(),
                (trigger, token) => trigger.GetOnTransformParentChangedAsyncHandler(token),
                handler => ((IOnityAsyncOnTransformParentChangedHandler)handler).OnTransformParentChangedAsync());
        }

        [Test]
        public void TransformChildrenChanged_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncTransformChildrenChangedTrigger>(
                "OnTransformChildrenChanged",
                gameObject => gameObject.GetAsyncTransformChildrenChangedTrigger(),
                component => component.GetAsyncTransformChildrenChangedTrigger(),
                trigger => trigger.OnTransformChildrenChangedAsync(),
                (trigger, token) => trigger.OnTransformChildrenChangedAsync(token),
                trigger => trigger.GetOnTransformChildrenChangedAsyncHandler(),
                (trigger, token) => trigger.GetOnTransformChildrenChangedAsyncHandler(token),
                handler => ((IOnityAsyncOnTransformChildrenChangedHandler)handler).OnTransformChildrenChangedAsync());
        }

        [Test]
        public void TriggerEnter2D_RaisesEveryWaitShape()
        {
            Collider2D other = NewComponent<BoxCollider2D>();

            CheckValueMessage<OnityAsyncTriggerEnter2DTrigger, Collider2D>(
                "OnTriggerEnter2D",
                other, new object[] { other },
                gameObject => gameObject.GetAsyncTriggerEnter2DTrigger(),
                component => component.GetAsyncTriggerEnter2DTrigger(),
                trigger => trigger.OnTriggerEnter2DAsync(),
                (trigger, token) => trigger.OnTriggerEnter2DAsync(token),
                trigger => trigger.GetOnTriggerEnter2DAsyncHandler(),
                (trigger, token) => trigger.GetOnTriggerEnter2DAsyncHandler(token),
                handler => ((IOnityAsyncOnTriggerEnter2DHandler)handler).OnTriggerEnter2DAsync());
        }

        [Test]
        public void TriggerExit2D_RaisesEveryWaitShape()
        {
            Collider2D other = NewComponent<BoxCollider2D>();

            CheckValueMessage<OnityAsyncTriggerExit2DTrigger, Collider2D>(
                "OnTriggerExit2D",
                other, new object[] { other },
                gameObject => gameObject.GetAsyncTriggerExit2DTrigger(),
                component => component.GetAsyncTriggerExit2DTrigger(),
                trigger => trigger.OnTriggerExit2DAsync(),
                (trigger, token) => trigger.OnTriggerExit2DAsync(token),
                trigger => trigger.GetOnTriggerExit2DAsyncHandler(),
                (trigger, token) => trigger.GetOnTriggerExit2DAsyncHandler(token),
                handler => ((IOnityAsyncOnTriggerExit2DHandler)handler).OnTriggerExit2DAsync());
        }

        [Test]
        public void TriggerStay2D_RaisesEveryWaitShape()
        {
            Collider2D other = NewComponent<BoxCollider2D>();

            CheckValueMessage<OnityAsyncTriggerStay2DTrigger, Collider2D>(
                "OnTriggerStay2D",
                other, new object[] { other },
                gameObject => gameObject.GetAsyncTriggerStay2DTrigger(),
                component => component.GetAsyncTriggerStay2DTrigger(),
                trigger => trigger.OnTriggerStay2DAsync(),
                (trigger, token) => trigger.OnTriggerStay2DAsync(token),
                trigger => trigger.GetOnTriggerStay2DAsyncHandler(),
                (trigger, token) => trigger.GetOnTriggerStay2DAsyncHandler(token),
                handler => ((IOnityAsyncOnTriggerStay2DHandler)handler).OnTriggerStay2DAsync());
        }

        [Test]
        public void TriggerEnter_RaisesEveryWaitShape()
        {
            Collider other = NewComponent<BoxCollider>();

            CheckValueMessage<OnityAsyncTriggerEnterTrigger, Collider>(
                "OnTriggerEnter",
                other, new object[] { other },
                gameObject => gameObject.GetAsyncTriggerEnterTrigger(),
                component => component.GetAsyncTriggerEnterTrigger(),
                trigger => trigger.OnTriggerEnterAsync(),
                (trigger, token) => trigger.OnTriggerEnterAsync(token),
                trigger => trigger.GetOnTriggerEnterAsyncHandler(),
                (trigger, token) => trigger.GetOnTriggerEnterAsyncHandler(token),
                handler => ((IOnityAsyncOnTriggerEnterHandler)handler).OnTriggerEnterAsync());
        }

        [Test]
        public void TriggerExit_RaisesEveryWaitShape()
        {
            Collider other = NewComponent<BoxCollider>();

            CheckValueMessage<OnityAsyncTriggerExitTrigger, Collider>(
                "OnTriggerExit",
                other, new object[] { other },
                gameObject => gameObject.GetAsyncTriggerExitTrigger(),
                component => component.GetAsyncTriggerExitTrigger(),
                trigger => trigger.OnTriggerExitAsync(),
                (trigger, token) => trigger.OnTriggerExitAsync(token),
                trigger => trigger.GetOnTriggerExitAsyncHandler(),
                (trigger, token) => trigger.GetOnTriggerExitAsyncHandler(token),
                handler => ((IOnityAsyncOnTriggerExitHandler)handler).OnTriggerExitAsync());
        }

        [Test]
        public void TriggerStay_RaisesEveryWaitShape()
        {
            Collider other = NewComponent<BoxCollider>();

            CheckValueMessage<OnityAsyncTriggerStayTrigger, Collider>(
                "OnTriggerStay",
                other, new object[] { other },
                gameObject => gameObject.GetAsyncTriggerStayTrigger(),
                component => component.GetAsyncTriggerStayTrigger(),
                trigger => trigger.OnTriggerStayAsync(),
                (trigger, token) => trigger.OnTriggerStayAsync(token),
                trigger => trigger.GetOnTriggerStayAsyncHandler(),
                (trigger, token) => trigger.GetOnTriggerStayAsyncHandler(token),
                handler => ((IOnityAsyncOnTriggerStayHandler)handler).OnTriggerStayAsync());
        }

        [Test]
        public void BecameInvisible_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncBecameInvisibleTrigger>(
                "OnBecameInvisible",
                gameObject => gameObject.GetAsyncBecameInvisibleTrigger(),
                component => component.GetAsyncBecameInvisibleTrigger(),
                trigger => trigger.OnBecameInvisibleAsync(),
                (trigger, token) => trigger.OnBecameInvisibleAsync(token),
                trigger => trigger.GetOnBecameInvisibleAsyncHandler(),
                (trigger, token) => trigger.GetOnBecameInvisibleAsyncHandler(token),
                handler => ((IOnityAsyncOnBecameInvisibleHandler)handler).OnBecameInvisibleAsync());
        }

        [Test]
        public void BecameVisible_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncBecameVisibleTrigger>(
                "OnBecameVisible",
                gameObject => gameObject.GetAsyncBecameVisibleTrigger(),
                component => component.GetAsyncBecameVisibleTrigger(),
                trigger => trigger.OnBecameVisibleAsync(),
                (trigger, token) => trigger.OnBecameVisibleAsync(token),
                trigger => trigger.GetOnBecameVisibleAsyncHandler(),
                (trigger, token) => trigger.GetOnBecameVisibleAsyncHandler(token),
                handler => ((IOnityAsyncOnBecameVisibleHandler)handler).OnBecameVisibleAsync());
        }

#if !(UNITY_IPHONE || UNITY_ANDROID || UNITY_METRO)
        [Test]
        public void MouseDown_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncMouseDownTrigger>(
                "OnMouseDown",
                gameObject => gameObject.GetAsyncMouseDownTrigger(),
                component => component.GetAsyncMouseDownTrigger(),
                trigger => trigger.OnMouseDownAsync(),
                (trigger, token) => trigger.OnMouseDownAsync(token),
                trigger => trigger.GetOnMouseDownAsyncHandler(),
                (trigger, token) => trigger.GetOnMouseDownAsyncHandler(token),
                handler => ((IOnityAsyncOnMouseDownHandler)handler).OnMouseDownAsync());
        }
#endif

#if !(UNITY_IPHONE || UNITY_ANDROID || UNITY_METRO)
        [Test]
        public void MouseDrag_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncMouseDragTrigger>(
                "OnMouseDrag",
                gameObject => gameObject.GetAsyncMouseDragTrigger(),
                component => component.GetAsyncMouseDragTrigger(),
                trigger => trigger.OnMouseDragAsync(),
                (trigger, token) => trigger.OnMouseDragAsync(token),
                trigger => trigger.GetOnMouseDragAsyncHandler(),
                (trigger, token) => trigger.GetOnMouseDragAsyncHandler(token),
                handler => ((IOnityAsyncOnMouseDragHandler)handler).OnMouseDragAsync());
        }
#endif

#if !(UNITY_IPHONE || UNITY_ANDROID || UNITY_METRO)
        [Test]
        public void MouseEnter_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncMouseEnterTrigger>(
                "OnMouseEnter",
                gameObject => gameObject.GetAsyncMouseEnterTrigger(),
                component => component.GetAsyncMouseEnterTrigger(),
                trigger => trigger.OnMouseEnterAsync(),
                (trigger, token) => trigger.OnMouseEnterAsync(token),
                trigger => trigger.GetOnMouseEnterAsyncHandler(),
                (trigger, token) => trigger.GetOnMouseEnterAsyncHandler(token),
                handler => ((IOnityAsyncOnMouseEnterHandler)handler).OnMouseEnterAsync());
        }
#endif

#if !(UNITY_IPHONE || UNITY_ANDROID || UNITY_METRO)
        [Test]
        public void MouseExit_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncMouseExitTrigger>(
                "OnMouseExit",
                gameObject => gameObject.GetAsyncMouseExitTrigger(),
                component => component.GetAsyncMouseExitTrigger(),
                trigger => trigger.OnMouseExitAsync(),
                (trigger, token) => trigger.OnMouseExitAsync(token),
                trigger => trigger.GetOnMouseExitAsyncHandler(),
                (trigger, token) => trigger.GetOnMouseExitAsyncHandler(token),
                handler => ((IOnityAsyncOnMouseExitHandler)handler).OnMouseExitAsync());
        }
#endif

#if !(UNITY_IPHONE || UNITY_ANDROID || UNITY_METRO)
        [Test]
        public void MouseOver_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncMouseOverTrigger>(
                "OnMouseOver",
                gameObject => gameObject.GetAsyncMouseOverTrigger(),
                component => component.GetAsyncMouseOverTrigger(),
                trigger => trigger.OnMouseOverAsync(),
                (trigger, token) => trigger.OnMouseOverAsync(token),
                trigger => trigger.GetOnMouseOverAsyncHandler(),
                (trigger, token) => trigger.GetOnMouseOverAsyncHandler(token),
                handler => ((IOnityAsyncOnMouseOverHandler)handler).OnMouseOverAsync());
        }
#endif

#if !(UNITY_IPHONE || UNITY_ANDROID || UNITY_METRO)
        [Test]
        public void MouseUp_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncMouseUpTrigger>(
                "OnMouseUp",
                gameObject => gameObject.GetAsyncMouseUpTrigger(),
                component => component.GetAsyncMouseUpTrigger(),
                trigger => trigger.OnMouseUpAsync(),
                (trigger, token) => trigger.OnMouseUpAsync(token),
                trigger => trigger.GetOnMouseUpAsyncHandler(),
                (trigger, token) => trigger.GetOnMouseUpAsyncHandler(token),
                handler => ((IOnityAsyncOnMouseUpHandler)handler).OnMouseUpAsync());
        }
#endif

#if !(UNITY_IPHONE || UNITY_ANDROID || UNITY_METRO)
        [Test]
        public void MouseUpAsButton_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncMouseUpAsButtonTrigger>(
                "OnMouseUpAsButton",
                gameObject => gameObject.GetAsyncMouseUpAsButtonTrigger(),
                component => component.GetAsyncMouseUpAsButtonTrigger(),
                trigger => trigger.OnMouseUpAsButtonAsync(),
                (trigger, token) => trigger.OnMouseUpAsButtonAsync(token),
                trigger => trigger.GetOnMouseUpAsButtonAsyncHandler(),
                (trigger, token) => trigger.GetOnMouseUpAsButtonAsyncHandler(token),
                handler => ((IOnityAsyncOnMouseUpAsButtonHandler)handler).OnMouseUpAsButtonAsync());
        }
#endif

        [Test]
        public void ApplicationFocus_RaisesEveryWaitShape()
        {
            bool hasFocus = true;

            CheckValueMessage<OnityAsyncApplicationFocusTrigger, bool>(
                "OnApplicationFocus",
                hasFocus, new object[] { hasFocus },
                gameObject => gameObject.GetAsyncApplicationFocusTrigger(),
                component => component.GetAsyncApplicationFocusTrigger(),
                trigger => trigger.OnApplicationFocusAsync(),
                (trigger, token) => trigger.OnApplicationFocusAsync(token),
                trigger => trigger.GetOnApplicationFocusAsyncHandler(),
                (trigger, token) => trigger.GetOnApplicationFocusAsyncHandler(token),
                handler => ((IOnityAsyncOnApplicationFocusHandler)handler).OnApplicationFocusAsync());
        }

        [Test]
        public void ApplicationPause_RaisesEveryWaitShape()
        {
            bool pauseStatus = true;

            CheckValueMessage<OnityAsyncApplicationPauseTrigger, bool>(
                "OnApplicationPause",
                pauseStatus, new object[] { pauseStatus },
                gameObject => gameObject.GetAsyncApplicationPauseTrigger(),
                component => component.GetAsyncApplicationPauseTrigger(),
                trigger => trigger.OnApplicationPauseAsync(),
                (trigger, token) => trigger.OnApplicationPauseAsync(token),
                trigger => trigger.GetOnApplicationPauseAsyncHandler(),
                (trigger, token) => trigger.GetOnApplicationPauseAsyncHandler(token),
                handler => ((IOnityAsyncOnApplicationPauseHandler)handler).OnApplicationPauseAsync());
        }

        [Test]
        public void ApplicationQuit_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncApplicationQuitTrigger>(
                "OnApplicationQuit",
                gameObject => gameObject.GetAsyncApplicationQuitTrigger(),
                component => component.GetAsyncApplicationQuitTrigger(),
                trigger => trigger.OnApplicationQuitAsync(),
                (trigger, token) => trigger.OnApplicationQuitAsync(token),
                trigger => trigger.GetOnApplicationQuitAsyncHandler(),
                (trigger, token) => trigger.GetOnApplicationQuitAsyncHandler(token),
                handler => ((IOnityAsyncOnApplicationQuitHandler)handler).OnApplicationQuitAsync());
        }

        [Test]
        public void AudioFilterRead_RaisesEveryWaitShape()
        {
            float[] data = new float[4];
            int channels = 3;

            CheckValueMessage<OnityAsyncAudioFilterReadTrigger, (float[] data, int channels)>(
                "OnAudioFilterRead",
                (data, channels), new object[] { data, channels },
                gameObject => gameObject.GetAsyncAudioFilterReadTrigger(),
                component => component.GetAsyncAudioFilterReadTrigger(),
                trigger => trigger.OnAudioFilterReadAsync(),
                (trigger, token) => trigger.OnAudioFilterReadAsync(token),
                trigger => trigger.GetOnAudioFilterReadAsyncHandler(),
                (trigger, token) => trigger.GetOnAudioFilterReadAsyncHandler(token),
                handler => ((IOnityAsyncOnAudioFilterReadHandler)handler).OnAudioFilterReadAsync());
        }

        [Test]
        public void ControllerColliderHit_RaisesEveryWaitShape()
        {
            ControllerColliderHit hit = new ControllerColliderHit();

            CheckValueMessage<OnityAsyncControllerColliderHitTrigger, ControllerColliderHit>(
                "OnControllerColliderHit",
                hit, new object[] { hit },
                gameObject => gameObject.GetAsyncControllerColliderHitTrigger(),
                component => component.GetAsyncControllerColliderHitTrigger(),
                trigger => trigger.OnControllerColliderHitAsync(),
                (trigger, token) => trigger.OnControllerColliderHitAsync(token),
                trigger => trigger.GetOnControllerColliderHitAsyncHandler(),
                (trigger, token) => trigger.GetOnControllerColliderHitAsyncHandler(token),
                handler => ((IOnityAsyncOnControllerColliderHitHandler)handler).OnControllerColliderHitAsync());
        }

        [Test]
        public void DrawGizmos_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncDrawGizmosTrigger>(
                "OnDrawGizmos",
                gameObject => gameObject.GetAsyncDrawGizmosTrigger(),
                component => component.GetAsyncDrawGizmosTrigger(),
                trigger => trigger.OnDrawGizmosAsync(),
                (trigger, token) => trigger.OnDrawGizmosAsync(token),
                trigger => trigger.GetOnDrawGizmosAsyncHandler(),
                (trigger, token) => trigger.GetOnDrawGizmosAsyncHandler(token),
                handler => ((IOnityAsyncOnDrawGizmosHandler)handler).OnDrawGizmosAsync());
        }

        [Test]
        public void DrawGizmosSelected_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncDrawGizmosSelectedTrigger>(
                "OnDrawGizmosSelected",
                gameObject => gameObject.GetAsyncDrawGizmosSelectedTrigger(),
                component => component.GetAsyncDrawGizmosSelectedTrigger(),
                trigger => trigger.OnDrawGizmosSelectedAsync(),
                (trigger, token) => trigger.OnDrawGizmosSelectedAsync(token),
                trigger => trigger.GetOnDrawGizmosSelectedAsyncHandler(),
                (trigger, token) => trigger.GetOnDrawGizmosSelectedAsyncHandler(token),
                handler => ((IOnityAsyncOnDrawGizmosSelectedHandler)handler).OnDrawGizmosSelectedAsync());
        }

        [Test]
        public void GUI_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncGUITrigger>(
                "OnGUI",
                gameObject => gameObject.GetAsyncGUITrigger(),
                component => component.GetAsyncGUITrigger(),
                trigger => trigger.OnGUIAsync(),
                (trigger, token) => trigger.OnGUIAsync(token),
                trigger => trigger.GetOnGUIAsyncHandler(),
                (trigger, token) => trigger.GetOnGUIAsyncHandler(token),
                handler => ((IOnityAsyncOnGUIHandler)handler).OnGUIAsync());
        }

        [Test]
        public void ParticleSystemStopped_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncParticleSystemStoppedTrigger>(
                "OnParticleSystemStopped",
                gameObject => gameObject.GetAsyncParticleSystemStoppedTrigger(),
                component => component.GetAsyncParticleSystemStoppedTrigger(),
                trigger => trigger.OnParticleSystemStoppedAsync(),
                (trigger, token) => trigger.OnParticleSystemStoppedAsync(token),
                trigger => trigger.GetOnParticleSystemStoppedAsyncHandler(),
                (trigger, token) => trigger.GetOnParticleSystemStoppedAsyncHandler(token),
                handler => ((IOnityAsyncOnParticleSystemStoppedHandler)handler).OnParticleSystemStoppedAsync());
        }

        [Test]
        public void ParticleTrigger_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncParticleTriggerTrigger>(
                "OnParticleTrigger",
                gameObject => gameObject.GetAsyncParticleTriggerTrigger(),
                component => component.GetAsyncParticleTriggerTrigger(),
                trigger => trigger.OnParticleTriggerAsync(),
                (trigger, token) => trigger.OnParticleTriggerAsync(token),
                trigger => trigger.GetOnParticleTriggerAsyncHandler(),
                (trigger, token) => trigger.GetOnParticleTriggerAsyncHandler(token),
                handler => ((IOnityAsyncOnParticleTriggerHandler)handler).OnParticleTriggerAsync());
        }

        [Test]
        public void PostRender_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncPostRenderTrigger>(
                "OnPostRender",
                gameObject => gameObject.GetAsyncPostRenderTrigger(),
                component => component.GetAsyncPostRenderTrigger(),
                trigger => trigger.OnPostRenderAsync(),
                (trigger, token) => trigger.OnPostRenderAsync(token),
                trigger => trigger.GetOnPostRenderAsyncHandler(),
                (trigger, token) => trigger.GetOnPostRenderAsyncHandler(token),
                handler => ((IOnityAsyncOnPostRenderHandler)handler).OnPostRenderAsync());
        }

        [Test]
        public void PreCull_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncPreCullTrigger>(
                "OnPreCull",
                gameObject => gameObject.GetAsyncPreCullTrigger(),
                component => component.GetAsyncPreCullTrigger(),
                trigger => trigger.OnPreCullAsync(),
                (trigger, token) => trigger.OnPreCullAsync(token),
                trigger => trigger.GetOnPreCullAsyncHandler(),
                (trigger, token) => trigger.GetOnPreCullAsyncHandler(token),
                handler => ((IOnityAsyncOnPreCullHandler)handler).OnPreCullAsync());
        }

        [Test]
        public void PreRender_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncPreRenderTrigger>(
                "OnPreRender",
                gameObject => gameObject.GetAsyncPreRenderTrigger(),
                component => component.GetAsyncPreRenderTrigger(),
                trigger => trigger.OnPreRenderAsync(),
                (trigger, token) => trigger.OnPreRenderAsync(token),
                trigger => trigger.GetOnPreRenderAsyncHandler(),
                (trigger, token) => trigger.GetOnPreRenderAsyncHandler(token),
                handler => ((IOnityAsyncOnPreRenderHandler)handler).OnPreRenderAsync());
        }

        [Test]
        public void RenderImage_RaisesEveryWaitShape()
        {
            RenderTexture source = null;
            RenderTexture destination = null;

            CheckValueMessage<OnityAsyncRenderImageTrigger, (RenderTexture source, RenderTexture destination)>(
                "OnRenderImage",
                (source, destination), new object[] { source, destination },
                gameObject => gameObject.GetAsyncRenderImageTrigger(),
                component => component.GetAsyncRenderImageTrigger(),
                trigger => trigger.OnRenderImageAsync(),
                (trigger, token) => trigger.OnRenderImageAsync(token),
                trigger => trigger.GetOnRenderImageAsyncHandler(),
                (trigger, token) => trigger.GetOnRenderImageAsyncHandler(token),
                handler => ((IOnityAsyncOnRenderImageHandler)handler).OnRenderImageAsync());
        }

        [Test]
        public void RenderObject_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncRenderObjectTrigger>(
                "OnRenderObject",
                gameObject => gameObject.GetAsyncRenderObjectTrigger(),
                component => component.GetAsyncRenderObjectTrigger(),
                trigger => trigger.OnRenderObjectAsync(),
                (trigger, token) => trigger.OnRenderObjectAsync(token),
                trigger => trigger.GetOnRenderObjectAsyncHandler(),
                (trigger, token) => trigger.GetOnRenderObjectAsyncHandler(token),
                handler => ((IOnityAsyncOnRenderObjectHandler)handler).OnRenderObjectAsync());
        }

        [Test]
        public void ServerInitialized_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncServerInitializedTrigger>(
                "OnServerInitialized",
                gameObject => gameObject.GetAsyncServerInitializedTrigger(),
                component => component.GetAsyncServerInitializedTrigger(),
                trigger => trigger.OnServerInitializedAsync(),
                (trigger, token) => trigger.OnServerInitializedAsync(token),
                trigger => trigger.GetOnServerInitializedAsyncHandler(),
                (trigger, token) => trigger.GetOnServerInitializedAsyncHandler(token),
                handler => ((IOnityAsyncOnServerInitializedHandler)handler).OnServerInitializedAsync());
        }

        [Test]
        public void Validate_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncValidateTrigger>(
                "OnValidate",
                gameObject => gameObject.GetAsyncValidateTrigger(),
                component => component.GetAsyncValidateTrigger(),
                trigger => trigger.OnValidateAsync(),
                (trigger, token) => trigger.OnValidateAsync(token),
                trigger => trigger.GetOnValidateAsyncHandler(),
                (trigger, token) => trigger.GetOnValidateAsyncHandler(token),
                handler => ((IOnityAsyncOnValidateHandler)handler).OnValidateAsync());
        }

        [Test]
        public void WillRenderObject_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncWillRenderObjectTrigger>(
                "OnWillRenderObject",
                gameObject => gameObject.GetAsyncWillRenderObjectTrigger(),
                component => component.GetAsyncWillRenderObjectTrigger(),
                trigger => trigger.OnWillRenderObjectAsync(),
                (trigger, token) => trigger.OnWillRenderObjectAsync(token),
                trigger => trigger.GetOnWillRenderObjectAsyncHandler(),
                (trigger, token) => trigger.GetOnWillRenderObjectAsyncHandler(token),
                handler => ((IOnityAsyncOnWillRenderObjectHandler)handler).OnWillRenderObjectAsync());
        }

        [Test]
        public void Reset_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncResetTrigger>(
                "Reset",
                gameObject => gameObject.GetAsyncResetTrigger(),
                component => component.GetAsyncResetTrigger(),
                trigger => trigger.ResetAsync(),
                (trigger, token) => trigger.ResetAsync(token),
                trigger => trigger.GetResetAsyncHandler(),
                (trigger, token) => trigger.GetResetAsyncHandler(token),
                handler => ((IOnityAsyncResetHandler)handler).ResetAsync());
        }

        [Test]
        public void ParticleUpdateJobScheduled_RaisesEveryWaitShape()
        {
            CheckUnitMessage<OnityAsyncParticleUpdateJobScheduledTrigger>(
                "OnParticleUpdateJobScheduled",
                gameObject => gameObject.GetAsyncParticleUpdateJobScheduledTrigger(),
                component => component.GetAsyncParticleUpdateJobScheduledTrigger(),
                trigger => trigger.OnParticleUpdateJobScheduledAsync(),
                (trigger, token) => trigger.OnParticleUpdateJobScheduledAsync(token),
                trigger => trigger.GetOnParticleUpdateJobScheduledAsyncHandler(),
                (trigger, token) => trigger.GetOnParticleUpdateJobScheduledAsyncHandler(token),
                handler => ((IOnityAsyncOnParticleUpdateJobScheduledHandler)handler).OnParticleUpdateJobScheduledAsync());
        }
    }
}
