// <auto-generated>
// Generated by tools/codegen/generate_onity_async_triggers.py. Do not edit by hand;
// change the generator and rerun it.
// </auto-generated>
using System;
using System.Threading;
using UnityEngine;
using UnityEngine.EventSystems;

namespace Onity.Unity.Async.Triggers
{
#region BeginDrag

    /// <summary>
    /// Waits for the next <c>OnBeginDrag</c> event, which the event system sends when the pointer starts
    /// dragging this object (UniTask <c>IAsyncOnBeginDragHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnBeginDragHandler
    {
        /// <summary>Waits for the next <c>OnBeginDrag</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<PointerEventData> OnBeginDragAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnBeginDrag</c> event, which the event system sends when the pointer starts dragging
    /// this object (UniTask <c>AsyncBeginDragTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncBeginDragTrigger : OnityAsyncTriggerBase<PointerEventData>, IBeginDragHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnBeginDragAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnBeginDragHandler GetOnBeginDragAsyncHandler()
        {
            return new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnBeginDragAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnBeginDragHandler GetOnBeginDragAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncPointerEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnBeginDrag</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnBeginDragAsync()
        {
            return ((IOnityAsyncOnBeginDragHandler)new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, true)).OnBeginDragAsync();
        }

        /// <summary>Waits for the next <c>OnBeginDrag</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnBeginDragAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnBeginDragHandler)new OnityAsyncPointerEventDataHandler(this, cancellationToken, true)).OnBeginDragAsync();
        }

        void IBeginDragHandler.OnBeginDrag(PointerEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region Cancel

    /// <summary>
    /// Waits for the next <c>OnCancel</c> event, which the event system sends when the Cancel input is raised
    /// while this object is selected (UniTask <c>IAsyncOnCancelHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnCancelHandler
    {
        /// <summary>Waits for the next <c>OnCancel</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<BaseEventData> OnCancelAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnCancel</c> event, which the event system sends when the Cancel input is raised
    /// while this object is selected (UniTask <c>AsyncCancelTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncCancelTrigger : OnityAsyncTriggerBase<BaseEventData>, ICancelHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnCancelAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnCancelHandler GetOnCancelAsyncHandler()
        {
            return new OnityAsyncBaseEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnCancelAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnCancelHandler GetOnCancelAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncBaseEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnCancel</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<BaseEventData> OnCancelAsync()
        {
            return ((IOnityAsyncOnCancelHandler)new OnityAsyncBaseEventDataHandler(this, CancellationToken.None, true)).OnCancelAsync();
        }

        /// <summary>Waits for the next <c>OnCancel</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<BaseEventData> OnCancelAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnCancelHandler)new OnityAsyncBaseEventDataHandler(this, cancellationToken, true)).OnCancelAsync();
        }

        void ICancelHandler.OnCancel(BaseEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region Deselect

    /// <summary>
    /// Waits for the next <c>OnDeselect</c> event, which the event system sends when this object stops being
    /// the selected object (UniTask <c>IAsyncOnDeselectHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnDeselectHandler
    {
        /// <summary>Waits for the next <c>OnDeselect</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<BaseEventData> OnDeselectAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnDeselect</c> event, which the event system sends when this object stops being the
    /// selected object (UniTask <c>AsyncDeselectTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncDeselectTrigger : OnityAsyncTriggerBase<BaseEventData>, IDeselectHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnDeselectAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnDeselectHandler GetOnDeselectAsyncHandler()
        {
            return new OnityAsyncBaseEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnDeselectAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnDeselectHandler GetOnDeselectAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncBaseEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnDeselect</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<BaseEventData> OnDeselectAsync()
        {
            return ((IOnityAsyncOnDeselectHandler)new OnityAsyncBaseEventDataHandler(this, CancellationToken.None, true)).OnDeselectAsync();
        }

        /// <summary>Waits for the next <c>OnDeselect</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<BaseEventData> OnDeselectAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnDeselectHandler)new OnityAsyncBaseEventDataHandler(this, cancellationToken, true)).OnDeselectAsync();
        }

        void IDeselectHandler.OnDeselect(BaseEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region Drag

    /// <summary>
    /// Waits for the next <c>OnDrag</c> event, which the event system sends on every pointer move while this
    /// object is being dragged (UniTask <c>IAsyncOnDragHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnDragHandler
    {
        /// <summary>Waits for the next <c>OnDrag</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<PointerEventData> OnDragAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnDrag</c> event, which the event system sends on every pointer move while this
    /// object is being dragged (UniTask <c>AsyncDragTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncDragTrigger : OnityAsyncTriggerBase<PointerEventData>, IDragHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnDragAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnDragHandler GetOnDragAsyncHandler()
        {
            return new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnDragAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnDragHandler GetOnDragAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncPointerEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnDrag</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnDragAsync()
        {
            return ((IOnityAsyncOnDragHandler)new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, true)).OnDragAsync();
        }

        /// <summary>Waits for the next <c>OnDrag</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnDragAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnDragHandler)new OnityAsyncPointerEventDataHandler(this, cancellationToken, true)).OnDragAsync();
        }

        void IDragHandler.OnDrag(PointerEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region Drop

    /// <summary>
    /// Waits for the next <c>OnDrop</c> event, which the event system sends when a dragged object is dropped on
    /// this object (UniTask <c>IAsyncOnDropHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnDropHandler
    {
        /// <summary>Waits for the next <c>OnDrop</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<PointerEventData> OnDropAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnDrop</c> event, which the event system sends when a dragged object is dropped on
    /// this object (UniTask <c>AsyncDropTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncDropTrigger : OnityAsyncTriggerBase<PointerEventData>, IDropHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnDropAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnDropHandler GetOnDropAsyncHandler()
        {
            return new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnDropAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnDropHandler GetOnDropAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncPointerEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnDrop</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnDropAsync()
        {
            return ((IOnityAsyncOnDropHandler)new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, true)).OnDropAsync();
        }

        /// <summary>Waits for the next <c>OnDrop</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnDropAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnDropHandler)new OnityAsyncPointerEventDataHandler(this, cancellationToken, true)).OnDropAsync();
        }

        void IDropHandler.OnDrop(PointerEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region EndDrag

    /// <summary>
    /// Waits for the next <c>OnEndDrag</c> event, which the event system sends when a drag of this object ends
    /// (UniTask <c>IAsyncOnEndDragHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnEndDragHandler
    {
        /// <summary>Waits for the next <c>OnEndDrag</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<PointerEventData> OnEndDragAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnEndDrag</c> event, which the event system sends when a drag of this object ends
    /// (UniTask <c>AsyncEndDragTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncEndDragTrigger : OnityAsyncTriggerBase<PointerEventData>, IEndDragHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnEndDragAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnEndDragHandler GetOnEndDragAsyncHandler()
        {
            return new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnEndDragAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnEndDragHandler GetOnEndDragAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncPointerEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnEndDrag</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnEndDragAsync()
        {
            return ((IOnityAsyncOnEndDragHandler)new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, true)).OnEndDragAsync();
        }

        /// <summary>Waits for the next <c>OnEndDrag</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnEndDragAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnEndDragHandler)new OnityAsyncPointerEventDataHandler(this, cancellationToken, true)).OnEndDragAsync();
        }

        void IEndDragHandler.OnEndDrag(PointerEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region InitializePotentialDrag

    /// <summary>
    /// Waits for the next <c>OnInitializePotentialDrag</c> event, which the event system sends when a pointer
    /// press may start a drag of this object (UniTask <c>IAsyncOnInitializePotentialDragHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnInitializePotentialDragHandler
    {
        /// <summary>Waits for the next <c>OnInitializePotentialDrag</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<PointerEventData> OnInitializePotentialDragAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnInitializePotentialDrag</c> event, which the event system sends when a pointer
    /// press may start a drag of this object (UniTask <c>AsyncInitializePotentialDragTrigger</c> parity). The
    /// component itself is an <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncInitializePotentialDragTrigger : OnityAsyncTriggerBase<PointerEventData>, IInitializePotentialDragHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnInitializePotentialDragAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnInitializePotentialDragHandler GetOnInitializePotentialDragAsyncHandler()
        {
            return new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnInitializePotentialDragAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnInitializePotentialDragHandler GetOnInitializePotentialDragAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncPointerEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnInitializePotentialDrag</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnInitializePotentialDragAsync()
        {
            return ((IOnityAsyncOnInitializePotentialDragHandler)new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, true)).OnInitializePotentialDragAsync();
        }

        /// <summary>Waits for the next <c>OnInitializePotentialDrag</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnInitializePotentialDragAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnInitializePotentialDragHandler)new OnityAsyncPointerEventDataHandler(this, cancellationToken, true)).OnInitializePotentialDragAsync();
        }

        void IInitializePotentialDragHandler.OnInitializePotentialDrag(PointerEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region Move

    /// <summary>
    /// Waits for the next <c>OnMove</c> event, which the event system sends when a move input such as an arrow
    /// key or a gamepad stick is raised while this object is selected (UniTask <c>IAsyncOnMoveHandler</c>
    /// parity).
    /// </summary>
    public interface IOnityAsyncOnMoveHandler
    {
        /// <summary>Waits for the next <c>OnMove</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<AxisEventData> OnMoveAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnMove</c> event, which the event system sends when a move input such as an arrow key
    /// or a gamepad stick is raised while this object is selected (UniTask <c>AsyncMoveTrigger</c> parity). The
    /// component itself is an <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncMoveTrigger : OnityAsyncTriggerBase<AxisEventData>, IMoveHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnMoveAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnMoveHandler GetOnMoveAsyncHandler()
        {
            return new OnityAsyncAxisEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnMoveAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnMoveHandler GetOnMoveAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncAxisEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnMove</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<AxisEventData> OnMoveAsync()
        {
            return ((IOnityAsyncOnMoveHandler)new OnityAsyncAxisEventDataHandler(this, CancellationToken.None, true)).OnMoveAsync();
        }

        /// <summary>Waits for the next <c>OnMove</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<AxisEventData> OnMoveAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnMoveHandler)new OnityAsyncAxisEventDataHandler(this, cancellationToken, true)).OnMoveAsync();
        }

        void IMoveHandler.OnMove(AxisEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region PointerClick

    /// <summary>
    /// Waits for the next <c>OnPointerClick</c> event, which the event system sends when the pointer is pressed
    /// and released over this object (UniTask <c>IAsyncOnPointerClickHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnPointerClickHandler
    {
        /// <summary>Waits for the next <c>OnPointerClick</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<PointerEventData> OnPointerClickAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnPointerClick</c> event, which the event system sends when the pointer is pressed
    /// and released over this object (UniTask <c>AsyncPointerClickTrigger</c> parity). The component itself is
    /// an <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncPointerClickTrigger : OnityAsyncTriggerBase<PointerEventData>, IPointerClickHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnPointerClickAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnPointerClickHandler GetOnPointerClickAsyncHandler()
        {
            return new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnPointerClickAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnPointerClickHandler GetOnPointerClickAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncPointerEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnPointerClick</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnPointerClickAsync()
        {
            return ((IOnityAsyncOnPointerClickHandler)new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, true)).OnPointerClickAsync();
        }

        /// <summary>Waits for the next <c>OnPointerClick</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnPointerClickAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnPointerClickHandler)new OnityAsyncPointerEventDataHandler(this, cancellationToken, true)).OnPointerClickAsync();
        }

        void IPointerClickHandler.OnPointerClick(PointerEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region PointerDown

    /// <summary>
    /// Waits for the next <c>OnPointerDown</c> event, which the event system sends when the pointer is pressed
    /// over this object (UniTask <c>IAsyncOnPointerDownHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnPointerDownHandler
    {
        /// <summary>Waits for the next <c>OnPointerDown</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<PointerEventData> OnPointerDownAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnPointerDown</c> event, which the event system sends when the pointer is pressed
    /// over this object (UniTask <c>AsyncPointerDownTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncPointerDownTrigger : OnityAsyncTriggerBase<PointerEventData>, IPointerDownHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnPointerDownAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnPointerDownHandler GetOnPointerDownAsyncHandler()
        {
            return new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnPointerDownAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnPointerDownHandler GetOnPointerDownAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncPointerEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnPointerDown</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnPointerDownAsync()
        {
            return ((IOnityAsyncOnPointerDownHandler)new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, true)).OnPointerDownAsync();
        }

        /// <summary>Waits for the next <c>OnPointerDown</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnPointerDownAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnPointerDownHandler)new OnityAsyncPointerEventDataHandler(this, cancellationToken, true)).OnPointerDownAsync();
        }

        void IPointerDownHandler.OnPointerDown(PointerEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region PointerEnter

    /// <summary>
    /// Waits for the next <c>OnPointerEnter</c> event, which the event system sends when the pointer enters
    /// this object (UniTask <c>IAsyncOnPointerEnterHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnPointerEnterHandler
    {
        /// <summary>Waits for the next <c>OnPointerEnter</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<PointerEventData> OnPointerEnterAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnPointerEnter</c> event, which the event system sends when the pointer enters this
    /// object (UniTask <c>AsyncPointerEnterTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncPointerEnterTrigger : OnityAsyncTriggerBase<PointerEventData>, IPointerEnterHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnPointerEnterAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnPointerEnterHandler GetOnPointerEnterAsyncHandler()
        {
            return new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnPointerEnterAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnPointerEnterHandler GetOnPointerEnterAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncPointerEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnPointerEnter</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnPointerEnterAsync()
        {
            return ((IOnityAsyncOnPointerEnterHandler)new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, true)).OnPointerEnterAsync();
        }

        /// <summary>Waits for the next <c>OnPointerEnter</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnPointerEnterAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnPointerEnterHandler)new OnityAsyncPointerEventDataHandler(this, cancellationToken, true)).OnPointerEnterAsync();
        }

        void IPointerEnterHandler.OnPointerEnter(PointerEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region PointerExit

    /// <summary>
    /// Waits for the next <c>OnPointerExit</c> event, which the event system sends when the pointer leaves this
    /// object (UniTask <c>IAsyncOnPointerExitHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnPointerExitHandler
    {
        /// <summary>Waits for the next <c>OnPointerExit</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<PointerEventData> OnPointerExitAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnPointerExit</c> event, which the event system sends when the pointer leaves this
    /// object (UniTask <c>AsyncPointerExitTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncPointerExitTrigger : OnityAsyncTriggerBase<PointerEventData>, IPointerExitHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnPointerExitAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnPointerExitHandler GetOnPointerExitAsyncHandler()
        {
            return new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnPointerExitAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnPointerExitHandler GetOnPointerExitAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncPointerEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnPointerExit</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnPointerExitAsync()
        {
            return ((IOnityAsyncOnPointerExitHandler)new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, true)).OnPointerExitAsync();
        }

        /// <summary>Waits for the next <c>OnPointerExit</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnPointerExitAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnPointerExitHandler)new OnityAsyncPointerEventDataHandler(this, cancellationToken, true)).OnPointerExitAsync();
        }

        void IPointerExitHandler.OnPointerExit(PointerEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region PointerUp

    /// <summary>
    /// Waits for the next <c>OnPointerUp</c> event, which the event system sends when the pointer is released
    /// over this object (UniTask <c>IAsyncOnPointerUpHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnPointerUpHandler
    {
        /// <summary>Waits for the next <c>OnPointerUp</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<PointerEventData> OnPointerUpAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnPointerUp</c> event, which the event system sends when the pointer is released over
    /// this object (UniTask <c>AsyncPointerUpTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncPointerUpTrigger : OnityAsyncTriggerBase<PointerEventData>, IPointerUpHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnPointerUpAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnPointerUpHandler GetOnPointerUpAsyncHandler()
        {
            return new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnPointerUpAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnPointerUpHandler GetOnPointerUpAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncPointerEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnPointerUp</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnPointerUpAsync()
        {
            return ((IOnityAsyncOnPointerUpHandler)new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, true)).OnPointerUpAsync();
        }

        /// <summary>Waits for the next <c>OnPointerUp</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnPointerUpAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnPointerUpHandler)new OnityAsyncPointerEventDataHandler(this, cancellationToken, true)).OnPointerUpAsync();
        }

        void IPointerUpHandler.OnPointerUp(PointerEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region Scroll

    /// <summary>
    /// Waits for the next <c>OnScroll</c> event, which the event system sends when the scroll wheel moves over
    /// this object (UniTask <c>IAsyncOnScrollHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnScrollHandler
    {
        /// <summary>Waits for the next <c>OnScroll</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<PointerEventData> OnScrollAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnScroll</c> event, which the event system sends when the scroll wheel moves over
    /// this object (UniTask <c>AsyncScrollTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncScrollTrigger : OnityAsyncTriggerBase<PointerEventData>, IScrollHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnScrollAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnScrollHandler GetOnScrollAsyncHandler()
        {
            return new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnScrollAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnScrollHandler GetOnScrollAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncPointerEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnScroll</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnScrollAsync()
        {
            return ((IOnityAsyncOnScrollHandler)new OnityAsyncPointerEventDataHandler(this, CancellationToken.None, true)).OnScrollAsync();
        }

        /// <summary>Waits for the next <c>OnScroll</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<PointerEventData> OnScrollAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnScrollHandler)new OnityAsyncPointerEventDataHandler(this, cancellationToken, true)).OnScrollAsync();
        }

        void IScrollHandler.OnScroll(PointerEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region Select

    /// <summary>
    /// Waits for the next <c>OnSelect</c> event, which the event system sends when this object becomes the
    /// selected object (UniTask <c>IAsyncOnSelectHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnSelectHandler
    {
        /// <summary>Waits for the next <c>OnSelect</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<BaseEventData> OnSelectAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnSelect</c> event, which the event system sends when this object becomes the
    /// selected object (UniTask <c>AsyncSelectTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncSelectTrigger : OnityAsyncTriggerBase<BaseEventData>, ISelectHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnSelectAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnSelectHandler GetOnSelectAsyncHandler()
        {
            return new OnityAsyncBaseEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnSelectAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnSelectHandler GetOnSelectAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncBaseEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnSelect</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<BaseEventData> OnSelectAsync()
        {
            return ((IOnityAsyncOnSelectHandler)new OnityAsyncBaseEventDataHandler(this, CancellationToken.None, true)).OnSelectAsync();
        }

        /// <summary>Waits for the next <c>OnSelect</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<BaseEventData> OnSelectAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnSelectHandler)new OnityAsyncBaseEventDataHandler(this, cancellationToken, true)).OnSelectAsync();
        }

        void ISelectHandler.OnSelect(BaseEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region Submit

    /// <summary>
    /// Waits for the next <c>OnSubmit</c> event, which the event system sends when the Submit input is raised
    /// while this object is selected (UniTask <c>IAsyncOnSubmitHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnSubmitHandler
    {
        /// <summary>Waits for the next <c>OnSubmit</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<BaseEventData> OnSubmitAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnSubmit</c> event, which the event system sends when the Submit input is raised
    /// while this object is selected (UniTask <c>AsyncSubmitTrigger</c> parity). The component itself is an
    /// <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncSubmitTrigger : OnityAsyncTriggerBase<BaseEventData>, ISubmitHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnSubmitAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnSubmitHandler GetOnSubmitAsyncHandler()
        {
            return new OnityAsyncBaseEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnSubmitAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnSubmitHandler GetOnSubmitAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncBaseEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnSubmit</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<BaseEventData> OnSubmitAsync()
        {
            return ((IOnityAsyncOnSubmitHandler)new OnityAsyncBaseEventDataHandler(this, CancellationToken.None, true)).OnSubmitAsync();
        }

        /// <summary>Waits for the next <c>OnSubmit</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<BaseEventData> OnSubmitAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnSubmitHandler)new OnityAsyncBaseEventDataHandler(this, cancellationToken, true)).OnSubmitAsync();
        }

        void ISubmitHandler.OnSubmit(BaseEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

#region UpdateSelected

    /// <summary>
    /// Waits for the next <c>OnUpdateSelected</c> event, which the event system sends on every update while
    /// this object is the selected object (UniTask <c>IAsyncOnUpdateSelectedHandler</c> parity).
    /// </summary>
    public interface IOnityAsyncOnUpdateSelectedHandler
    {
        /// <summary>Waits for the next <c>OnUpdateSelected</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<BaseEventData> OnUpdateSelectedAsync();
    }

    /// <summary>
    /// Trigger for the <c>OnUpdateSelected</c> event, which the event system sends on every update while this
    /// object is the selected object (UniTask <c>AsyncUpdateSelectedTrigger</c> parity). The component itself
    /// is an <see cref="IOnityAsyncEnumerable{T}"/> of the raised events. Main thread only.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsyncUpdateSelectedTrigger : OnityAsyncTriggerBase<BaseEventData>, IUpdateSelectedHandler
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>OnUpdateSelectedAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnUpdateSelectedHandler GetOnUpdateSelectedAsyncHandler()
        {
            return new OnityAsyncBaseEventDataHandler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>OnUpdateSelectedAsync()</c> waits for the next event.</returns>
        public IOnityAsyncOnUpdateSelectedHandler GetOnUpdateSelectedAsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncBaseEventDataHandler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>OnUpdateSelected</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<BaseEventData> OnUpdateSelectedAsync()
        {
            return ((IOnityAsyncOnUpdateSelectedHandler)new OnityAsyncBaseEventDataHandler(this, CancellationToken.None, true)).OnUpdateSelectedAsync();
        }

        /// <summary>Waits for the next <c>OnUpdateSelected</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<BaseEventData> OnUpdateSelectedAsync(CancellationToken cancellationToken)
        {
            return ((IOnityAsyncOnUpdateSelectedHandler)new OnityAsyncBaseEventDataHandler(this, cancellationToken, true)).OnUpdateSelectedAsync();
        }

        void IUpdateSelectedHandler.OnUpdateSelected(BaseEventData eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion

    // Adapts the shared trigger handler to the handler interfaces of the messages that carry PointerEventData.
    internal sealed class OnityAsyncPointerEventDataHandler :
        IOnityAsyncOnBeginDragHandler,
        IOnityAsyncOnDragHandler,
        IOnityAsyncOnDropHandler,
        IOnityAsyncOnEndDragHandler,
        IOnityAsyncOnInitializePotentialDragHandler,
        IOnityAsyncOnPointerClickHandler,
        IOnityAsyncOnPointerDownHandler,
        IOnityAsyncOnPointerEnterHandler,
        IOnityAsyncOnPointerExitHandler,
        IOnityAsyncOnPointerUpHandler,
        IOnityAsyncOnScrollHandler,
        IDisposable
    {
        private readonly OnityAsyncTriggerHandler<PointerEventData> m_handler;

        internal OnityAsyncPointerEventDataHandler(
            OnityAsyncTriggerBase<PointerEventData> trigger, CancellationToken cancellationToken, bool callOnce)
        {
            m_handler = new OnityAsyncTriggerHandler<PointerEventData>(trigger, cancellationToken, callOnce);
        }

        public void Dispose()
        {
            m_handler.Dispose();
        }

        OnityTask<PointerEventData> IOnityAsyncOnBeginDragHandler.OnBeginDragAsync()
        {
            return m_handler.WaitValueAsync<PointerEventData>();
        }

        OnityTask<PointerEventData> IOnityAsyncOnDragHandler.OnDragAsync()
        {
            return m_handler.WaitValueAsync<PointerEventData>();
        }

        OnityTask<PointerEventData> IOnityAsyncOnDropHandler.OnDropAsync()
        {
            return m_handler.WaitValueAsync<PointerEventData>();
        }

        OnityTask<PointerEventData> IOnityAsyncOnEndDragHandler.OnEndDragAsync()
        {
            return m_handler.WaitValueAsync<PointerEventData>();
        }

        OnityTask<PointerEventData> IOnityAsyncOnInitializePotentialDragHandler.OnInitializePotentialDragAsync()
        {
            return m_handler.WaitValueAsync<PointerEventData>();
        }

        OnityTask<PointerEventData> IOnityAsyncOnPointerClickHandler.OnPointerClickAsync()
        {
            return m_handler.WaitValueAsync<PointerEventData>();
        }

        OnityTask<PointerEventData> IOnityAsyncOnPointerDownHandler.OnPointerDownAsync()
        {
            return m_handler.WaitValueAsync<PointerEventData>();
        }

        OnityTask<PointerEventData> IOnityAsyncOnPointerEnterHandler.OnPointerEnterAsync()
        {
            return m_handler.WaitValueAsync<PointerEventData>();
        }

        OnityTask<PointerEventData> IOnityAsyncOnPointerExitHandler.OnPointerExitAsync()
        {
            return m_handler.WaitValueAsync<PointerEventData>();
        }

        OnityTask<PointerEventData> IOnityAsyncOnPointerUpHandler.OnPointerUpAsync()
        {
            return m_handler.WaitValueAsync<PointerEventData>();
        }

        OnityTask<PointerEventData> IOnityAsyncOnScrollHandler.OnScrollAsync()
        {
            return m_handler.WaitValueAsync<PointerEventData>();
        }
    }

    // Adapts the shared trigger handler to the handler interfaces of the messages that carry BaseEventData.
    internal sealed class OnityAsyncBaseEventDataHandler :
        IOnityAsyncOnCancelHandler,
        IOnityAsyncOnDeselectHandler,
        IOnityAsyncOnSelectHandler,
        IOnityAsyncOnSubmitHandler,
        IOnityAsyncOnUpdateSelectedHandler,
        IDisposable
    {
        private readonly OnityAsyncTriggerHandler<BaseEventData> m_handler;

        internal OnityAsyncBaseEventDataHandler(
            OnityAsyncTriggerBase<BaseEventData> trigger, CancellationToken cancellationToken, bool callOnce)
        {
            m_handler = new OnityAsyncTriggerHandler<BaseEventData>(trigger, cancellationToken, callOnce);
        }

        public void Dispose()
        {
            m_handler.Dispose();
        }

        OnityTask<BaseEventData> IOnityAsyncOnCancelHandler.OnCancelAsync()
        {
            return m_handler.WaitValueAsync<BaseEventData>();
        }

        OnityTask<BaseEventData> IOnityAsyncOnDeselectHandler.OnDeselectAsync()
        {
            return m_handler.WaitValueAsync<BaseEventData>();
        }

        OnityTask<BaseEventData> IOnityAsyncOnSelectHandler.OnSelectAsync()
        {
            return m_handler.WaitValueAsync<BaseEventData>();
        }

        OnityTask<BaseEventData> IOnityAsyncOnSubmitHandler.OnSubmitAsync()
        {
            return m_handler.WaitValueAsync<BaseEventData>();
        }

        OnityTask<BaseEventData> IOnityAsyncOnUpdateSelectedHandler.OnUpdateSelectedAsync()
        {
            return m_handler.WaitValueAsync<BaseEventData>();
        }
    }

    // Adapts the shared trigger handler to the handler interfaces of the messages that carry AxisEventData.
    internal sealed class OnityAsyncAxisEventDataHandler :
        IOnityAsyncOnMoveHandler,
        IDisposable
    {
        private readonly OnityAsyncTriggerHandler<AxisEventData> m_handler;

        internal OnityAsyncAxisEventDataHandler(
            OnityAsyncTriggerBase<AxisEventData> trigger, CancellationToken cancellationToken, bool callOnce)
        {
            m_handler = new OnityAsyncTriggerHandler<AxisEventData>(trigger, cancellationToken, callOnce);
        }

        public void Dispose()
        {
            m_handler.Dispose();
        }

        OnityTask<AxisEventData> IOnityAsyncOnMoveHandler.OnMoveAsync()
        {
            return m_handler.WaitValueAsync<AxisEventData>();
        }
    }

    /// <summary>
    /// Entry points that get or add the EventSystems triggers on a GameObject (UniTask
    /// <c>AsyncTriggerExtensions</c> parity). Each trigger type is added at most once per GameObject and
    /// reused. Every member requires Unity's main thread.
    /// </summary>
    public static class OnityAsyncEventSystemTriggerExtensions
    {
        /// <summary>Gets or adds the <see cref="OnityAsyncBeginDragTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncBeginDragTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncBeginDragTrigger GetAsyncBeginDragTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncBeginDragTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncBeginDragTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncBeginDragTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncBeginDragTrigger GetAsyncBeginDragTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncBeginDragTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncCancelTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncCancelTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncCancelTrigger GetAsyncCancelTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncCancelTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncCancelTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncCancelTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncCancelTrigger GetAsyncCancelTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncCancelTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncDeselectTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncDeselectTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncDeselectTrigger GetAsyncDeselectTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncDeselectTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncDeselectTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncDeselectTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncDeselectTrigger GetAsyncDeselectTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncDeselectTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncDragTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncDragTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncDragTrigger GetAsyncDragTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncDragTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncDragTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncDragTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncDragTrigger GetAsyncDragTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncDragTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncDropTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncDropTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncDropTrigger GetAsyncDropTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncDropTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncDropTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncDropTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncDropTrigger GetAsyncDropTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncDropTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncEndDragTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncEndDragTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncEndDragTrigger GetAsyncEndDragTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncEndDragTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncEndDragTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncEndDragTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncEndDragTrigger GetAsyncEndDragTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncEndDragTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncInitializePotentialDragTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncInitializePotentialDragTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncInitializePotentialDragTrigger GetAsyncInitializePotentialDragTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncInitializePotentialDragTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncInitializePotentialDragTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncInitializePotentialDragTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncInitializePotentialDragTrigger GetAsyncInitializePotentialDragTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncInitializePotentialDragTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncMoveTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncMoveTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncMoveTrigger GetAsyncMoveTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncMoveTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncMoveTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncMoveTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncMoveTrigger GetAsyncMoveTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncMoveTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncPointerClickTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncPointerClickTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncPointerClickTrigger GetAsyncPointerClickTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncPointerClickTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncPointerClickTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncPointerClickTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncPointerClickTrigger GetAsyncPointerClickTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncPointerClickTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncPointerDownTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncPointerDownTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncPointerDownTrigger GetAsyncPointerDownTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncPointerDownTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncPointerDownTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncPointerDownTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncPointerDownTrigger GetAsyncPointerDownTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncPointerDownTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncPointerEnterTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncPointerEnterTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncPointerEnterTrigger GetAsyncPointerEnterTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncPointerEnterTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncPointerEnterTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncPointerEnterTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncPointerEnterTrigger GetAsyncPointerEnterTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncPointerEnterTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncPointerExitTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncPointerExitTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncPointerExitTrigger GetAsyncPointerExitTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncPointerExitTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncPointerExitTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncPointerExitTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncPointerExitTrigger GetAsyncPointerExitTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncPointerExitTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncPointerUpTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncPointerUpTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncPointerUpTrigger GetAsyncPointerUpTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncPointerUpTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncPointerUpTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncPointerUpTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncPointerUpTrigger GetAsyncPointerUpTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncPointerUpTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncScrollTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncScrollTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncScrollTrigger GetAsyncScrollTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncScrollTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncScrollTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncScrollTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncScrollTrigger GetAsyncScrollTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncScrollTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncSelectTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncSelectTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncSelectTrigger GetAsyncSelectTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncSelectTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncSelectTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncSelectTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncSelectTrigger GetAsyncSelectTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncSelectTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncSubmitTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncSubmitTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncSubmitTrigger GetAsyncSubmitTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncSubmitTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncSubmitTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncSubmitTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncSubmitTrigger GetAsyncSubmitTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncSubmitTrigger();
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncUpdateSelectedTrigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsyncUpdateSelectedTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsyncUpdateSelectedTrigger GetAsyncUpdateSelectedTrigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsyncUpdateSelectedTrigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsyncUpdateSelectedTrigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsyncUpdateSelectedTrigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsyncUpdateSelectedTrigger GetAsyncUpdateSelectedTrigger(this Component component)
        {
            return GetGameObject(component).GetAsyncUpdateSelectedTrigger();
        }

        private static T GetOrAddComponent<T>(GameObject gameObject)
            where T : Component
        {
            if (ReferenceEquals(gameObject, null))
            {
                throw new ArgumentNullException(nameof(gameObject));
            }

            if (!gameObject.TryGetComponent(out T component))
            {
                component = gameObject.AddComponent<T>();
            }

            return component;
        }

        private static GameObject GetGameObject(Component component)
        {
            if (ReferenceEquals(component, null))
            {
                throw new ArgumentNullException(nameof(component));
            }

            return component.gameObject;
        }
    }
}
