// <auto-generated>
// Generated by tools/codegen/generate_onity_async_triggers.py. Do not edit by hand;
// change the generator and rerun it.
// </auto-generated>
using System;
using System.Threading;
using Onity.Core;
using UnityEngine;
using UnityEngine.UI;

namespace Onity.Unity.Async
{
    /// <summary>
    /// Awaitable waits, async sequences and reusable handlers for the events of uGUI components (UniTask
    /// <c>UnityAsyncExtensions</c> parity). Overloads without a token end with the destroy of the
    /// component. Every member requires Unity's main thread.
    /// </summary>
    public static class OnityUguiAsyncExtensions
    {
        /// <summary>
        /// Creates a reusable handler for the click of the Button that stays registered
        /// until disposed or until the Button is destroyed. Main thread only.
        /// </summary>
        /// <param name="button">Button to listen to.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="button"/> is null.</exception>
        public static IOnityAsyncClickEventHandler GetAsyncClickEventHandler(this Button button)
        {
            ThrowIfNull(button, nameof(button));
            return new OnityAsyncUnityEventHandler(button.onClick, button.GetCancellationTokenOnDestroy(), false);
        }

        /// <summary>
        /// Creates a reusable handler for the click of the Button that stays registered
        /// until disposed or until the token is canceled. Main thread only.
        /// </summary>
        /// <param name="button">Button to listen to.</param>
        /// <param name="cancellationToken">Stops listening when canceled.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="button"/> is null.</exception>
        public static IOnityAsyncClickEventHandler GetAsyncClickEventHandler(
            this Button button, CancellationToken cancellationToken)
        {
            ThrowIfNull(button, nameof(button));
            return new OnityAsyncUnityEventHandler(button.onClick, cancellationToken, false);
        }

        /// <summary>
        /// Waits for the next click of the Button; the wait is canceled when the
        /// Button is destroyed. Main thread only.
        /// </summary>
        /// <param name="button">Button to listen to.</param>
        /// <returns>A single-consumption task; canceled on destroy.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="button"/> is null.</exception>
        public static OnityTask OnClickAsync(this Button button)
        {
            ThrowIfNull(button, nameof(button));
            return new OnityAsyncUnityEventHandler(button.onClick, button.GetCancellationTokenOnDestroy(), true).OnInvokeAsync();
        }

        /// <summary>Waits for the next click of the Button. Main thread only.</summary>
        /// <param name="button">Button to listen to.</param>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task; canceled by the token.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="button"/> is null.</exception>
        public static OnityTask OnClickAsync(this Button button, CancellationToken cancellationToken)
        {
            ThrowIfNull(button, nameof(button));
            return new OnityAsyncUnityEventHandler(button.onClick, cancellationToken, true).OnInvokeAsync();
        }

        /// <summary>
        /// Exposes the clicks of the Button as an async sequence that ends when the
        /// Button is destroyed. Main thread only.
        /// </summary>
        /// <param name="button">Button to listen to.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="button"/> is null.</exception>
        public static IOnityAsyncEnumerable<Unit> OnClickAsAsyncEnumerable(this Button button)
        {
            ThrowIfNull(button, nameof(button));
            return new OnityUnityEventAsyncEnumerable(button.onClick, button.GetCancellationTokenOnDestroy());
        }

        /// <summary>
        /// Exposes the clicks of the Button as an async sequence that ends when the token is
        /// canceled. Main thread only.
        /// </summary>
        /// <param name="button">Button to listen to.</param>
        /// <param name="cancellationToken">Ends every enumeration when canceled.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="button"/> is null.</exception>
        public static IOnityAsyncEnumerable<Unit> OnClickAsAsyncEnumerable(
            this Button button, CancellationToken cancellationToken)
        {
            ThrowIfNull(button, nameof(button));
            return new OnityUnityEventAsyncEnumerable(button.onClick, cancellationToken);
        }

        /// <summary>
        /// Creates a reusable handler for the value change of the Toggle that stays registered
        /// until disposed or until the Toggle is destroyed. Main thread only.
        /// </summary>
        /// <param name="toggle">Toggle to listen to.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="toggle"/> is null.</exception>
        public static IOnityAsyncValueChangedEventHandler<bool> GetAsyncValueChangedEventHandler(this Toggle toggle)
        {
            ThrowIfNull(toggle, nameof(toggle));
            return new OnityAsyncUnityEventHandler<bool>(toggle.onValueChanged, toggle.GetCancellationTokenOnDestroy(), false);
        }

        /// <summary>
        /// Creates a reusable handler for the value change of the Toggle that stays registered
        /// until disposed or until the token is canceled. Main thread only.
        /// </summary>
        /// <param name="toggle">Toggle to listen to.</param>
        /// <param name="cancellationToken">Stops listening when canceled.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="toggle"/> is null.</exception>
        public static IOnityAsyncValueChangedEventHandler<bool> GetAsyncValueChangedEventHandler(
            this Toggle toggle, CancellationToken cancellationToken)
        {
            ThrowIfNull(toggle, nameof(toggle));
            return new OnityAsyncUnityEventHandler<bool>(toggle.onValueChanged, cancellationToken, false);
        }

        /// <summary>
        /// Waits for the next value change of the Toggle; the wait is canceled when the
        /// Toggle is destroyed. Main thread only.
        /// </summary>
        /// <param name="toggle">Toggle to listen to.</param>
        /// <returns>A single-consumption task completed with the new value; canceled on destroy.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="toggle"/> is null.</exception>
        public static OnityTask<bool> OnValueChangedAsync(this Toggle toggle)
        {
            ThrowIfNull(toggle, nameof(toggle));
            return new OnityAsyncUnityEventHandler<bool>(toggle.onValueChanged, toggle.GetCancellationTokenOnDestroy(), true).OnInvokeAsync();
        }

        /// <summary>Waits for the next value change of the Toggle. Main thread only.</summary>
        /// <param name="toggle">Toggle to listen to.</param>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the new value; canceled by the token.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="toggle"/> is null.</exception>
        public static OnityTask<bool> OnValueChangedAsync(this Toggle toggle, CancellationToken cancellationToken)
        {
            ThrowIfNull(toggle, nameof(toggle));
            return new OnityAsyncUnityEventHandler<bool>(toggle.onValueChanged, cancellationToken, true).OnInvokeAsync();
        }

        /// <summary>
        /// Exposes the value changes of the Toggle as an async sequence that ends when the
        /// Toggle is destroyed. Main thread only.
        /// </summary>
        /// <param name="toggle">Toggle to listen to.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="toggle"/> is null.</exception>
        public static IOnityAsyncEnumerable<bool> OnValueChangedAsAsyncEnumerable(this Toggle toggle)
        {
            ThrowIfNull(toggle, nameof(toggle));
            return new OnityUnityEventAsyncEnumerable<bool>(toggle.onValueChanged, toggle.GetCancellationTokenOnDestroy());
        }

        /// <summary>
        /// Exposes the value changes of the Toggle as an async sequence that ends when the token is
        /// canceled. Main thread only.
        /// </summary>
        /// <param name="toggle">Toggle to listen to.</param>
        /// <param name="cancellationToken">Ends every enumeration when canceled.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="toggle"/> is null.</exception>
        public static IOnityAsyncEnumerable<bool> OnValueChangedAsAsyncEnumerable(
            this Toggle toggle, CancellationToken cancellationToken)
        {
            ThrowIfNull(toggle, nameof(toggle));
            return new OnityUnityEventAsyncEnumerable<bool>(toggle.onValueChanged, cancellationToken);
        }

        /// <summary>
        /// Creates a reusable handler for the value change of the Scrollbar that stays registered
        /// until disposed or until the Scrollbar is destroyed. Main thread only.
        /// </summary>
        /// <param name="scrollbar">Scrollbar to listen to.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="scrollbar"/> is null.</exception>
        public static IOnityAsyncValueChangedEventHandler<float> GetAsyncValueChangedEventHandler(this Scrollbar scrollbar)
        {
            ThrowIfNull(scrollbar, nameof(scrollbar));
            return new OnityAsyncUnityEventHandler<float>(scrollbar.onValueChanged, scrollbar.GetCancellationTokenOnDestroy(), false);
        }

        /// <summary>
        /// Creates a reusable handler for the value change of the Scrollbar that stays registered
        /// until disposed or until the token is canceled. Main thread only.
        /// </summary>
        /// <param name="scrollbar">Scrollbar to listen to.</param>
        /// <param name="cancellationToken">Stops listening when canceled.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="scrollbar"/> is null.</exception>
        public static IOnityAsyncValueChangedEventHandler<float> GetAsyncValueChangedEventHandler(
            this Scrollbar scrollbar, CancellationToken cancellationToken)
        {
            ThrowIfNull(scrollbar, nameof(scrollbar));
            return new OnityAsyncUnityEventHandler<float>(scrollbar.onValueChanged, cancellationToken, false);
        }

        /// <summary>
        /// Waits for the next value change of the Scrollbar; the wait is canceled when the
        /// Scrollbar is destroyed. Main thread only.
        /// </summary>
        /// <param name="scrollbar">Scrollbar to listen to.</param>
        /// <returns>A single-consumption task completed with the new value; canceled on destroy.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="scrollbar"/> is null.</exception>
        public static OnityTask<float> OnValueChangedAsync(this Scrollbar scrollbar)
        {
            ThrowIfNull(scrollbar, nameof(scrollbar));
            return new OnityAsyncUnityEventHandler<float>(scrollbar.onValueChanged, scrollbar.GetCancellationTokenOnDestroy(), true).OnInvokeAsync();
        }

        /// <summary>Waits for the next value change of the Scrollbar. Main thread only.</summary>
        /// <param name="scrollbar">Scrollbar to listen to.</param>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the new value; canceled by the token.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="scrollbar"/> is null.</exception>
        public static OnityTask<float> OnValueChangedAsync(this Scrollbar scrollbar, CancellationToken cancellationToken)
        {
            ThrowIfNull(scrollbar, nameof(scrollbar));
            return new OnityAsyncUnityEventHandler<float>(scrollbar.onValueChanged, cancellationToken, true).OnInvokeAsync();
        }

        /// <summary>
        /// Exposes the value changes of the Scrollbar as an async sequence that ends when the
        /// Scrollbar is destroyed. Main thread only.
        /// </summary>
        /// <param name="scrollbar">Scrollbar to listen to.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="scrollbar"/> is null.</exception>
        public static IOnityAsyncEnumerable<float> OnValueChangedAsAsyncEnumerable(this Scrollbar scrollbar)
        {
            ThrowIfNull(scrollbar, nameof(scrollbar));
            return new OnityUnityEventAsyncEnumerable<float>(scrollbar.onValueChanged, scrollbar.GetCancellationTokenOnDestroy());
        }

        /// <summary>
        /// Exposes the value changes of the Scrollbar as an async sequence that ends when the token is
        /// canceled. Main thread only.
        /// </summary>
        /// <param name="scrollbar">Scrollbar to listen to.</param>
        /// <param name="cancellationToken">Ends every enumeration when canceled.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="scrollbar"/> is null.</exception>
        public static IOnityAsyncEnumerable<float> OnValueChangedAsAsyncEnumerable(
            this Scrollbar scrollbar, CancellationToken cancellationToken)
        {
            ThrowIfNull(scrollbar, nameof(scrollbar));
            return new OnityUnityEventAsyncEnumerable<float>(scrollbar.onValueChanged, cancellationToken);
        }

        /// <summary>
        /// Creates a reusable handler for the scroll position change of the ScrollRect that stays registered
        /// until disposed or until the ScrollRect is destroyed. Main thread only.
        /// </summary>
        /// <param name="scrollRect">ScrollRect to listen to.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="scrollRect"/> is null.</exception>
        public static IOnityAsyncValueChangedEventHandler<Vector2> GetAsyncValueChangedEventHandler(this ScrollRect scrollRect)
        {
            ThrowIfNull(scrollRect, nameof(scrollRect));
            return new OnityAsyncUnityEventHandler<Vector2>(scrollRect.onValueChanged, scrollRect.GetCancellationTokenOnDestroy(), false);
        }

        /// <summary>
        /// Creates a reusable handler for the scroll position change of the ScrollRect that stays registered
        /// until disposed or until the token is canceled. Main thread only.
        /// </summary>
        /// <param name="scrollRect">ScrollRect to listen to.</param>
        /// <param name="cancellationToken">Stops listening when canceled.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="scrollRect"/> is null.</exception>
        public static IOnityAsyncValueChangedEventHandler<Vector2> GetAsyncValueChangedEventHandler(
            this ScrollRect scrollRect, CancellationToken cancellationToken)
        {
            ThrowIfNull(scrollRect, nameof(scrollRect));
            return new OnityAsyncUnityEventHandler<Vector2>(scrollRect.onValueChanged, cancellationToken, false);
        }

        /// <summary>
        /// Waits for the next scroll position change of the ScrollRect; the wait is canceled when the
        /// ScrollRect is destroyed. Main thread only.
        /// </summary>
        /// <param name="scrollRect">ScrollRect to listen to.</param>
        /// <returns>A single-consumption task completed with the new value; canceled on destroy.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="scrollRect"/> is null.</exception>
        public static OnityTask<Vector2> OnValueChangedAsync(this ScrollRect scrollRect)
        {
            ThrowIfNull(scrollRect, nameof(scrollRect));
            return new OnityAsyncUnityEventHandler<Vector2>(scrollRect.onValueChanged, scrollRect.GetCancellationTokenOnDestroy(), true).OnInvokeAsync();
        }

        /// <summary>Waits for the next scroll position change of the ScrollRect. Main thread only.</summary>
        /// <param name="scrollRect">ScrollRect to listen to.</param>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the new value; canceled by the token.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="scrollRect"/> is null.</exception>
        public static OnityTask<Vector2> OnValueChangedAsync(this ScrollRect scrollRect, CancellationToken cancellationToken)
        {
            ThrowIfNull(scrollRect, nameof(scrollRect));
            return new OnityAsyncUnityEventHandler<Vector2>(scrollRect.onValueChanged, cancellationToken, true).OnInvokeAsync();
        }

        /// <summary>
        /// Exposes the scroll position changes of the ScrollRect as an async sequence that ends when the
        /// ScrollRect is destroyed. Main thread only.
        /// </summary>
        /// <param name="scrollRect">ScrollRect to listen to.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="scrollRect"/> is null.</exception>
        public static IOnityAsyncEnumerable<Vector2> OnValueChangedAsAsyncEnumerable(this ScrollRect scrollRect)
        {
            ThrowIfNull(scrollRect, nameof(scrollRect));
            return new OnityUnityEventAsyncEnumerable<Vector2>(scrollRect.onValueChanged, scrollRect.GetCancellationTokenOnDestroy());
        }

        /// <summary>
        /// Exposes the scroll position changes of the ScrollRect as an async sequence that ends when the token is
        /// canceled. Main thread only.
        /// </summary>
        /// <param name="scrollRect">ScrollRect to listen to.</param>
        /// <param name="cancellationToken">Ends every enumeration when canceled.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="scrollRect"/> is null.</exception>
        public static IOnityAsyncEnumerable<Vector2> OnValueChangedAsAsyncEnumerable(
            this ScrollRect scrollRect, CancellationToken cancellationToken)
        {
            ThrowIfNull(scrollRect, nameof(scrollRect));
            return new OnityUnityEventAsyncEnumerable<Vector2>(scrollRect.onValueChanged, cancellationToken);
        }

        /// <summary>
        /// Creates a reusable handler for the value change of the Slider that stays registered
        /// until disposed or until the Slider is destroyed. Main thread only.
        /// </summary>
        /// <param name="slider">Slider to listen to.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="slider"/> is null.</exception>
        public static IOnityAsyncValueChangedEventHandler<float> GetAsyncValueChangedEventHandler(this Slider slider)
        {
            ThrowIfNull(slider, nameof(slider));
            return new OnityAsyncUnityEventHandler<float>(slider.onValueChanged, slider.GetCancellationTokenOnDestroy(), false);
        }

        /// <summary>
        /// Creates a reusable handler for the value change of the Slider that stays registered
        /// until disposed or until the token is canceled. Main thread only.
        /// </summary>
        /// <param name="slider">Slider to listen to.</param>
        /// <param name="cancellationToken">Stops listening when canceled.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="slider"/> is null.</exception>
        public static IOnityAsyncValueChangedEventHandler<float> GetAsyncValueChangedEventHandler(
            this Slider slider, CancellationToken cancellationToken)
        {
            ThrowIfNull(slider, nameof(slider));
            return new OnityAsyncUnityEventHandler<float>(slider.onValueChanged, cancellationToken, false);
        }

        /// <summary>
        /// Waits for the next value change of the Slider; the wait is canceled when the
        /// Slider is destroyed. Main thread only.
        /// </summary>
        /// <param name="slider">Slider to listen to.</param>
        /// <returns>A single-consumption task completed with the new value; canceled on destroy.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="slider"/> is null.</exception>
        public static OnityTask<float> OnValueChangedAsync(this Slider slider)
        {
            ThrowIfNull(slider, nameof(slider));
            return new OnityAsyncUnityEventHandler<float>(slider.onValueChanged, slider.GetCancellationTokenOnDestroy(), true).OnInvokeAsync();
        }

        /// <summary>Waits for the next value change of the Slider. Main thread only.</summary>
        /// <param name="slider">Slider to listen to.</param>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the new value; canceled by the token.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="slider"/> is null.</exception>
        public static OnityTask<float> OnValueChangedAsync(this Slider slider, CancellationToken cancellationToken)
        {
            ThrowIfNull(slider, nameof(slider));
            return new OnityAsyncUnityEventHandler<float>(slider.onValueChanged, cancellationToken, true).OnInvokeAsync();
        }

        /// <summary>
        /// Exposes the value changes of the Slider as an async sequence that ends when the
        /// Slider is destroyed. Main thread only.
        /// </summary>
        /// <param name="slider">Slider to listen to.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="slider"/> is null.</exception>
        public static IOnityAsyncEnumerable<float> OnValueChangedAsAsyncEnumerable(this Slider slider)
        {
            ThrowIfNull(slider, nameof(slider));
            return new OnityUnityEventAsyncEnumerable<float>(slider.onValueChanged, slider.GetCancellationTokenOnDestroy());
        }

        /// <summary>
        /// Exposes the value changes of the Slider as an async sequence that ends when the token is
        /// canceled. Main thread only.
        /// </summary>
        /// <param name="slider">Slider to listen to.</param>
        /// <param name="cancellationToken">Ends every enumeration when canceled.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="slider"/> is null.</exception>
        public static IOnityAsyncEnumerable<float> OnValueChangedAsAsyncEnumerable(
            this Slider slider, CancellationToken cancellationToken)
        {
            ThrowIfNull(slider, nameof(slider));
            return new OnityUnityEventAsyncEnumerable<float>(slider.onValueChanged, cancellationToken);
        }

        /// <summary>
        /// Creates a reusable handler for the end-edit event of the InputField that stays registered
        /// until disposed or until the InputField is destroyed. Main thread only.
        /// </summary>
        /// <param name="inputField">InputField to listen to.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="inputField"/> is null.</exception>
        public static IOnityAsyncEndEditEventHandler<string> GetAsyncEndEditEventHandler(this InputField inputField)
        {
            ThrowIfNull(inputField, nameof(inputField));
            return new OnityAsyncUnityEventHandler<string>(inputField.onEndEdit, inputField.GetCancellationTokenOnDestroy(), false);
        }

        /// <summary>
        /// Creates a reusable handler for the end-edit event of the InputField that stays registered
        /// until disposed or until the token is canceled. Main thread only.
        /// </summary>
        /// <param name="inputField">InputField to listen to.</param>
        /// <param name="cancellationToken">Stops listening when canceled.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="inputField"/> is null.</exception>
        public static IOnityAsyncEndEditEventHandler<string> GetAsyncEndEditEventHandler(
            this InputField inputField, CancellationToken cancellationToken)
        {
            ThrowIfNull(inputField, nameof(inputField));
            return new OnityAsyncUnityEventHandler<string>(inputField.onEndEdit, cancellationToken, false);
        }

        /// <summary>
        /// Waits for the next end-edit event of the InputField; the wait is canceled when the
        /// InputField is destroyed. Main thread only.
        /// </summary>
        /// <param name="inputField">InputField to listen to.</param>
        /// <returns>A single-consumption task completed with the new value; canceled on destroy.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="inputField"/> is null.</exception>
        public static OnityTask<string> OnEndEditAsync(this InputField inputField)
        {
            ThrowIfNull(inputField, nameof(inputField));
            return new OnityAsyncUnityEventHandler<string>(inputField.onEndEdit, inputField.GetCancellationTokenOnDestroy(), true).OnInvokeAsync();
        }

        /// <summary>Waits for the next end-edit event of the InputField. Main thread only.</summary>
        /// <param name="inputField">InputField to listen to.</param>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the new value; canceled by the token.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="inputField"/> is null.</exception>
        public static OnityTask<string> OnEndEditAsync(this InputField inputField, CancellationToken cancellationToken)
        {
            ThrowIfNull(inputField, nameof(inputField));
            return new OnityAsyncUnityEventHandler<string>(inputField.onEndEdit, cancellationToken, true).OnInvokeAsync();
        }

        /// <summary>
        /// Exposes the end-edit events of the InputField as an async sequence that ends when the
        /// InputField is destroyed. Main thread only.
        /// </summary>
        /// <param name="inputField">InputField to listen to.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="inputField"/> is null.</exception>
        public static IOnityAsyncEnumerable<string> OnEndEditAsAsyncEnumerable(this InputField inputField)
        {
            ThrowIfNull(inputField, nameof(inputField));
            return new OnityUnityEventAsyncEnumerable<string>(inputField.onEndEdit, inputField.GetCancellationTokenOnDestroy());
        }

        /// <summary>
        /// Exposes the end-edit events of the InputField as an async sequence that ends when the token is
        /// canceled. Main thread only.
        /// </summary>
        /// <param name="inputField">InputField to listen to.</param>
        /// <param name="cancellationToken">Ends every enumeration when canceled.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="inputField"/> is null.</exception>
        public static IOnityAsyncEnumerable<string> OnEndEditAsAsyncEnumerable(
            this InputField inputField, CancellationToken cancellationToken)
        {
            ThrowIfNull(inputField, nameof(inputField));
            return new OnityUnityEventAsyncEnumerable<string>(inputField.onEndEdit, cancellationToken);
        }

        /// <summary>
        /// Creates a reusable handler for the text change of the InputField that stays registered
        /// until disposed or until the InputField is destroyed. Main thread only.
        /// </summary>
        /// <param name="inputField">InputField to listen to.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="inputField"/> is null.</exception>
        public static IOnityAsyncValueChangedEventHandler<string> GetAsyncValueChangedEventHandler(this InputField inputField)
        {
            ThrowIfNull(inputField, nameof(inputField));
            return new OnityAsyncUnityEventHandler<string>(inputField.onValueChanged, inputField.GetCancellationTokenOnDestroy(), false);
        }

        /// <summary>
        /// Creates a reusable handler for the text change of the InputField that stays registered
        /// until disposed or until the token is canceled. Main thread only.
        /// </summary>
        /// <param name="inputField">InputField to listen to.</param>
        /// <param name="cancellationToken">Stops listening when canceled.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="inputField"/> is null.</exception>
        public static IOnityAsyncValueChangedEventHandler<string> GetAsyncValueChangedEventHandler(
            this InputField inputField, CancellationToken cancellationToken)
        {
            ThrowIfNull(inputField, nameof(inputField));
            return new OnityAsyncUnityEventHandler<string>(inputField.onValueChanged, cancellationToken, false);
        }

        /// <summary>
        /// Waits for the next text change of the InputField; the wait is canceled when the
        /// InputField is destroyed. Main thread only.
        /// </summary>
        /// <param name="inputField">InputField to listen to.</param>
        /// <returns>A single-consumption task completed with the new value; canceled on destroy.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="inputField"/> is null.</exception>
        public static OnityTask<string> OnValueChangedAsync(this InputField inputField)
        {
            ThrowIfNull(inputField, nameof(inputField));
            return new OnityAsyncUnityEventHandler<string>(inputField.onValueChanged, inputField.GetCancellationTokenOnDestroy(), true).OnInvokeAsync();
        }

        /// <summary>Waits for the next text change of the InputField. Main thread only.</summary>
        /// <param name="inputField">InputField to listen to.</param>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the new value; canceled by the token.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="inputField"/> is null.</exception>
        public static OnityTask<string> OnValueChangedAsync(this InputField inputField, CancellationToken cancellationToken)
        {
            ThrowIfNull(inputField, nameof(inputField));
            return new OnityAsyncUnityEventHandler<string>(inputField.onValueChanged, cancellationToken, true).OnInvokeAsync();
        }

        /// <summary>
        /// Exposes the text changes of the InputField as an async sequence that ends when the
        /// InputField is destroyed. Main thread only.
        /// </summary>
        /// <param name="inputField">InputField to listen to.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="inputField"/> is null.</exception>
        public static IOnityAsyncEnumerable<string> OnValueChangedAsAsyncEnumerable(this InputField inputField)
        {
            ThrowIfNull(inputField, nameof(inputField));
            return new OnityUnityEventAsyncEnumerable<string>(inputField.onValueChanged, inputField.GetCancellationTokenOnDestroy());
        }

        /// <summary>
        /// Exposes the text changes of the InputField as an async sequence that ends when the token is
        /// canceled. Main thread only.
        /// </summary>
        /// <param name="inputField">InputField to listen to.</param>
        /// <param name="cancellationToken">Ends every enumeration when canceled.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="inputField"/> is null.</exception>
        public static IOnityAsyncEnumerable<string> OnValueChangedAsAsyncEnumerable(
            this InputField inputField, CancellationToken cancellationToken)
        {
            ThrowIfNull(inputField, nameof(inputField));
            return new OnityUnityEventAsyncEnumerable<string>(inputField.onValueChanged, cancellationToken);
        }

        /// <summary>
        /// Creates a reusable handler for the selection change of the Dropdown that stays registered
        /// until disposed or until the Dropdown is destroyed. Main thread only.
        /// </summary>
        /// <param name="dropdown">Dropdown to listen to.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="dropdown"/> is null.</exception>
        public static IOnityAsyncValueChangedEventHandler<int> GetAsyncValueChangedEventHandler(this Dropdown dropdown)
        {
            ThrowIfNull(dropdown, nameof(dropdown));
            return new OnityAsyncUnityEventHandler<int>(dropdown.onValueChanged, dropdown.GetCancellationTokenOnDestroy(), false);
        }

        /// <summary>
        /// Creates a reusable handler for the selection change of the Dropdown that stays registered
        /// until disposed or until the token is canceled. Main thread only.
        /// </summary>
        /// <param name="dropdown">Dropdown to listen to.</param>
        /// <param name="cancellationToken">Stops listening when canceled.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="dropdown"/> is null.</exception>
        public static IOnityAsyncValueChangedEventHandler<int> GetAsyncValueChangedEventHandler(
            this Dropdown dropdown, CancellationToken cancellationToken)
        {
            ThrowIfNull(dropdown, nameof(dropdown));
            return new OnityAsyncUnityEventHandler<int>(dropdown.onValueChanged, cancellationToken, false);
        }

        /// <summary>
        /// Waits for the next selection change of the Dropdown; the wait is canceled when the
        /// Dropdown is destroyed. Main thread only.
        /// </summary>
        /// <param name="dropdown">Dropdown to listen to.</param>
        /// <returns>A single-consumption task completed with the new value; canceled on destroy.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="dropdown"/> is null.</exception>
        public static OnityTask<int> OnValueChangedAsync(this Dropdown dropdown)
        {
            ThrowIfNull(dropdown, nameof(dropdown));
            return new OnityAsyncUnityEventHandler<int>(dropdown.onValueChanged, dropdown.GetCancellationTokenOnDestroy(), true).OnInvokeAsync();
        }

        /// <summary>Waits for the next selection change of the Dropdown. Main thread only.</summary>
        /// <param name="dropdown">Dropdown to listen to.</param>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the new value; canceled by the token.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="dropdown"/> is null.</exception>
        public static OnityTask<int> OnValueChangedAsync(this Dropdown dropdown, CancellationToken cancellationToken)
        {
            ThrowIfNull(dropdown, nameof(dropdown));
            return new OnityAsyncUnityEventHandler<int>(dropdown.onValueChanged, cancellationToken, true).OnInvokeAsync();
        }

        /// <summary>
        /// Exposes the selection changes of the Dropdown as an async sequence that ends when the
        /// Dropdown is destroyed. Main thread only.
        /// </summary>
        /// <param name="dropdown">Dropdown to listen to.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="dropdown"/> is null.</exception>
        public static IOnityAsyncEnumerable<int> OnValueChangedAsAsyncEnumerable(this Dropdown dropdown)
        {
            ThrowIfNull(dropdown, nameof(dropdown));
            return new OnityUnityEventAsyncEnumerable<int>(dropdown.onValueChanged, dropdown.GetCancellationTokenOnDestroy());
        }

        /// <summary>
        /// Exposes the selection changes of the Dropdown as an async sequence that ends when the token is
        /// canceled. Main thread only.
        /// </summary>
        /// <param name="dropdown">Dropdown to listen to.</param>
        /// <param name="cancellationToken">Ends every enumeration when canceled.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="dropdown"/> is null.</exception>
        public static IOnityAsyncEnumerable<int> OnValueChangedAsAsyncEnumerable(
            this Dropdown dropdown, CancellationToken cancellationToken)
        {
            ThrowIfNull(dropdown, nameof(dropdown));
            return new OnityUnityEventAsyncEnumerable<int>(dropdown.onValueChanged, cancellationToken);
        }

        private static void ThrowIfNull(object component, string name)
        {
            if (ReferenceEquals(component, null))
            {
                throw new ArgumentNullException(name);
            }
        }
    }
}
