// <auto-generated>
// Generated by tools/codegen/generate_onity_async_triggers.py. Do not edit by hand;
// change the generator and rerun it.
// </auto-generated>
using NUnit.Framework;
using Onity.Unity.Async.Triggers;
using UnityEngine.EventSystems;

namespace Onity.Tests.UGUI.PlayMode
{
    public sealed partial class OnityAsyncEventSystemTriggerPlayModeTests
    {
        [Test]
        public void BeginDrag_RaisesEveryWaitShape()
        {
            PointerEventData eventData = new PointerEventData(null);

            CheckEventMessage<OnityAsyncBeginDragTrigger, PointerEventData>(
                eventData,
                trigger => ((IBeginDragHandler)trigger).OnBeginDrag(eventData),
                gameObject => gameObject.GetAsyncBeginDragTrigger(),
                component => component.GetAsyncBeginDragTrigger(),
                trigger => trigger.OnBeginDragAsync(),
                (trigger, token) => trigger.OnBeginDragAsync(token),
                trigger => trigger.GetOnBeginDragAsyncHandler(),
                (trigger, token) => trigger.GetOnBeginDragAsyncHandler(token),
                handler => ((IOnityAsyncOnBeginDragHandler)handler).OnBeginDragAsync());
        }

        [Test]
        public void Cancel_RaisesEveryWaitShape()
        {
            BaseEventData eventData = new BaseEventData(null);

            CheckEventMessage<OnityAsyncCancelTrigger, BaseEventData>(
                eventData,
                trigger => ((ICancelHandler)trigger).OnCancel(eventData),
                gameObject => gameObject.GetAsyncCancelTrigger(),
                component => component.GetAsyncCancelTrigger(),
                trigger => trigger.OnCancelAsync(),
                (trigger, token) => trigger.OnCancelAsync(token),
                trigger => trigger.GetOnCancelAsyncHandler(),
                (trigger, token) => trigger.GetOnCancelAsyncHandler(token),
                handler => ((IOnityAsyncOnCancelHandler)handler).OnCancelAsync());
        }

        [Test]
        public void Deselect_RaisesEveryWaitShape()
        {
            BaseEventData eventData = new BaseEventData(null);

            CheckEventMessage<OnityAsyncDeselectTrigger, BaseEventData>(
                eventData,
                trigger => ((IDeselectHandler)trigger).OnDeselect(eventData),
                gameObject => gameObject.GetAsyncDeselectTrigger(),
                component => component.GetAsyncDeselectTrigger(),
                trigger => trigger.OnDeselectAsync(),
                (trigger, token) => trigger.OnDeselectAsync(token),
                trigger => trigger.GetOnDeselectAsyncHandler(),
                (trigger, token) => trigger.GetOnDeselectAsyncHandler(token),
                handler => ((IOnityAsyncOnDeselectHandler)handler).OnDeselectAsync());
        }

        [Test]
        public void Drag_RaisesEveryWaitShape()
        {
            PointerEventData eventData = new PointerEventData(null);

            CheckEventMessage<OnityAsyncDragTrigger, PointerEventData>(
                eventData,
                trigger => ((IDragHandler)trigger).OnDrag(eventData),
                gameObject => gameObject.GetAsyncDragTrigger(),
                component => component.GetAsyncDragTrigger(),
                trigger => trigger.OnDragAsync(),
                (trigger, token) => trigger.OnDragAsync(token),
                trigger => trigger.GetOnDragAsyncHandler(),
                (trigger, token) => trigger.GetOnDragAsyncHandler(token),
                handler => ((IOnityAsyncOnDragHandler)handler).OnDragAsync());
        }

        [Test]
        public void Drop_RaisesEveryWaitShape()
        {
            PointerEventData eventData = new PointerEventData(null);

            CheckEventMessage<OnityAsyncDropTrigger, PointerEventData>(
                eventData,
                trigger => ((IDropHandler)trigger).OnDrop(eventData),
                gameObject => gameObject.GetAsyncDropTrigger(),
                component => component.GetAsyncDropTrigger(),
                trigger => trigger.OnDropAsync(),
                (trigger, token) => trigger.OnDropAsync(token),
                trigger => trigger.GetOnDropAsyncHandler(),
                (trigger, token) => trigger.GetOnDropAsyncHandler(token),
                handler => ((IOnityAsyncOnDropHandler)handler).OnDropAsync());
        }

        [Test]
        public void EndDrag_RaisesEveryWaitShape()
        {
            PointerEventData eventData = new PointerEventData(null);

            CheckEventMessage<OnityAsyncEndDragTrigger, PointerEventData>(
                eventData,
                trigger => ((IEndDragHandler)trigger).OnEndDrag(eventData),
                gameObject => gameObject.GetAsyncEndDragTrigger(),
                component => component.GetAsyncEndDragTrigger(),
                trigger => trigger.OnEndDragAsync(),
                (trigger, token) => trigger.OnEndDragAsync(token),
                trigger => trigger.GetOnEndDragAsyncHandler(),
                (trigger, token) => trigger.GetOnEndDragAsyncHandler(token),
                handler => ((IOnityAsyncOnEndDragHandler)handler).OnEndDragAsync());
        }

        [Test]
        public void InitializePotentialDrag_RaisesEveryWaitShape()
        {
            PointerEventData eventData = new PointerEventData(null);

            CheckEventMessage<OnityAsyncInitializePotentialDragTrigger, PointerEventData>(
                eventData,
                trigger => ((IInitializePotentialDragHandler)trigger).OnInitializePotentialDrag(eventData),
                gameObject => gameObject.GetAsyncInitializePotentialDragTrigger(),
                component => component.GetAsyncInitializePotentialDragTrigger(),
                trigger => trigger.OnInitializePotentialDragAsync(),
                (trigger, token) => trigger.OnInitializePotentialDragAsync(token),
                trigger => trigger.GetOnInitializePotentialDragAsyncHandler(),
                (trigger, token) => trigger.GetOnInitializePotentialDragAsyncHandler(token),
                handler => ((IOnityAsyncOnInitializePotentialDragHandler)handler).OnInitializePotentialDragAsync());
        }

        [Test]
        public void Move_RaisesEveryWaitShape()
        {
            AxisEventData eventData = new AxisEventData(null);

            CheckEventMessage<OnityAsyncMoveTrigger, AxisEventData>(
                eventData,
                trigger => ((IMoveHandler)trigger).OnMove(eventData),
                gameObject => gameObject.GetAsyncMoveTrigger(),
                component => component.GetAsyncMoveTrigger(),
                trigger => trigger.OnMoveAsync(),
                (trigger, token) => trigger.OnMoveAsync(token),
                trigger => trigger.GetOnMoveAsyncHandler(),
                (trigger, token) => trigger.GetOnMoveAsyncHandler(token),
                handler => ((IOnityAsyncOnMoveHandler)handler).OnMoveAsync());
        }

        [Test]
        public void PointerClick_RaisesEveryWaitShape()
        {
            PointerEventData eventData = new PointerEventData(null);

            CheckEventMessage<OnityAsyncPointerClickTrigger, PointerEventData>(
                eventData,
                trigger => ((IPointerClickHandler)trigger).OnPointerClick(eventData),
                gameObject => gameObject.GetAsyncPointerClickTrigger(),
                component => component.GetAsyncPointerClickTrigger(),
                trigger => trigger.OnPointerClickAsync(),
                (trigger, token) => trigger.OnPointerClickAsync(token),
                trigger => trigger.GetOnPointerClickAsyncHandler(),
                (trigger, token) => trigger.GetOnPointerClickAsyncHandler(token),
                handler => ((IOnityAsyncOnPointerClickHandler)handler).OnPointerClickAsync());
        }

        [Test]
        public void PointerDown_RaisesEveryWaitShape()
        {
            PointerEventData eventData = new PointerEventData(null);

            CheckEventMessage<OnityAsyncPointerDownTrigger, PointerEventData>(
                eventData,
                trigger => ((IPointerDownHandler)trigger).OnPointerDown(eventData),
                gameObject => gameObject.GetAsyncPointerDownTrigger(),
                component => component.GetAsyncPointerDownTrigger(),
                trigger => trigger.OnPointerDownAsync(),
                (trigger, token) => trigger.OnPointerDownAsync(token),
                trigger => trigger.GetOnPointerDownAsyncHandler(),
                (trigger, token) => trigger.GetOnPointerDownAsyncHandler(token),
                handler => ((IOnityAsyncOnPointerDownHandler)handler).OnPointerDownAsync());
        }

        [Test]
        public void PointerEnter_RaisesEveryWaitShape()
        {
            PointerEventData eventData = new PointerEventData(null);

            CheckEventMessage<OnityAsyncPointerEnterTrigger, PointerEventData>(
                eventData,
                trigger => ((IPointerEnterHandler)trigger).OnPointerEnter(eventData),
                gameObject => gameObject.GetAsyncPointerEnterTrigger(),
                component => component.GetAsyncPointerEnterTrigger(),
                trigger => trigger.OnPointerEnterAsync(),
                (trigger, token) => trigger.OnPointerEnterAsync(token),
                trigger => trigger.GetOnPointerEnterAsyncHandler(),
                (trigger, token) => trigger.GetOnPointerEnterAsyncHandler(token),
                handler => ((IOnityAsyncOnPointerEnterHandler)handler).OnPointerEnterAsync());
        }

        [Test]
        public void PointerExit_RaisesEveryWaitShape()
        {
            PointerEventData eventData = new PointerEventData(null);

            CheckEventMessage<OnityAsyncPointerExitTrigger, PointerEventData>(
                eventData,
                trigger => ((IPointerExitHandler)trigger).OnPointerExit(eventData),
                gameObject => gameObject.GetAsyncPointerExitTrigger(),
                component => component.GetAsyncPointerExitTrigger(),
                trigger => trigger.OnPointerExitAsync(),
                (trigger, token) => trigger.OnPointerExitAsync(token),
                trigger => trigger.GetOnPointerExitAsyncHandler(),
                (trigger, token) => trigger.GetOnPointerExitAsyncHandler(token),
                handler => ((IOnityAsyncOnPointerExitHandler)handler).OnPointerExitAsync());
        }

        [Test]
        public void PointerUp_RaisesEveryWaitShape()
        {
            PointerEventData eventData = new PointerEventData(null);

            CheckEventMessage<OnityAsyncPointerUpTrigger, PointerEventData>(
                eventData,
                trigger => ((IPointerUpHandler)trigger).OnPointerUp(eventData),
                gameObject => gameObject.GetAsyncPointerUpTrigger(),
                component => component.GetAsyncPointerUpTrigger(),
                trigger => trigger.OnPointerUpAsync(),
                (trigger, token) => trigger.OnPointerUpAsync(token),
                trigger => trigger.GetOnPointerUpAsyncHandler(),
                (trigger, token) => trigger.GetOnPointerUpAsyncHandler(token),
                handler => ((IOnityAsyncOnPointerUpHandler)handler).OnPointerUpAsync());
        }

        [Test]
        public void Scroll_RaisesEveryWaitShape()
        {
            PointerEventData eventData = new PointerEventData(null);

            CheckEventMessage<OnityAsyncScrollTrigger, PointerEventData>(
                eventData,
                trigger => ((IScrollHandler)trigger).OnScroll(eventData),
                gameObject => gameObject.GetAsyncScrollTrigger(),
                component => component.GetAsyncScrollTrigger(),
                trigger => trigger.OnScrollAsync(),
                (trigger, token) => trigger.OnScrollAsync(token),
                trigger => trigger.GetOnScrollAsyncHandler(),
                (trigger, token) => trigger.GetOnScrollAsyncHandler(token),
                handler => ((IOnityAsyncOnScrollHandler)handler).OnScrollAsync());
        }

        [Test]
        public void Select_RaisesEveryWaitShape()
        {
            BaseEventData eventData = new BaseEventData(null);

            CheckEventMessage<OnityAsyncSelectTrigger, BaseEventData>(
                eventData,
                trigger => ((ISelectHandler)trigger).OnSelect(eventData),
                gameObject => gameObject.GetAsyncSelectTrigger(),
                component => component.GetAsyncSelectTrigger(),
                trigger => trigger.OnSelectAsync(),
                (trigger, token) => trigger.OnSelectAsync(token),
                trigger => trigger.GetOnSelectAsyncHandler(),
                (trigger, token) => trigger.GetOnSelectAsyncHandler(token),
                handler => ((IOnityAsyncOnSelectHandler)handler).OnSelectAsync());
        }

        [Test]
        public void Submit_RaisesEveryWaitShape()
        {
            BaseEventData eventData = new BaseEventData(null);

            CheckEventMessage<OnityAsyncSubmitTrigger, BaseEventData>(
                eventData,
                trigger => ((ISubmitHandler)trigger).OnSubmit(eventData),
                gameObject => gameObject.GetAsyncSubmitTrigger(),
                component => component.GetAsyncSubmitTrigger(),
                trigger => trigger.OnSubmitAsync(),
                (trigger, token) => trigger.OnSubmitAsync(token),
                trigger => trigger.GetOnSubmitAsyncHandler(),
                (trigger, token) => trigger.GetOnSubmitAsyncHandler(token),
                handler => ((IOnityAsyncOnSubmitHandler)handler).OnSubmitAsync());
        }

        [Test]
        public void UpdateSelected_RaisesEveryWaitShape()
        {
            BaseEventData eventData = new BaseEventData(null);

            CheckEventMessage<OnityAsyncUpdateSelectedTrigger, BaseEventData>(
                eventData,
                trigger => ((IUpdateSelectedHandler)trigger).OnUpdateSelected(eventData),
                gameObject => gameObject.GetAsyncUpdateSelectedTrigger(),
                component => component.GetAsyncUpdateSelectedTrigger(),
                trigger => trigger.OnUpdateSelectedAsync(),
                (trigger, token) => trigger.OnUpdateSelectedAsync(token),
                trigger => trigger.GetOnUpdateSelectedAsyncHandler(),
                (trigger, token) => trigger.GetOnUpdateSelectedAsyncHandler(token),
                handler => ((IOnityAsyncOnUpdateSelectedHandler)handler).OnUpdateSelectedAsync());
        }
    }
}
