#!/usr/bin/env python3
"""Generates the OnityAsync MonoBehaviour message triggers (UniTask 2.5.11 parity).

One table row per Unity message produces, for the core target (assembly Onity.Unity):
  * the handler interface  IOnityAsync<Method>Handler  with <Method>Async();
  * the explicit implementation on the partial OnityAsyncTriggerHandler<T>;
  * the GameObject / Component entry points  GetAsync<Trigger>Trigger();
  * the trigger component  OnityAsync<Trigger>Trigger  with the Unity message, the reusable-handler
    getters, and the one-shot <Method>Async() waits.
Enable, Disable, Awake, Start and Destroy are hand written (Async/Triggers and Async/OnityAsyncDestroyTrigger.cs).

Usage:
    python generate_onity_async_triggers.py            # rewrite the generated files
    python generate_onity_async_triggers.py --check    # exit 1 when a generated file is stale

Deviations from the UniTask template, on purpose:
  * ParticleUpdateJobScheduled is declared without a parameter, as Unity sends it (UniTask declares a
    ParticleSystemJobData parameter that Unity does not pass, so that trigger never fires there);
  * the audio-thread trigger (OnAudioFilterRead) synchronizes its waiter list, because Unity raises that
    message off the main thread and the usual await loop registers its next wait on the audio thread;
  * module-dependent triggers are wrapped in the symbols the Onity.Unity asmdef defines through
    versionDefines: ONITY_PHYSICS, ONITY_PHYSICS2D, ONITY_PARTICLESYSTEM;
  * like UniTask, the Mouse triggers are compiled out on iOS, Android and WSA: Unity flags every OnMouse
    handler in a handheld build, and the types would otherwise exist in every mobile project.
"""

import argparse
import os
import sys
from string import Template

REPOSITORY = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
PACKAGE = os.path.join(REPOSITORY, "Packages", "com.onity.framework")

CORE_OUTPUT = os.path.join(PACKAGE, "Runtime", "Unity", "Scripts", "Async", "Triggers",
                           "OnityAsyncMessageTriggers.Generated.cs")

HEADER = """// <auto-generated>
// Generated by tools/codegen/generate_onity_async_triggers.py. Do not edit by hand;
// change the generator and rerun it.
// </auto-generated>
"""

DOC_WIDTH = 112


class Trigger:
    """One Unity message. `params` are the message parameters as (type, name) pairs."""

    def __init__(self, name, method, params, define, summary, payload_doc="", remarks="", thread_safe=False,
                 await_remarks=""):
        self.name = name
        self.method = method
        self.params = list(params)
        self.define = define  # complete #if expression, or None
        self.summary = summary
        self.payload_doc = payload_doc
        self.remarks = remarks
        self.thread_safe = thread_safe
        self.await_remarks = await_remarks  # one sentence repeated on the awaitable members

    @property
    def platform_guard(self):
        """The #if expression that applies to test code too (a Unity platform symbol), else None."""
        return self.define if self.define == HANDHELD else None

    @property
    def payload(self):
        if not self.params:
            return "Unit"
        if len(self.params) == 1:
            return self.params[0][0]
        return "(" + ", ".join("{} {}".format(t, n) for t, n in self.params) + ")"

    @property
    def is_unit(self):
        return not self.params

    @property
    def task_type(self):
        return "OnityTask" if self.is_unit else "OnityTask<{}>".format(self.payload)

    @property
    def wait_call(self):
        return "WaitAsync()" if self.is_unit else "WaitValueAsync<{}>()".format(self.payload)

    @property
    def raise_expression(self):
        if not self.params:
            return "Unit.Default"
        if len(self.params) == 1:
            return self.params[0][1]
        return "(" + ", ".join(n for _, n in self.params) + ")"

    @property
    def message_parameters(self):
        return ", ".join("{} {}".format(t, n) for t, n in self.params)


def T(name, method, params, define, summary, payload_doc="", remarks="", thread_safe=False, await_remarks=""):
    return Trigger(name, method, params, define, summary, payload_doc, remarks, thread_safe, await_remarks)


PHYSICS = "ONITY_PHYSICS"
PHYSICS2D = "ONITY_PHYSICS2D"
PARTICLES = "ONITY_PARTICLESYSTEM"
HANDHELD = "!(UNITY_IPHONE || UNITY_ANDROID || UNITY_METRO)"

COLLISION_REUSE = ("Unity may reuse the <c>Collision</c> instance for later callbacks when "
                   "<c>Physics.reuseCollisionCallbacks</c> is enabled, so read its data (such as "
                   "<c>collider</c>) right after the await, before the continuation first yields.")
COLLISION2D_REUSE = ("Unity may reuse the <c>Collision2D</c> instance for later callbacks when "
                     "<c>Physics2D.reuseCollisionCallbacks</c> is enabled, so read its data (such as "
                     "<c>collider</c>) right after the await, before the continuation first yields.")
HANDHELD_ONLY = ("Compiled out on iOS, Android and WSA (UNITY_IPHONE, UNITY_ANDROID, UNITY_METRO), as in "
                 "UniTask, because Unity flags every <c>OnMouse</c> handler in a handheld build.")
CAMERA_ONLY = ("Unity sends this message only to components on a camera, and only in the built-in "
               "render pipeline.")
EDITOR_ONLY = "Unity sends this message only in the Editor."

# Order: as in the UniTask template. Enable/Disable/Awake/Start/Destroy are hand written.
CORE_TRIGGERS = [
    T("AnimatorIK", "OnAnimatorIK", [("int", "layerIndex")], None,
      "when the Animator updates inverse kinematics for a layer whose IK Pass is enabled",
      "the index of the animator layer",
      "Unity sends this message only while the Animator layer has its IK Pass enabled."),
    T("AnimatorMove", "OnAnimatorMove", [], None,
      "after the Animator evaluates a frame, so a script can apply the root motion itself"),
    T("OnCanvasGroupChanged", "OnCanvasGroupChanged", [], None,
      "when a <c>CanvasGroup</c> on this object or one of its parents changes"),

    T("CollisionEnter2D", "OnCollisionEnter2D", [("Collision2D", "coll")], PHYSICS2D,
      "when this object's 2D collider or rigidbody starts touching another 2D collider",
      "the contact information", await_remarks=COLLISION2D_REUSE),
    T("CollisionExit2D", "OnCollisionExit2D", [("Collision2D", "coll")], PHYSICS2D,
      "when this object's 2D collider or rigidbody stops touching another 2D collider",
      "the contact information", await_remarks=COLLISION2D_REUSE),
    T("CollisionStay2D", "OnCollisionStay2D", [("Collision2D", "coll")], PHYSICS2D,
      "on every physics step while this object's 2D collider or rigidbody touches another 2D collider",
      "the contact information", await_remarks=COLLISION2D_REUSE),
    T("CollisionEnter", "OnCollisionEnter", [("Collision", "coll")], PHYSICS,
      "when this object's collider or rigidbody starts touching another collider",
      "the contact information", await_remarks=COLLISION_REUSE),
    T("CollisionExit", "OnCollisionExit", [("Collision", "coll")], PHYSICS,
      "when this object's collider or rigidbody stops touching another collider",
      "the contact information", await_remarks=COLLISION_REUSE),
    T("CollisionStay", "OnCollisionStay", [("Collision", "coll")], PHYSICS,
      "on every physics step while this object's collider or rigidbody touches another collider",
      "the contact information", await_remarks=COLLISION_REUSE),

    T("JointBreak", "OnJointBreak", [("float", "breakForce")], PHYSICS,
      "when a joint attached to this object breaks",
      "the force that broke the joint"),
    T("JointBreak2D", "OnJointBreak2D", [("Joint2D", "brokenJoint")], PHYSICS2D,
      "when a 2D joint attached to this object breaks",
      "the joint that broke"),

    T("Update", "Update", [], None,
      "every frame while the component is enabled",
      "", "Unity calls the message every frame whether or not a wait is pending."),
    T("FixedUpdate", "FixedUpdate", [], None,
      "every fixed timestep while the component is enabled",
      "", "Unity calls the message every fixed step whether or not a wait is pending."),
    T("LateUpdate", "LateUpdate", [], None,
      "every frame, after every Update call, while the component is enabled",
      "", "Unity calls the message every frame whether or not a wait is pending."),

    T("ParticleCollision", "OnParticleCollision", [("GameObject", "other")], None,
      "when a particle hits a collider on this object",
      "the GameObject of the particle system that hit the collider"),

    T("RectTransformDimensionsChange", "OnRectTransformDimensionsChange", [], None,
      "when the dimensions of this object's <c>RectTransform</c> change (size, anchors or pivot)"),
    T("RectTransformRemoved", "OnRectTransformRemoved", [], None,
      "when the <c>RectTransform</c> of this object is removed"),

    T("BeforeTransformParentChanged", "OnBeforeTransformParentChanged", [], None,
      "just before this object's parent changes"),
    T("TransformParentChanged", "OnTransformParentChanged", [], None,
      "after this object's parent changed"),
    T("TransformChildrenChanged", "OnTransformChildrenChanged", [], None,
      "when the children of this object's transform change"),

    T("TriggerEnter2D", "OnTriggerEnter2D", [("Collider2D", "other")], PHYSICS2D,
      "when another 2D collider enters this object's trigger collider",
      "the other collider"),
    T("TriggerExit2D", "OnTriggerExit2D", [("Collider2D", "other")], PHYSICS2D,
      "when another 2D collider leaves this object's trigger collider",
      "the other collider"),
    T("TriggerStay2D", "OnTriggerStay2D", [("Collider2D", "other")], PHYSICS2D,
      "on every physics step while another 2D collider stays inside this object's trigger collider",
      "the other collider"),
    T("TriggerEnter", "OnTriggerEnter", [("Collider", "other")], PHYSICS,
      "when another collider enters this object's trigger collider",
      "the other collider"),
    T("TriggerExit", "OnTriggerExit", [("Collider", "other")], PHYSICS,
      "when another collider leaves this object's trigger collider",
      "the other collider"),
    T("TriggerStay", "OnTriggerStay", [("Collider", "other")], PHYSICS,
      "on every physics step while another collider stays inside this object's trigger collider",
      "the other collider"),

    T("BecameInvisible", "OnBecameInvisible", [], None,
      "when the object's renderer stops being visible to every camera"),
    T("BecameVisible", "OnBecameVisible", [], None,
      "when the object's renderer becomes visible to a camera"),

    T("MouseDown", "OnMouseDown", [], HANDHELD,
      "when the mouse button is pressed over this object's collider or GUI element",
      "", HANDHELD_ONLY),
    T("MouseDrag", "OnMouseDrag", [], HANDHELD,
      "on every frame the mouse is held down after pressing it over this object",
      "", HANDHELD_ONLY),
    T("MouseEnter", "OnMouseEnter", [], HANDHELD,
      "when the mouse pointer enters this object's collider or GUI element",
      "", HANDHELD_ONLY),
    T("MouseExit", "OnMouseExit", [], HANDHELD,
      "when the mouse pointer leaves this object's collider or GUI element",
      "", HANDHELD_ONLY),
    T("MouseOver", "OnMouseOver", [], HANDHELD,
      "on every frame the mouse pointer is over this object's collider or GUI element",
      "", HANDHELD_ONLY),
    T("MouseUp", "OnMouseUp", [], HANDHELD,
      "when the mouse button is released after pressing it over this object",
      "", HANDHELD_ONLY),
    T("MouseUpAsButton", "OnMouseUpAsButton", [], HANDHELD,
      "when the mouse button is released over the same object it was pressed on",
      "", HANDHELD_ONLY),

    T("ApplicationFocus", "OnApplicationFocus", [("bool", "hasFocus")], None,
      "when the application gains or loses focus",
      "whether the application has focus"),
    T("ApplicationPause", "OnApplicationPause", [("bool", "pauseStatus")], None,
      "when the application pauses or resumes",
      "whether the application is paused"),
    T("ApplicationQuit", "OnApplicationQuit", [], None,
      "before the application quits"),

    T("AudioFilterRead", "OnAudioFilterRead", [("float[]", "data"), ("int", "channels")], None,
      "when the audio thread filters a buffer of audio on this object",
      "the interleaved sample buffer and its channel count",
      "Unity raises this message on the audio thread, not on the main thread, and the buffer is valid only "
      "during the call. This trigger synchronizes its waiter list, so a wait or handler may be created, "
      "disposed or canceled from any thread, and a continuation may wait again. A waiter's continuation "
      "runs inline on the audio thread, under the list's lock: it must finish with the buffer and return "
      "quickly, and it must not touch Unity objects or block on the main thread.",
      thread_safe=True),

    T("ControllerColliderHit", "OnControllerColliderHit", [("ControllerColliderHit", "hit")], PHYSICS,
      "when a <c>CharacterController</c> on this object hits a collider while moving",
      "the hit information"),

    T("DrawGizmos", "OnDrawGizmos", [], None,
      "when the Editor draws gizmos for this object",
      "", EDITOR_ONLY),
    T("DrawGizmosSelected", "OnDrawGizmosSelected", [], None,
      "when the Editor draws gizmos for this object while it is selected",
      "", EDITOR_ONLY),

    T("GUI", "OnGUI", [], None,
      "for every IMGUI event, several times per frame",
      "", "Adding this trigger makes Unity run the IMGUI event loop for the component."),

    T("ParticleSystemStopped", "OnParticleSystemStopped", [], None,
      "when a particle system on this object stops"),
    T("ParticleTrigger", "OnParticleTrigger", [], None,
      "when particles of a system with the trigger module enabled meet a trigger condition"),

    T("PostRender", "OnPostRender", [], None,
      "after a camera on this object finished rendering",
      "", CAMERA_ONLY),
    T("PreCull", "OnPreCull", [], None,
      "before a camera on this object culls the scene",
      "", CAMERA_ONLY),
    T("PreRender", "OnPreRender", [], None,
      "before a camera on this object renders the scene",
      "", CAMERA_ONLY),

    T("RenderImage", "OnRenderImage", [("RenderTexture", "source"), ("RenderTexture", "destination")], None,
      "after a camera on this object rendered, to let a script post-process the image",
      "the rendered source texture and the destination texture",
      CAMERA_ONLY + " Once the component exists the script owns the final blit: a wait that does not copy "
      "the source to the destination in its continuation leaves the camera output undefined."),

    T("RenderObject", "OnRenderObject", [], None,
      "after the scene's regular rendering finished, to let a script draw with the <c>GL</c> class"),
    T("ServerInitialized", "OnServerInitialized", [], None,
      "when a legacy-networking server finished initializing"),
    T("Validate", "OnValidate", [], None,
      "when the component is loaded or a value changes in the Inspector",
      "", EDITOR_ONLY),
    T("WillRenderObject", "OnWillRenderObject", [], None,
      "once per camera while the object's renderer is visible"),
    T("Reset", "Reset", [], None,
      "when the component is first added or reset from the Inspector",
      "", EDITOR_ONLY),

    T("ParticleUpdateJobScheduled", "OnParticleUpdateJobScheduled", [], PARTICLES,
      "when a particle system's built-in update job has been scheduled",
      "", "Unlike UniTask 2.5.11, which declares a <c>ParticleSystemJobData</c> parameter that Unity does "
          "not pass, this trigger is declared without a parameter, as Unity sends the message."),
]


def wrap(text, indent="    ", width=DOC_WIDTH):
    """Wraps text for a '///' block at the given indentation, keeping '<see cref=...>' tags whole."""
    protected = text.replace("<see cref", "<see\x00cref")
    lines, current = [], ""
    for word in protected.split():
        candidate = word if not current else current + " " + word
        if current and len(indent) + 4 + len(candidate) > width:
            lines.append(current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(current)
    return [line.replace("\x00", " ") for line in lines]


def doc_block(lines, indent="    "):
    return "\n".join(indent + "/// " + line for line in lines)


TRIGGER_TEMPLATE = Template("""#region ${name}
${define_open}
    /// <summary>
${interface_summary}
    /// </summary>
    public interface IOnityAsync${method}Handler
    {
        /// <summary>Waits for the next <c>${method}</c> message. ${thread}</summary>
        /// <returns>A single-consumption task${payload_returns}; canceled when the trigger is destroyed.</returns>
${await_remarks}        ${task_type} ${method}Async();
    }

    public sealed partial class OnityAsyncTriggerHandler<T> : IOnityAsync${method}Handler
    {
        ${task_type} IOnityAsync${method}Handler.${method}Async()
        {
            return ${wait_call};
        }
    }

    public static partial class OnityAsyncTriggerExtensions
    {
        /// <summary>Gets or adds the <see cref="OnityAsync${name}Trigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsync${name}Trigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsync${name}Trigger GetAsync${name}Trigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsync${name}Trigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsync${name}Trigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsync${name}Trigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsync${name}Trigger GetAsync${name}Trigger(this Component component)
        {
            return GetGameObject(component).GetAsync${name}Trigger();
        }
    }

    /// <summary>
${class_summary}
    /// </summary>
${class_remarks}    [DisallowMultipleComponent]
    public sealed class OnityAsync${name}Trigger : OnityAsyncTriggerBase<${payload}>
    {
${constructor}        /// <summary>Creates a reusable handler; dispose it to unregister. ${thread}</summary>
        /// <returns>A handler whose each <c>${method}Async()</c> waits for the next message.</returns>
        public IOnityAsync${method}Handler Get${method}AsyncHandler()
        {
            return new OnityAsyncTriggerHandler<${payload}>(this, false);
        }

        /// <summary>Creates a reusable handler bound to a token. ${thread}</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>${method}Async()</c> waits for the next message.</returns>
        public IOnityAsync${method}Handler Get${method}AsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsyncTriggerHandler<${payload}>(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>${method}</c> message. ${thread}</summary>
        /// <returns>A single-consumption task${payload_returns}; canceled when the trigger is destroyed.</returns>
${await_remarks}        public ${task_type} ${method}Async()
        {
            return ((IOnityAsync${method}Handler)new OnityAsyncTriggerHandler<${payload}>(this, true)).${method}Async();
        }

        /// <summary>Waits for the next <c>${method}</c> message. ${thread}</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task${payload_returns}; canceled by the token or when the trigger is destroyed.</returns>
${await_remarks}        public ${task_type} ${method}Async(CancellationToken cancellationToken)
        {
            return ((IOnityAsync${method}Handler)new OnityAsyncTriggerHandler<${payload}>(this, cancellationToken, true)).${method}Async();
        }

        private void ${method}(${message_parameters})
        {
            RaiseEvent(${raise_expression});
        }
    }
${define_close}#endregion
""")


def render_trigger(trigger):
    interface_text = ("Waits for the next <c>{}</c> message, which Unity sends {} "
                      "(UniTask <c>IAsync{}Handler</c> parity).").format(trigger.method, trigger.summary,
                                                                        trigger.method)
    thread = "Safe to call from any thread." if trigger.thread_safe else "Main thread only."
    class_text = ("Trigger for the <c>{}</c> message, which Unity sends {} (UniTask <c>Async{}Trigger</c> "
                  "parity). The component itself is an <see cref=\"IOnityAsyncEnumerable{{T}}\"/> of the "
                  "raised messages. {}").format(trigger.method, trigger.summary, trigger.name, thread)
    class_remarks = ""
    if trigger.remarks:
        class_remarks = ("    /// <remarks>\n" + doc_block(wrap(trigger.remarks)) + "\n    /// </remarks>\n")
    payload_returns = "" if trigger.is_unit else " completed with " + trigger.payload_doc
    await_remarks = ""
    if trigger.await_remarks:
        await_remarks = ("        /// <remarks>\n"
                         + doc_block(wrap(trigger.await_remarks, "        "), "        ")
                         + "\n        /// </remarks>\n")
    constructor = ""
    if trigger.thread_safe:
        constructor = ("        /// <summary>\n"
                       "        /// Creates the trigger with a synchronized waiter list, because Unity raises this message off the\n"
                       "        /// main thread.\n"
                       "        /// </summary>\n"
                       "        public OnityAsync{}Trigger()\n"
                       "        {{\n"
                       "            UseThreadSafeWaiters();\n"
                       "        }}\n\n").format(trigger.name)
    if trigger.define:
        define_open = "#if {}\n".format(trigger.define)
        define_close = "\n#endif\n"
    else:
        define_open = ""
        define_close = ""
    return TRIGGER_TEMPLATE.substitute(
        name=trigger.name,
        method=trigger.method,
        thread=thread,
        constructor=constructor,
        await_remarks=await_remarks,
        define_open=define_open,
        define_close=define_close,
        interface_summary=doc_block(wrap(interface_text)),
        class_summary=doc_block(wrap(class_text)),
        class_remarks=class_remarks,
        payload=trigger.payload,
        payload_returns=payload_returns,
        task_type=trigger.task_type,
        wait_call=trigger.wait_call,
        message_parameters=trigger.message_parameters,
        raise_expression=trigger.raise_expression,
    )


def generate_core():
    parts = [HEADER,
             "using System;\nusing System.Threading;\nusing Onity.Core;\nusing UnityEngine;\n\n",
             "namespace Onity.Unity.Async.Triggers\n{\n",
             "\n".join(render_trigger(trigger) for trigger in CORE_TRIGGERS),
             "}\n"]
    return "".join(parts)


# --- EditMode tests: one generated row per trigger, logic in OnityAsyncMessageTriggerEditModeTests.cs ---

EDIT_TEST_OUTPUT = os.path.join(PACKAGE, "Tests", "EditMode", "Scripts",
                                "OnityAsyncMessageTriggerEditModeTests.Generated.cs")

# Sample value per message parameter type. NewComponent<T>() and NewObject() are helpers of the hand-written part.
SAMPLE_INITIALIZERS = {
    "int": "3",
    "float": "12.5f",
    "bool": "true",
    "float[]": "new float[4]",
    "Collision2D": "new Collision2D()",
    "Collision": "new Collision()",
    "Joint2D": "NewComponent<HingeJoint2D>()",
    "GameObject": "NewObject()",
    "Collider2D": "NewComponent<BoxCollider2D>()",
    "Collider": "NewComponent<BoxCollider>()",
    "ControllerColliderHit": "new ControllerColliderHit()",
    "RenderTexture": "null",
}

EDIT_TEST_TEMPLATE = Template("""        [Test]
        public void ${name}_RaisesEveryWaitShape()
        {
${locals}            Check${kind}Message<OnityAsync${name}Trigger${payload_argument}>(
                "${method}",${payload_arguments}
                gameObject => gameObject.GetAsync${name}Trigger(),
                component => component.GetAsync${name}Trigger(),
                trigger => trigger.${method}Async(),
                (trigger, token) => trigger.${method}Async(token),
                trigger => trigger.Get${method}AsyncHandler(),
                (trigger, token) => trigger.Get${method}AsyncHandler(token),
                handler => ((IOnityAsync${method}Handler)handler).${method}Async());
        }
""")


def render_edit_test(trigger):
    locals_text = ""
    payload_arguments = ""
    if trigger.params:
        for type_name, parameter in trigger.params:
            locals_text += "            {} {} = {};\n".format(type_name, parameter, SAMPLE_INITIALIZERS[type_name])
        locals_text += "\n"
        payload_arguments = "\n                {}, new object[] {{ {} }},".format(
            trigger.raise_expression, ", ".join(name for _, name in trigger.params))
    row = EDIT_TEST_TEMPLATE.substitute(
        name=trigger.name,
        method=trigger.method,
        kind="Unit" if trigger.is_unit else "Value",
        payload_argument="" if trigger.is_unit else ", " + trigger.payload,
        locals=locals_text,
        payload_arguments=payload_arguments,
    )
    if trigger.platform_guard:
        row = "#if {}\n{}#endif\n".format(trigger.platform_guard, row)
    return row


def generate_edit_tests():
    parts = [HEADER,
             "using NUnit.Framework;\nusing Onity.Unity.Async.Triggers;\nusing UnityEngine;\n\n",
             "namespace Onity.Tests.EditMode\n{\n",
             "    public sealed partial class OnityAsyncMessageTriggerEditModeTests\n    {\n",
             "\n".join(render_edit_test(trigger) for trigger in CORE_TRIGGERS),
             "    }\n}\n"]
    return "".join(parts)


# --- uGUI (optional assembly Onity.Unity.UGUI, compiled only when com.unity.ugui is installed) ---

UGUI_ROOT = os.path.join(PACKAGE, "Runtime", "Unity.UGUI", "Scripts")
UGUI_TRIGGER_OUTPUT = os.path.join(UGUI_ROOT, "OnityAsyncEventSystemTriggers.Generated.cs")
UGUI_EXTENSION_OUTPUT = os.path.join(UGUI_ROOT, "OnityUguiAsyncExtensions.Generated.cs")
UGUI_TEST_OUTPUT = os.path.join(PACKAGE, "Tests", "PlayMode", "UGUI",
                                "OnityAsyncEventSystemTriggerPlayModeTests.Generated.cs")


class EventSystemTrigger:
    """One EventSystems interface message. All of them take a single event-data parameter."""

    def __init__(self, name, handler_interface, payload, summary):
        self.name = name
        self.method = "On" + name
        self.handler_interface = handler_interface
        self.payload = payload
        self.summary = summary


UGUI_TRIGGERS = [
    EventSystemTrigger("BeginDrag", "IBeginDragHandler", "PointerEventData",
                       "when the pointer starts dragging this object"),
    EventSystemTrigger("Cancel", "ICancelHandler", "BaseEventData",
                       "when the Cancel input is raised while this object is selected"),
    EventSystemTrigger("Deselect", "IDeselectHandler", "BaseEventData",
                       "when this object stops being the selected object"),
    EventSystemTrigger("Drag", "IDragHandler", "PointerEventData",
                       "on every pointer move while this object is being dragged"),
    EventSystemTrigger("Drop", "IDropHandler", "PointerEventData",
                       "when a dragged object is dropped on this object"),
    EventSystemTrigger("EndDrag", "IEndDragHandler", "PointerEventData",
                       "when a drag of this object ends"),
    EventSystemTrigger("InitializePotentialDrag", "IInitializePotentialDragHandler", "PointerEventData",
                       "when a pointer press may start a drag of this object"),
    EventSystemTrigger("Move", "IMoveHandler", "AxisEventData",
                       "when a move input such as an arrow key or a gamepad stick is raised while this object is selected"),
    EventSystemTrigger("PointerClick", "IPointerClickHandler", "PointerEventData",
                       "when the pointer is pressed and released over this object"),
    EventSystemTrigger("PointerDown", "IPointerDownHandler", "PointerEventData",
                       "when the pointer is pressed over this object"),
    EventSystemTrigger("PointerEnter", "IPointerEnterHandler", "PointerEventData",
                       "when the pointer enters this object"),
    EventSystemTrigger("PointerExit", "IPointerExitHandler", "PointerEventData",
                       "when the pointer leaves this object"),
    EventSystemTrigger("PointerUp", "IPointerUpHandler", "PointerEventData",
                       "when the pointer is released over this object"),
    EventSystemTrigger("Scroll", "IScrollHandler", "PointerEventData",
                       "when the scroll wheel moves over this object"),
    EventSystemTrigger("Select", "ISelectHandler", "BaseEventData",
                       "when this object becomes the selected object"),
    EventSystemTrigger("Submit", "ISubmitHandler", "BaseEventData",
                       "when the Submit input is raised while this object is selected"),
    EventSystemTrigger("UpdateSelected", "IUpdateSelectedHandler", "BaseEventData",
                       "on every update while this object is the selected object"),
]

UGUI_PAYLOADS = ["PointerEventData", "BaseEventData", "AxisEventData"]

UGUI_TRIGGER_TEMPLATE = Template("""#region ${name}

    /// <summary>
${interface_summary}
    /// </summary>
    public interface IOnityAsync${method}Handler
    {
        /// <summary>Waits for the next <c>${method}</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data, which Unity may reuse after the continuation first yields; canceled when the trigger is destroyed.</returns>
        OnityTask<${payload}> ${method}Async();
    }

    /// <summary>
${class_summary}
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class OnityAsync${name}Trigger : OnityAsyncTriggerBase<${payload}>, ${handler_interface}
    {
        /// <summary>Creates a reusable handler; dispose it to unregister. Main thread only.</summary>
        /// <returns>A handler whose each <c>${method}Async()</c> waits for the next event.</returns>
        public IOnityAsync${method}Handler Get${method}AsyncHandler()
        {
            return new OnityAsync${payload}Handler(this, CancellationToken.None, false);
        }

        /// <summary>Creates a reusable handler bound to a token. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the pending wait and unregisters the handler.</param>
        /// <returns>A handler whose each <c>${method}Async()</c> waits for the next event.</returns>
        public IOnityAsync${method}Handler Get${method}AsyncHandler(CancellationToken cancellationToken)
        {
            return new OnityAsync${payload}Handler(this, cancellationToken, false);
        }

        /// <summary>Waits for the next <c>${method}</c> event. Main thread only.</summary>
        /// <returns>A single-consumption task completed with the event data; canceled when the trigger is destroyed.</returns>
        public OnityTask<${payload}> ${method}Async()
        {
            return ((IOnityAsync${method}Handler)new OnityAsync${payload}Handler(this, CancellationToken.None, true)).${method}Async();
        }

        /// <summary>Waits for the next <c>${method}</c> event. Main thread only.</summary>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task completed with the event data; canceled by the token or when the trigger is destroyed.</returns>
        public OnityTask<${payload}> ${method}Async(CancellationToken cancellationToken)
        {
            return ((IOnityAsync${method}Handler)new OnityAsync${payload}Handler(this, cancellationToken, true)).${method}Async();
        }

        void ${handler_interface}.${method}(${payload} eventData)
        {
            RaiseEvent(eventData);
        }
    }
#endregion
""")

UGUI_HANDLER_TEMPLATE = Template("""    // Adapts the shared trigger handler to the handler interfaces of the messages that carry ${payload}.
    internal sealed class OnityAsync${payload}Handler :
${interfaces},
        IDisposable
    {
        private readonly OnityAsyncTriggerHandler<${payload}> m_handler;

        internal OnityAsync${payload}Handler(
            OnityAsyncTriggerBase<${payload}> trigger, CancellationToken cancellationToken, bool callOnce)
        {
            m_handler = new OnityAsyncTriggerHandler<${payload}>(trigger, cancellationToken, callOnce);
        }

        public void Dispose()
        {
            m_handler.Dispose();
        }
${methods}    }
""")

UGUI_EXTENSION_ENTRY = Template("""        /// <summary>Gets or adds the <see cref="OnityAsync${name}Trigger"/>. Main thread only.</summary>
        /// <param name="gameObject">Live owner GameObject.</param>
        /// <returns>The single <see cref="OnityAsync${name}Trigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="gameObject"/> is null.</exception>
        public static OnityAsync${name}Trigger GetAsync${name}Trigger(this GameObject gameObject)
        {
            return GetOrAddComponent<OnityAsync${name}Trigger>(gameObject);
        }

        /// <summary>Gets or adds the <see cref="OnityAsync${name}Trigger"/> on the component's GameObject. Main thread only.</summary>
        /// <param name="component">Live owner component.</param>
        /// <returns>The single <see cref="OnityAsync${name}Trigger"/> on the GameObject.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="component"/> is null.</exception>
        public static OnityAsync${name}Trigger GetAsync${name}Trigger(this Component component)
        {
            return GetGameObject(component).GetAsync${name}Trigger();
        }
""")


def render_ugui_trigger(trigger):
    interface_text = ("Waits for the next <c>{}</c> event, which the event system sends {} "
                      "(UniTask <c>IAsync{}Handler</c> parity).").format(trigger.method, trigger.summary,
                                                                        trigger.method)
    class_text = ("Trigger for the <c>{}</c> event, which the event system sends {} (UniTask "
                  "<c>Async{}Trigger</c> parity). The component itself is an "
                  "<see cref=\"IOnityAsyncEnumerable{{T}}\"/> of the raised events. Main thread only.").format(
                      trigger.method, trigger.summary, trigger.name)
    return UGUI_TRIGGER_TEMPLATE.substitute(
        name=trigger.name,
        method=trigger.method,
        payload=trigger.payload,
        handler_interface=trigger.handler_interface,
        interface_summary=doc_block(wrap(interface_text)),
        class_summary=doc_block(wrap(class_text)),
    )


def render_ugui_handler(payload):
    triggers = [t for t in UGUI_TRIGGERS if t.payload == payload]
    interfaces = ",\n".join("        IOnityAsync{}Handler".format(t.method) for t in triggers)
    methods = ""
    for trigger in triggers:
        methods += ("\n        OnityTask<{p}> IOnityAsync{m}Handler.{m}Async()\n        {{\n"
                    "            return m_handler.WaitValueAsync<{p}>();\n        }}\n").format(
                        p=payload, m=trigger.method)
    return UGUI_HANDLER_TEMPLATE.substitute(payload=payload, interfaces=interfaces, methods=methods)


def generate_ugui_triggers():
    parts = [HEADER,
             "using System;\nusing System.Threading;\nusing UnityEngine;\nusing UnityEngine.EventSystems;\n\n",
             "namespace Onity.Unity.Async.Triggers\n{\n",
             "\n".join(render_ugui_trigger(trigger) for trigger in UGUI_TRIGGERS),
             "\n",
             "\n".join(render_ugui_handler(payload) for payload in UGUI_PAYLOADS),
             "\n",
             "    /// <summary>\n"
             "    /// Entry points that get or add the EventSystems triggers on a GameObject (UniTask\n"
             "    /// <c>AsyncTriggerExtensions</c> parity). Each trigger type is added at most once per GameObject and\n"
             "    /// reused. Every member requires Unity's main thread.\n"
             "    /// </summary>\n"
             "    public static class OnityAsyncEventSystemTriggerExtensions\n    {\n",
             "\n".join(UGUI_EXTENSION_ENTRY.substitute(name=t.name) for t in UGUI_TRIGGERS),
             "\n"
             "        private static T GetOrAddComponent<T>(GameObject gameObject)\n"
             "            where T : Component\n"
             "        {\n"
             "            if (ReferenceEquals(gameObject, null))\n"
             "            {\n"
             "                throw new ArgumentNullException(nameof(gameObject));\n"
             "            }\n"
             "\n"
             "            if (!gameObject.TryGetComponent(out T component))\n"
             "            {\n"
             "                component = gameObject.AddComponent<T>();\n"
             "            }\n"
             "\n"
             "            return component;\n"
             "        }\n"
             "\n"
             "        private static GameObject GetGameObject(Component component)\n"
             "        {\n"
             "            if (ReferenceEquals(component, null))\n"
             "            {\n"
             "                throw new ArgumentNullException(nameof(component));\n"
             "            }\n"
             "\n"
             "            return component.gameObject;\n"
             "        }\n"
             "    }\n"
             "}\n"]
    return "".join(parts)


# uGUI components: (component, event field, value type or None for a click, verb, handler interface,
# event description)
UGUI_COMPONENT_EVENTS = [
    ("Button", "onClick", None, "Click", "IOnityAsyncClickEventHandler", "click"),
    ("Toggle", "onValueChanged", "bool", "ValueChanged", "IOnityAsyncValueChangedEventHandler<bool>",
     "value change"),
    ("Scrollbar", "onValueChanged", "float", "ValueChanged", "IOnityAsyncValueChangedEventHandler<float>",
     "value change"),
    ("ScrollRect", "onValueChanged", "Vector2", "ValueChanged", "IOnityAsyncValueChangedEventHandler<Vector2>",
     "scroll position change"),
    ("Slider", "onValueChanged", "float", "ValueChanged", "IOnityAsyncValueChangedEventHandler<float>",
     "value change"),
    ("InputField", "onEndEdit", "string", "EndEdit", "IOnityAsyncEndEditEventHandler<string>",
     "end-edit event"),
    ("InputField", "onValueChanged", "string", "ValueChanged", "IOnityAsyncValueChangedEventHandler<string>",
     "text change"),
    ("Dropdown", "onValueChanged", "int", "ValueChanged", "IOnityAsyncValueChangedEventHandler<int>",
     "selection change"),
]

UGUI_EXTENSION_TEMPLATE = Template("""        /// <summary>
        /// Creates a reusable handler for the ${description} of the ${component} that stays registered
        /// until disposed or until the ${component} is destroyed. Main thread only.
        /// </summary>
        /// <param name="${arg}">${component} to listen to.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="${arg}"/> is null.</exception>
        public static ${handler_interface} GetAsync${verb}EventHandler(this ${component} ${arg})
        {
            ThrowIfNull(${arg}, nameof(${arg}));
            return new ${handler_class}(${arg}.${field}, ${arg}.GetCancellationTokenOnDestroy(), false);
        }

        /// <summary>
        /// Creates a reusable handler for the ${description} of the ${component} that stays registered
        /// until disposed or until the token is canceled. Main thread only.
        /// </summary>
        /// <param name="${arg}">${component} to listen to.</param>
        /// <param name="cancellationToken">Stops listening when canceled.</param>
        /// <returns>The handler; dispose it to unregister.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="${arg}"/> is null.</exception>
        public static ${handler_interface} GetAsync${verb}EventHandler(
            this ${component} ${arg}, CancellationToken cancellationToken)
        {
            ThrowIfNull(${arg}, nameof(${arg}));
            return new ${handler_class}(${arg}.${field}, cancellationToken, false);
        }

        /// <summary>
        /// Waits for the next ${description} of the ${component}; the wait is canceled when the
        /// ${component} is destroyed. Main thread only.
        /// </summary>
        /// <param name="${arg}">${component} to listen to.</param>
        /// <returns>A single-consumption task${returns}; canceled on destroy.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="${arg}"/> is null.</exception>
        public static ${task_type} On${verb}Async(this ${component} ${arg})
        {
            ThrowIfNull(${arg}, nameof(${arg}));
            return new ${handler_class}(${arg}.${field}, ${arg}.GetCancellationTokenOnDestroy(), true).OnInvokeAsync();
        }

        /// <summary>Waits for the next ${description} of the ${component}. Main thread only.</summary>
        /// <param name="${arg}">${component} to listen to.</param>
        /// <param name="cancellationToken">Cancels the wait.</param>
        /// <returns>A single-consumption task${returns}; canceled by the token.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="${arg}"/> is null.</exception>
        public static ${task_type} On${verb}Async(this ${component} ${arg}, CancellationToken cancellationToken)
        {
            ThrowIfNull(${arg}, nameof(${arg}));
            return new ${handler_class}(${arg}.${field}, cancellationToken, true).OnInvokeAsync();
        }

        /// <summary>
        /// Exposes the ${description}s of the ${component} as an async sequence that ends when the
        /// ${component} is destroyed. Main thread only.
        /// </summary>
        /// <param name="${arg}">${component} to listen to.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="${arg}"/> is null.</exception>
        public static IOnityAsyncEnumerable<${item}> On${verb}AsAsyncEnumerable(this ${component} ${arg})
        {
            ThrowIfNull(${arg}, nameof(${arg}));
            return new ${enumerable_class}(${arg}.${field}, ${arg}.GetCancellationTokenOnDestroy());
        }

        /// <summary>
        /// Exposes the ${description}s of the ${component} as an async sequence that ends when the token is
        /// canceled. Main thread only.
        /// </summary>
        /// <param name="${arg}">${component} to listen to.</param>
        /// <param name="cancellationToken">Ends every enumeration when canceled.</param>
        /// <returns>A sequence that listens while an enumerator moves; an event while no move is pending is skipped.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="${arg}"/> is null.</exception>
        public static IOnityAsyncEnumerable<${item}> On${verb}AsAsyncEnumerable(
            this ${component} ${arg}, CancellationToken cancellationToken)
        {
            ThrowIfNull(${arg}, nameof(${arg}));
            return new ${enumerable_class}(${arg}.${field}, cancellationToken);
        }
""")


def render_ugui_extension(entry):
    component, field, value_type, verb, handler_interface, description = entry
    argument = component[0].lower() + component[1:]
    if value_type is None:
        handler_class = "OnityAsyncUnityEventHandler"
        enumerable_class = "OnityUnityEventAsyncEnumerable"
        task_type = "OnityTask"
        item = "Unit"
        returns = ""
    else:
        handler_class = "OnityAsyncUnityEventHandler<{}>".format(value_type)
        enumerable_class = "OnityUnityEventAsyncEnumerable<{}>".format(value_type)
        task_type = "OnityTask<{}>".format(value_type)
        item = value_type
        returns = " completed with the new value"
    return UGUI_EXTENSION_TEMPLATE.substitute(
        component=component, arg=argument, field=field, verb=verb, handler_interface=handler_interface,
        handler_class=handler_class, enumerable_class=enumerable_class, task_type=task_type, item=item,
        returns=returns, description=description)


def generate_ugui_extensions():
    parts = [HEADER,
             "using System;\nusing System.Threading;\nusing Onity.Core;\nusing UnityEngine;\n"
             "using UnityEngine.UI;\n\n",
             "namespace Onity.Unity.Async\n{\n",
             "    /// <summary>\n"
             "    /// Awaitable waits, async sequences and reusable handlers for the events of uGUI components (UniTask\n"
             "    /// <c>UnityAsyncExtensions</c> parity). Overloads without a token end with the destroy of the\n"
             "    /// component. Every member requires Unity's main thread.\n"
             "    /// </summary>\n"
             "    public static class OnityUguiAsyncExtensions\n    {\n",
             "\n".join(render_ugui_extension(entry) for entry in UGUI_COMPONENT_EVENTS),
             "\n"
             "        private static void ThrowIfNull(object component, string name)\n"
             "        {\n"
             "            if (ReferenceEquals(component, null))\n"
             "            {\n"
             "                throw new ArgumentNullException(name);\n"
             "            }\n"
             "        }\n"
             "    }\n"
             "}\n"]
    return "".join(parts)


UGUI_TEST_TEMPLATE = Template("""        [Test]
        public void ${name}_RaisesEveryWaitShape()
        {
            ${payload} eventData = new ${payload}(null);

            CheckEventMessage<OnityAsync${name}Trigger, ${payload}>(
                eventData,
                trigger => ((${handler_interface})trigger).${method}(eventData),
                gameObject => gameObject.GetAsync${name}Trigger(),
                component => component.GetAsync${name}Trigger(),
                trigger => trigger.${method}Async(),
                (trigger, token) => trigger.${method}Async(token),
                trigger => trigger.Get${method}AsyncHandler(),
                (trigger, token) => trigger.Get${method}AsyncHandler(token),
                handler => ((IOnityAsync${method}Handler)handler).${method}Async());
        }
""")


def generate_ugui_tests():
    rows = "\n".join(
        UGUI_TEST_TEMPLATE.substitute(name=t.name, method=t.method, payload=t.payload,
                                      handler_interface=t.handler_interface)
        for t in UGUI_TRIGGERS)
    parts = [HEADER,
             "using NUnit.Framework;\nusing Onity.Unity.Async.Triggers;\nusing UnityEngine.EventSystems;\n\n",
             "namespace Onity.Tests.UGUI.PlayMode\n{\n",
             "    public sealed partial class OnityAsyncEventSystemTriggerPlayModeTests\n    {\n",
             rows,
             "    }\n}\n"]
    return "".join(parts)


TARGETS = {
    "core": (CORE_OUTPUT, generate_core),
    "edit-tests": (EDIT_TEST_OUTPUT, generate_edit_tests),
    "ugui-triggers": (UGUI_TRIGGER_OUTPUT, generate_ugui_triggers),
    "ugui-extensions": (UGUI_EXTENSION_OUTPUT, generate_ugui_extensions),
    "ugui-tests": (UGUI_TEST_OUTPUT, generate_ugui_tests),
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 when a generated file is stale")
    parser.add_argument("--target", choices=sorted(TARGETS) + ["all"], default="all")
    args = parser.parse_args()
    names = sorted(TARGETS) if args.target == "all" else [args.target]
    stale = False
    for name in names:
        path, generate = TARGETS[name]
        text = generate()
        if args.check:
            try:
                with open(path, "r", encoding="utf-8", newline="") as handle:
                    current = handle.read().replace("\r\n", "\n")
            except FileNotFoundError:
                current = ""
            if current != text:
                print("STALE: " + path)
                stale = True
            else:
                print("UP_TO_DATE: " + path)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        print("WROTE: {} ({} lines)".format(path, text.count("\n")))
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
