#!/usr/bin/env python3
"""Generates the fixed-arity OnityTask composition overloads (arities 2 to 15).

Outputs, relative to the repository root:

    Packages/com.onity.framework/Runtime/Unity/Scripts/Async/OnityTask.WhenAll.Generated.cs
        Tuple WhenAll<T1..Tn> overloads and their pooled sources.
    Packages/com.onity.framework/Runtime/Unity/Scripts/Async/OnityTask.WhenAny.Generated.cs
        Mixed WhenAny<T1..Tn> overloads returning (int winArgumentIndex, T1 result1, ...) and their
        pooled sources.
    Packages/com.onity.framework/Runtime/Unity/Scripts/Async/OnityTaskCompositionAwaitExtensions.Generated.cs
        GetAwaiter shorthands for typed and untyped task tuples.

Usage:

    python tools/codegen/generate_onitytask_composition.py          # write the files
    python tools/codegen/generate_onitytask_composition.py --check  # exit 1 when a file is stale

The output depends only on this script, so the generated files are reproducible. Files are
written with LF line endings; the check ignores carriage returns added by a Git checkout.
Generation fails when a generated line exceeds LINE_LIMIT columns.
"""

import argparse
import sys
from pathlib import Path

MIN_ARITY = 2
MAX_ARITY = 15
LINE_LIMIT = 120
INDENT = "    "
REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
ASYNC_FOLDER = (REPOSITORY_ROOT / "Packages" / "com.onity.framework" / "Runtime" / "Unity"
                / "Scripts" / "Async")

HEADER = [
    "// <auto-generated>",
    "// Generated by tools/codegen/generate_onitytask_composition.py; do not edit by hand.",
    "// Regenerate with: python tools/codegen/generate_onitytask_composition.py",
    "// Verify with: python tools/codegen/generate_onitytask_composition.py --check",
    "// </auto-generated>",
]

COUNT_WORDS = {
    2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight", 9: "nine",
    10: "ten", 11: "eleven", 12: "twelve", 13: "thirteen", 14: "fourteen", 15: "fifteen",
}

ORDINAL_WORDS = {
    1: "First", 2: "Second", 3: "Third", 4: "Fourth", 5: "Fifth", 6: "Sixth", 7: "Seventh",
    8: "Eighth", 9: "Ninth", 10: "Tenth", 11: "Eleventh", 12: "Twelfth", 13: "Thirteenth",
    14: "Fourteenth", 15: "Fifteenth",
}


def positions(arity):
    return range(1, arity + 1)


def arities():
    return range(MIN_ARITY, MAX_ARITY + 1)


def type_parameters(arity):
    return ", ".join(f"T{i}" for i in positions(arity))


def result_tuple(arity):
    return f"({type_parameters(arity)})"


def task_parameters(arity):
    return [f"OnityTask<T{i}> task{i}" for i in positions(arity)]


def when_all_cref(arity):
    tasks = ", ".join(f"OnityTask{{T{i}}}" for i in positions(arity))
    return f"OnityTask.WhenAll{{{type_parameters(arity)}}}({tasks})"


def separated(items, last_suffix):
    """Comma-terminates every item except the last, which receives the suffix."""
    return [item + ("," if index < len(items) - 1 else last_suffix) for index, item in enumerate(items)]


class Writer:
    """Collects indented lines and renders them with LF line endings."""

    def __init__(self):
        self.lines = []
        self.depth = 0

    def fits(self, text, extra_depth=0):
        return len(INDENT * (self.depth + extra_depth)) + len(text) <= LINE_LIMIT

    def line(self, text=""):
        self.lines.append(INDENT * self.depth + text if text else "")

    def doc(self, text):
        self.line("/// " + text)

    def open(self, text=None):
        if text is not None:
            self.line(text)
        self.line("{")
        self.depth += 1

    def close(self):
        self.depth -= 1
        self.line("}")

    def indented(self, texts, levels=1):
        self.depth += levels
        for text in texts:
            self.line(text)
        self.depth -= levels

    def render(self):
        too_long = [line for line in self.lines if len(line) > LINE_LIMIT]
        if too_long:
            raise ValueError(f"{len(too_long)} generated line(s) exceed {LINE_LIMIT} columns, "
                             f"for example: {too_long[0].strip()}")
        return "\n".join(self.lines) + "\n"


def write_header(writer, usings):
    for text in HEADER:
        writer.line(text)
    writer.line()
    for using in usings:
        writer.line(f"using {using};")
    if usings:
        writer.line()


def write_generic_signature(writer, head, arity, parameters):
    """Writes '<head><T1..Tn>(' and one parameter per line, splitting the type parameters when long."""
    one_line = f"{head}<{type_parameters(arity)}>("
    if writer.fits(one_line):
        writer.line(one_line)
    else:
        writer.line(f"{head}<")
        writer.indented([f"{type_parameters(arity)}>("])
    writer.indented(separated(parameters, ")"))


def write_tuple_parameter(writer, elements, name):
    """Writes 'this (e1, ..., en) name)' on one line or one tuple element per line."""
    one_line = f"this ({', '.join(elements)}) {name})"
    if writer.fits(one_line, 1):
        writer.indented([one_line])
        return
    writer.indented(["this ("])
    writer.indented(separated(elements, f") {name})"), 2)


def write_cref_or_code(writer, prefix, cref, fallback, suffix):
    """Writes a doc line with a cref when it fits, otherwise names the member as code."""
    text = f"{prefix}<see cref=\"{cref}\"/>{suffix}"
    if writer.fits("/// " + text):
        writer.doc(text)
    else:
        writer.doc(f"{prefix}<c>{fallback}</c>{suffix}")


def write_switch(writer, arity, case_body):
    """Writes a switch over the zero-based input index; the last input is the default case."""
    writer.open("switch (index)")
    for i in positions(arity):
        writer.line(f"case {i - 1}:" if i < arity else "default:")
        writer.indented(case_body(i))
    writer.close()


def write_rent_call(writer, owner, arguments):
    """Writes 'var source = <owner>.Source.Rent(' with one argument per line."""
    one_line = f"var source = {owner}.Source.Rent("
    if writer.fits(one_line):
        writer.line(one_line)
        writer.indented(separated(arguments, ");"))
    else:
        writer.line("var source =")
        writer.indented([f"{owner}.Source.Rent("])
        writer.indented(separated(arguments, ");"), 2)


# ----------------------------------------------------------------------------------------------
# Tuple WhenAll
# ----------------------------------------------------------------------------------------------

def write_when_all_method(writer, arity):
    tuple_type = result_tuple(arity)
    writer.doc("<summary>")
    writer.doc(f"Awaits {COUNT_WORDS[arity]} typed tasks and returns their results as a tuple in argument order.")
    writer.doc("The result types are independent of each other.")
    writer.doc("</summary>")
    writer.doc("<remarks>")
    writer.doc("Separate same-type arguments bind to this overload as well; pass an array to")
    writer.doc("<see cref=\"WhenAll{T}(OnityTask{T}[])\"/> for a <c>T[]</c> result. Inputs that already")
    writer.doc("completed successfully are consumed without allocating. Otherwise a pooled native source")
    writer.doc("observes each input once, waits for all of them, and publishes the first fault in")
    writer.doc("argument order ahead of the first cancellation in argument order. An input that cannot be")
    writer.doc("observed, such as a stale pooled task, becomes that argument's fault. Publication runs on")
    writer.doc("the thread that completes the last input; the returned native task is single-consumer.")
    writer.doc("</remarks>")
    for i in positions(arity):
        writer.doc(f"<typeparam name=\"T{i}\">Result type of <paramref name=\"task{i}\"/>.</typeparam>")
    for i in positions(arity):
        writer.doc(f"<param name=\"task{i}\">{ORDINAL_WORDS[i]} input; its result is <c>Item{i}</c> of the "
                   "tuple.</param>")
    writer.doc("<returns>A task with every result in argument order.</returns>")
    writer.doc("<exception cref=\"ArgumentException\">")
    writer.doc("Two arguments refer to the same single-consumer native operation.")
    writer.doc("</exception>")
    write_generic_signature(writer, f"public static OnityTask<{tuple_type}> WhenAll", arity, task_parameters(arity))
    writer.open()
    writer.line("int singleConsumerInputs = OnityTaskComposition.CountSingleConsumer(task1)")
    writer.indented([f"+ OnityTaskComposition.CountSingleConsumer(task{i})" + (";" if i == arity else "")
                     for i in range(2, arity + 1)])
    writer.line("if (singleConsumerInputs < 2")
    writer.indented([f"&& OnityTaskComposition.IsCompletedSuccessfully(task{i})" + (")" if i == arity else "")
                     for i in positions(arity)])
    writer.open()
    writer.line(f"return OnityTask<{tuple_type}>.FromResult((")
    writer.indented(separated([f"task{i}.GetAwaiter().GetResult()" for i in positions(arity)], "));"))
    writer.close()
    writer.line()
    write_rent_call(writer, f"OnityWhenAllTuple<{type_parameters(arity)}>",
                    [f"task{i}" for i in positions(arity)] + ["singleConsumerInputs > 1"])
    writer.line(f"var output = new OnityTask<{tuple_type}>(source);")
    writer.line("source.Start();")
    writer.line("return output;")
    writer.close()


def write_when_all_source(writer, arity):
    tuple_type = result_tuple(arity)
    writer.doc(f"<summary>Holds the pooled source of <c>OnityTask.WhenAll</c> over {COUNT_WORDS[arity]} typed "
               "tasks.</summary>")
    writer.open(f"internal static class OnityWhenAllTuple<{type_parameters(arity)}>")
    writer.doc("<summary>Native single-consumer source of one pending output; reused after release.</summary>")
    writer.line("internal sealed class Source :")
    writer.indented([f"OnityWhenAllTupleTaskSourceBase<{tuple_type}>,", "IOnityPooledRunner<Source>"])
    writer.open()
    writer.line(f"private const int k_inputCount = {arity};")
    writer.line()
    writer.line("private static OnityRunnerPool<Source> s_pool;")
    writer.line()
    writer.line("private Source m_nextPooled;")
    for i in positions(arity):
        writer.line(f"private OnityTask<T{i}> m_task{i};")
    for i in positions(arity):
        writer.line(f"private T{i} m_result{i};")
    writer.line()
    writer.line("private Source() : base(k_inputCount)")
    writer.open()
    writer.close()
    writer.line()
    writer.line("ref Source IOnityPooledRunner<Source>.NextPooled => ref m_nextPooled;")
    writer.line()
    writer.line("internal static Source Rent(")
    writer.indented(separated(task_parameters(arity) + ["bool validateInputs"], ")"))
    writer.open()
    writer.line("// A contended rent allocates instead of waiting.")
    writer.open("if (!s_pool.TryPop(out Source source))")
    writer.line("source = new Source();")
    writer.close()
    writer.line()
    for i in positions(arity):
        writer.line(f"source.m_task{i} = task{i};")
    writer.open("if (validateInputs)")
    writer.line("int duplicate = OnityTaskComposition.FindDuplicateInput(source, k_inputCount);")
    writer.open("if (duplicate >= 0)")
    writer.line("source.ClearInputs();")
    writer.line("source.ReturnToPool();")
    writer.line("OnityTaskComposition.ThrowDuplicateInput(OnityTaskComposition.k_whenAll, duplicate);")
    writer.close()
    writer.close()
    writer.line()
    writer.line("source.Initialize();")
    writer.line("return source;")
    writer.close()
    writer.line()
    writer.line("public override bool TryGetInputIdentity(int index, out OnityWhenAnyInputIdentity identity)")
    writer.open()
    write_switch(writer, arity, lambda i: [f"return m_task{i}.TryGetWhenAnyIdentity(out identity);"])
    writer.close()
    writer.line()
    writer.line("protected override void RegisterInput(int index, Action callback)")
    writer.open()
    write_switch(writer, arity, lambda i: [f"m_task{i}.RegisterWhenAnyObserver(callback);", "return;"])
    writer.close()
    writer.line()
    writer.line("protected override OnityTaskSourceStatus ReadInput(")
    writer.indented(separated(["int index", "out Exception fault", "out CancellationToken cancellationToken"], ")"))
    writer.open()
    write_switch(writer, arity, lambda i: [
        f"return m_task{i}.ReadWhenAnyOutcome(out m_result{i}, out fault, out cancellationToken);"])
    writer.close()
    writer.line()
    writer.line(f"protected override {tuple_type} CreateResult()")
    writer.open()
    writer.line("return (")
    writer.indented(separated([f"m_result{i}" for i in positions(arity)], ");"))
    writer.close()
    writer.line()
    writer.line("protected override void ClearInput(int index)")
    writer.open()
    write_switch(writer, arity, lambda i: [f"m_task{i} = default;", "return;"])
    writer.close()
    writer.line()
    writer.line("protected override void ClearInputs()")
    writer.open()
    for i in positions(arity):
        writer.line(f"m_task{i} = default;")
    for i in positions(arity):
        writer.line(f"m_result{i} = default;")
    writer.close()
    writer.line()
    writer.line("protected override void ReturnToPool()")
    writer.open()
    writer.line("// A contended or full return lets the source be collected.")
    writer.line("s_pool.TryPush(this, OnityTaskSettings.s_sourcePoolCapacity);")
    writer.close()
    writer.close()
    writer.close()


def generate_when_all():
    writer = Writer()
    write_header(writer, ["System", "System.Threading"])
    writer.open("namespace Onity.Unity.Async")
    writer.open("public readonly partial struct OnityTask")
    for arity in arities():
        if arity > MIN_ARITY:
            writer.line()
        write_when_all_method(writer, arity)
    writer.close()
    for arity in arities():
        writer.line()
        write_when_all_source(writer, arity)
    writer.close()
    return writer.render()


# ----------------------------------------------------------------------------------------------
# Mixed WhenAny
# ----------------------------------------------------------------------------------------------

def when_any_elements(arity):
    return ["int winArgumentIndex"] + [f"T{i} result{i}" for i in positions(arity)]


def when_any_source_tuple(arity):
    return f"(int, {type_parameters(arity)})"


def write_when_any_signature(writer, arity):
    """Writes the public signature, splitting the named result tuple when it is long."""
    elements = when_any_elements(arity)
    one_line = (f"public static OnityTask<({', '.join(elements)})> WhenAny<{type_parameters(arity)}>(")
    if writer.fits(one_line):
        writer.line(one_line)
    else:
        writer.line("public static OnityTask<(")
        writer.indented(separated(elements[:-1], ","))
        writer.indented([f"{elements[-1]})> WhenAny<{type_parameters(arity)}>("])
    writer.indented(separated(task_parameters(arity), ")"))


def write_when_any_method(writer, arity):
    writer.doc("<summary>")
    writer.doc(f"Completes when the first of {COUNT_WORDS[arity]} typed tasks completes and returns its argument "
               "index and result.")
    writer.doc("The result types are independent; the other result elements keep their default values.")
    writer.doc("</summary>")
    writer.doc("<remarks>")
    writer.doc("Separate same-type arguments bind to this overload as well; pass an array to")
    writer.doc("<see cref=\"WhenAny{T}(OnityTask{T}[])\"/> for a <c>(winnerIndex, result)</c> pair. Every input")
    writer.doc("is observed: losers keep running, are not canceled, and are consumed when they complete.")
    writer.doc("Inputs register in argument order, so already completed inputs favor the lowest index, while")
    writer.doc("pending inputs race by observation. The winner's fault or cancellation is propagated instead")
    writer.doc("of a result, and an input that cannot be observed, such as a stale pooled task, becomes that")
    writer.doc("input's fault. Publication runs on the winning input's thread; the returned native task is")
    writer.doc("single-consumer and its source is pooled.")
    writer.doc("</remarks>")
    for i in positions(arity):
        writer.doc(f"<typeparam name=\"T{i}\">Result type of <paramref name=\"task{i}\"/>.</typeparam>")
    for i in positions(arity):
        writer.doc(f"<param name=\"task{i}\">{ORDINAL_WORDS[i]} input, at argument index {i - 1}; its result is "
                   f"<c>result{i}</c>.</param>")
    writer.doc("<returns>")
    writer.doc("A task with the zero-based argument index of the winner and the winner's result in its")
    writer.doc("<c>resultN</c> element.")
    writer.doc("</returns>")
    writer.doc("<exception cref=\"ArgumentException\">")
    writer.doc("Two arguments refer to the same single-consumer native operation.")
    writer.doc("</exception>")
    write_when_any_signature(writer, arity)
    writer.open()
    writer.line("int singleConsumerInputs = OnityTaskComposition.CountSingleConsumer(task1)")
    writer.indented([f"+ OnityTaskComposition.CountSingleConsumer(task{i})" + (";" if i == arity else "")
                     for i in range(2, arity + 1)])
    write_rent_call(writer, f"OnityWhenAnyTuple<{type_parameters(arity)}>",
                    [f"task{i}" for i in positions(arity)] + ["singleConsumerInputs > 1"])
    writer.line(f"var output = new OnityTask<{when_any_source_tuple(arity)}>(source);")
    writer.line("source.Start();")
    writer.line("return output;")
    writer.close()


def write_when_any_source(writer, arity):
    source_tuple = when_any_source_tuple(arity)
    writer.doc(f"<summary>Holds the pooled source of <c>OnityTask.WhenAny</c> over {COUNT_WORDS[arity]} typed "
               "tasks.</summary>")
    writer.open(f"internal static class OnityWhenAnyTuple<{type_parameters(arity)}>")
    writer.doc("<summary>")
    writer.doc("Native single-consumer source of one pending output on the array <c>WhenAny</c> base, which")
    writer.doc("picks the winner, keeps observing the losers and returns the source to its pool.")
    writer.doc("</summary>")
    writer.line("internal sealed class Source :")
    writer.indented([f"OnityWhenAnyArrayTaskSourceBase<{source_tuple}>,", "IOnityPooledRunner<Source>,",
                     "IOnityCompositionInputs"])
    writer.open()
    writer.line(f"private const int k_inputCount = {arity};")
    writer.line()
    writer.line("private static OnityRunnerPool<Source> s_pool;")
    writer.line()
    writer.line("private Source m_nextPooled;")
    for i in positions(arity):
        writer.line(f"private OnityTask<T{i}> m_task{i};")
    writer.line()
    writer.line("private Source() : base(k_inputCount)")
    writer.open()
    writer.close()
    writer.line()
    writer.line("ref Source IOnityPooledRunner<Source>.NextPooled => ref m_nextPooled;")
    writer.line()
    writer.line("internal static Source Rent(")
    writer.indented(separated(task_parameters(arity) + ["bool validateInputs"], ")"))
    writer.open()
    writer.line("// A contended rent allocates instead of waiting.")
    writer.open("if (!s_pool.TryPop(out Source source))")
    writer.line("source = new Source();")
    writer.close()
    writer.line()
    for i in positions(arity):
        writer.line(f"source.m_task{i} = task{i};")
    writer.open("if (validateInputs)")
    writer.line("int duplicate = OnityTaskComposition.FindDuplicateInput(source, k_inputCount);")
    writer.open("if (duplicate >= 0)")
    writer.line("source.ClearInputs(k_inputCount);")
    writer.line("source.ReturnToPool();")
    writer.line("OnityTaskComposition.ThrowDuplicateInput(OnityTaskComposition.k_whenAny, duplicate);")
    writer.close()
    writer.close()
    writer.line()
    writer.line("source.Initialize(k_inputCount);")
    writer.line("return source;")
    writer.close()
    writer.line()
    writer.line("public bool TryGetInputIdentity(int index, out OnityWhenAnyInputIdentity identity)")
    writer.open()
    write_switch(writer, arity, lambda i: [f"return m_task{i}.TryGetWhenAnyIdentity(out identity);"])
    writer.close()
    writer.line()
    writer.line("protected override void RegisterInput(int index, Action callback)")
    writer.open()
    write_switch(writer, arity, lambda i: [f"m_task{i}.RegisterWhenAnyObserver(callback);", "return;"])
    writer.close()
    writer.line()
    writer.line("protected override OnityTaskSourceStatus ReadOutcome(")
    writer.indented(separated(["int index", f"out {source_tuple} result", "out Exception fault",
                               "out CancellationToken cancellationToken"], ")"))
    writer.open()
    writer.line("result = default;")
    writer.line("result.Item1 = index;")
    write_switch(writer, arity, lambda i: [
        f"return m_task{i}.ReadWhenAnyOutcome(out result.Item{i + 1}, out fault, out cancellationToken);"])
    writer.close()
    writer.line()
    writer.line("protected override void ClearInput(int index)")
    writer.open()
    write_switch(writer, arity, lambda i: [f"m_task{i} = default;", "return;"])
    writer.close()
    writer.line()
    writer.line("protected override void ClearInputs(int count)")
    writer.open()
    for i in positions(arity):
        writer.line(f"m_task{i} = default;")
    writer.close()
    writer.line()
    writer.line("protected override void ReturnToPool()")
    writer.open()
    writer.line("// A contended or full return lets the source be collected.")
    writer.line("s_pool.TryPush(this, OnityTaskSettings.s_sourcePoolCapacity);")
    writer.close()
    writer.close()
    writer.close()


def generate_when_any():
    writer = Writer()
    write_header(writer, ["System", "System.Threading"])
    writer.open("namespace Onity.Unity.Async")
    writer.open("public readonly partial struct OnityTask")
    for arity in arities():
        if arity > MIN_ARITY:
            writer.line()
        write_when_any_method(writer, arity)
    writer.close()
    for arity in arities():
        writer.line()
        write_when_any_source(writer, arity)
    writer.close()
    return writer.render()


# ----------------------------------------------------------------------------------------------
# Tuple awaiters
# ----------------------------------------------------------------------------------------------

def write_typed_awaiter(writer, arity):
    writer.doc("<summary>")
    writer.doc(f"Awaits a tuple of {COUNT_WORDS[arity]} typed tasks and returns their results in tuple order,")
    write_cref_or_code(writer, "as ", when_all_cref(arity), "OnityTask.WhenAll", ".")
    writer.doc("</summary>")
    for i in positions(arity):
        writer.doc(f"<typeparam name=\"T{i}\">Result type of task {i}.</typeparam>")
    writer.doc("<param name=\"tasks\">Tasks to await. Each single-consumer task is consumed once.</param>")
    writer.doc("<returns>The awaiter of the combined task.</returns>")
    head = f"public static OnityTaskAwaiter<{result_tuple(arity)}> GetAwaiter"
    one_line = f"{head}<{type_parameters(arity)}>("
    if writer.fits(one_line):
        writer.line(one_line)
    else:
        writer.line(f"{head}<")
        writer.indented([f"{type_parameters(arity)}>("])
    write_tuple_parameter(writer, task_parameters(arity), "tasks")
    writer.open()
    writer.line("return OnityTask.WhenAll(")
    writer.indented(separated([f"tasks.Item{i}" for i in positions(arity)], ").GetAwaiter();"))
    writer.close()


def write_untyped_awaiter(writer, arity):
    target = "OnityTask.WhenAll(OnityTask, OnityTask)" if arity == MIN_ARITY else "OnityTask.WhenAll(OnityTask[])"
    writer.doc("<summary>")
    writer.doc(f"Awaits a tuple of {COUNT_WORDS[arity]} untyped tasks, as <see cref=\"{target}\"/>.")
    writer.doc("</summary>")
    writer.doc("<param name=\"tasks\">Tasks to await. Each single-consumer task is consumed once.</param>")
    writer.doc("<returns>The awaiter of the combined task.</returns>")
    writer.line("public static OnityTaskAwaiter GetAwaiter(")
    write_tuple_parameter(writer, [f"OnityTask task{i}" for i in positions(arity)], "tasks")
    writer.open()
    writer.line("return OnityTask.WhenAll(")
    writer.indented(separated([f"tasks.Item{i}" for i in positions(arity)], ").GetAwaiter();"))
    writer.close()


def generate_awaiters():
    writer = Writer()
    write_header(writer, [])
    writer.open("namespace Onity.Unity.Async")
    writer.open("public static partial class OnityTaskCompositionAwaitExtensions")
    for arity in arities():
        if arity > MIN_ARITY:
            writer.line()
        write_typed_awaiter(writer, arity)
    for arity in arities():
        writer.line()
        write_untyped_awaiter(writer, arity)
    writer.close()
    writer.close()
    return writer.render()


# ----------------------------------------------------------------------------------------------
# Entry point
# ----------------------------------------------------------------------------------------------

OUTPUTS = {
    "OnityTask.WhenAll.Generated.cs": generate_when_all,
    "OnityTask.WhenAny.Generated.cs": generate_when_any,
    "OnityTaskCompositionAwaitExtensions.Generated.cs": generate_awaiters,
}


def normalize(text):
    return text.replace("\r\n", "\n")


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="Report stale or missing generated files without writing; exit 1 if any.")
    arguments = parser.parse_args(argv)

    problems = []
    for name, generate in OUTPUTS.items():
        path = ASYNC_FOLDER / name
        relative = path.relative_to(REPOSITORY_ROOT).as_posix()
        expected = generate()
        current = normalize(path.read_text(encoding="utf-8")) if path.exists() else None
        if current != expected:
            if arguments.check:
                problems.append(f"stale: {relative}")
            else:
                path.write_text(expected, encoding="utf-8", newline="\n")
                print(f"wrote {relative}")
        if not path.with_name(path.name + ".meta").exists():
            problems.append(f"missing: {relative}.meta (create it once with a fresh GUID)")

    for problem in problems:
        print(problem)
    if arguments.check:
        if problems:
            return 1
        print("generated files are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
