#!/usr/bin/env python3
"""Generates the CombineLatest operators of OnityAsyncEnumerableLinq for 2 to 15 sources.

Each arity gets a public extension method, a lazy description and an enumerator that only knows how
to call the result selector with the latest item of every source. The shared policy lives in the
hand-written OnityCombineLatestEnumerator (OnityAsyncEnumerableOperators.CombineLatest.cs) and the
coordination in OnityMultiSourceAsyncEnumerator.

Usage:
    python generate_onity_async_combinelatest.py            # rewrite the generated file
    python generate_onity_async_combinelatest.py --check    # exit 1 when the file is stale
"""

import argparse
import os
import sys

MIN_ARITY = 2
MAX_ARITY = 15

DEFAULT_OUTPUT = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "Packages", "com.onity.framework",
    "Runtime", "Unity", "Scripts", "Async", "OnityAsyncEnumerableOperators.CombineLatest.Generated.cs"))

HEADER = """// <auto-generated>
// Generated by tools/codegen/generate_onity_async_combinelatest.py. Do not edit by hand;
// change the generator and rerun it.
// </auto-generated>
using System;
using System.Threading;

namespace Onity.Unity.Async
{
"""

FOOTER = """}
"""

REMARKS = [
    "Each move moves every source that has no outstanding move and has not ended. Until every",
    "source has produced an item, a source that produced one is moved again at once, so only its",
    "latest item counts. Afterwards every arriving item yields exactly one result, computed at",
    "arrival from the latest item of every source and relayed in arrival order; a source is moved",
    "again only by a later move. The stream ends when every source has ended, or as soon as a source",
    "ends without ever producing an item. The first fault or cancellation is relayed after earlier",
    "results; a selector exception, including OperationCanceledException, is a fault. Every source is",
    "acquired at the first move with the enumeration token and disposed exactly once, in argument",
    "order, before the end or fault is published. A source that keeps completing synchronously while",
    "another has not produced its first item is pulled without yielding. Unlike UniTask, results",
    "that arrive between moves are queued instead of overwriting the current one, and a source that",
    "ends empty ends the stream.",
]


LINE_LIMIT = 110


def call(out, head, items, tail, indent):
    """Appends `head + items + tail`, wrapping one item per line when the line would be too long."""
    line = indent + head + ", ".join(items) + tail
    if len(line) <= LINE_LIMIT:
        out.append(line)
        return
    out.append(indent + head.rstrip())
    inner = indent + "    "
    for index, item in enumerate(items):
        out.append(inner + item + ("," if index < len(items) - 1 else tail))


def type_list(arity):
    return ", ".join("T{}".format(i) for i in range(1, arity + 1))


def type_args(arity):
    return type_list(arity) + ", TResult"


def selector_type(arity):
    return "Func<{}>".format(type_args(arity))


def emit_method(out, arity):
    args = type_args(arity)
    out.append("        /// <summary>Combines the latest items of {} sources each time one of them yields.</summary>".format(arity))
    for i in range(1, arity + 1):
        out.append("        /// <typeparam name=\"T{0}\">Item type of source {0}.</typeparam>".format(i))
    out.append("        /// <typeparam name=\"TResult\">Result type.</typeparam>")
    for i in range(1, arity + 1):
        out.append("        /// <param name=\"source{0}\">Source {0}.</param>".format(i))
    out.append("        /// <param name=\"resultSelector\">Selector invoked outside lifecycle locks with the latest item of every source.</param>")
    out.append("        /// <returns>A lazy description with independent enumerations.</returns>")
    out.append("        /// <remarks>")
    for line in REMARKS:
        out.append("        /// " + line)
    out.append("        /// </remarks>")
    out.append("        /// <exception cref=\"ArgumentNullException\">A source or the selector is null.</exception>")
    parameters = ["this IOnityAsyncEnumerable<T1> source1"]
    parameters += ["IOnityAsyncEnumerable<T{0}> source{0}".format(i) for i in range(2, arity + 1)]
    parameters.append("{} resultSelector".format(selector_type(arity)))
    out.append("        public static IOnityAsyncEnumerable<TResult> CombineLatest<{}>(".format(args))
    for index, parameter in enumerate(parameters):
        out.append("            " + parameter + ("," if index < len(parameters) - 1 else ")"))
    out.append("        {")
    for i in range(1, arity + 1):
        out.append("            OnityLinqCore.NotNull(source{0}, nameof(source{0}));".format(i))
    out.append("            OnityLinqCore.NotNull(resultSelector, nameof(resultSelector));")
    names = ["source{}".format(i) for i in range(1, arity + 1)] + ["resultSelector"]
    call(out, "return new OnityCombineLatestAsyncEnumerable<{}>(".format(args), names, ");", "            ")
    out.append("        }")
    out.append("")


def emit_types(out, arity):
    args = type_args(arity)
    out.append("    internal sealed class OnityCombineLatestAsyncEnumerable<{}> : IOnityAsyncEnumerable<TResult>".format(args))
    out.append("    {")
    for i in range(1, arity + 1):
        out.append("        private readonly IOnityAsyncEnumerable<T{0}> m_source{0};".format(i))
    out.append("        private readonly {} m_resultSelector;".format(selector_type(arity)))
    out.append("")
    ctor_parameters = ["IOnityAsyncEnumerable<T{0}> source{0}".format(i) for i in range(1, arity + 1)]
    ctor_parameters.append("{} resultSelector".format(selector_type(arity)))
    call(out, "internal OnityCombineLatestAsyncEnumerable(", ctor_parameters, ")", "        ")
    out.append("        {")
    for i in range(1, arity + 1):
        out.append("            m_source{0} = source{0};".format(i))
    out.append("            m_resultSelector = resultSelector;")
    out.append("        }")
    out.append("")
    out.append("        public IOnityAsyncEnumerator<TResult> GetAsyncEnumerator(CancellationToken cancellationToken = default)")
    out.append("        {")
    slots = ["new OnityStreamSlot<T{0}>(m_source{0})".format(i) for i in range(1, arity + 1)]
    call(out, "return new Enumerator(", slots + ["m_resultSelector", "cancellationToken"], ");", "            ")
    out.append("        }")
    out.append("")
    out.append("        private sealed class Enumerator : OnityCombineLatestEnumerator<TResult>")
    out.append("        {")
    for i in range(1, arity + 1):
        out.append("            private readonly OnityStreamSlot<T{0}> m_slot{0};".format(i))
    out.append("            private readonly {} m_resultSelector;".format(selector_type(arity)))
    out.append("")
    slot_parameters = ["OnityStreamSlot<T{0}> slot{0}".format(i) for i in range(1, arity + 1)]
    slot_parameters += ["{} resultSelector".format(selector_type(arity)), "CancellationToken token"]
    call(out, "internal Enumerator(", slot_parameters, ")", "            ")
    slot_names = ["slot{}".format(i) for i in range(1, arity + 1)]
    call(out, ": base(new OnityStreamSlot[] { ", slot_names, " }, token)", "                ")
    out.append("            {")
    for i in range(1, arity + 1):
        out.append("                m_slot{0} = slot{0};".format(i))
    out.append("                m_resultSelector = resultSelector;")
    out.append("            }")
    out.append("")
    values = ["m_slot{}.Value".format(i) for i in range(1, arity + 1)]
    call(out, "protected override TResult Combine() => m_resultSelector(", values, ");", "            ")
    out.append("        }")
    out.append("    }")
    out.append("")


def generate():
    out = [HEADER.rstrip("\n")]
    for arity in range(MIN_ARITY, MAX_ARITY + 1):
        emit_types(out, arity)
    out.append("    public static partial class OnityAsyncEnumerableLinq")
    out.append("    {")
    for arity in range(MIN_ARITY, MAX_ARITY + 1):
        emit_method(out, arity)
    if out[-1] == "":
        out.pop()
    out.append("    }")
    out.append(FOOTER.rstrip("\n"))
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    if args.check:
        try:
            with open(args.output, "r", encoding="utf-8", newline="") as handle:
                current = handle.read().replace("\r\n", "\n")
        except FileNotFoundError:
            current = ""
        if current != text:
            print("STALE: " + args.output)
            return 1
        print("UP_TO_DATE: " + args.output)
        return 0
    with open(args.output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print("WROTE: {} ({} lines)".format(args.output, text.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
