#!/usr/bin/env python3
"""Generates the numeric Sum/Average/Min/Max operators of OnityAsyncEnumerableLinq.

Mirrors the type matrix of UniTask 2.5.11 (Sum.tt, Average.tt, MinMax.tt): int, long, float,
double, decimal and their nullable forms, each with the selector-less, selector, Await and
AwaitWithCancellation overloads.

Usage:
    python generate_numeric_aggregates.py            # rewrite the generated file
    python generate_numeric_aggregates.py --check    # exit 1 when the file is stale

Semantics deliberately matching System.Linq where UniTask's template is accidentally wrong:
  * nullable Sum starts at zero (UniTask starts at null, so its nullable Sum is always null);
  * Average of an empty stream faults with InvalidOperationException for non-nullable types and
    yields null for nullable types (UniTask divides by zero: NaN or DivideByZeroException);
  * integer Average accumulates in long, float Average in double (UniTask overflows at int range).
"""

import argparse
import os
import sys

# (display name used in method names, C# type keyword, accumulator type for Average, result type for Average)
TYPES = [
    ("Int32", "int", "long", "double"),
    ("Int64", "long", "long", "double"),
    ("Single", "float", "double", "float"),
    ("Double", "double", "double", "double"),
    ("Decimal", "decimal", "decimal", "decimal"),
]

DEFAULT_OUTPUT = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "Packages", "com.onity.framework",
    "Runtime", "Unity", "Scripts", "Async", "OnityAsyncEnumerableOperators.Aggregates.Generated.cs"))

HEADER = """// <auto-generated>
// Generated by tools/async-linq-codegen/generate_numeric_aggregates.py. Do not edit by hand;
// change the generator and rerun it.
// </auto-generated>
using System;
using System.Threading;

namespace Onity.Unity.Async
{
    public static partial class OnityAsyncEnumerableLinq
    {
"""

FOOTER = """    }
}
"""

VARIANTS = [
    # (method suffix, selector parameter template, selector description, factory)
    ("", "Func<TSource, {t}> selector", "Selector invoked sequentially.", "FromSync"),
    ("Await", "Func<TSource, OnityTask<{t}>> selector", "Selector awaited sequentially.", "FromAwait"),
    ("AwaitWithCancellation", "Func<TSource, CancellationToken, OnityTask<{t}>> selector",
     "Selector awaited sequentially with the enumeration token.", "FromCancel"),
]


def type_pairs():
    for name, keyword, accumulator, average in TYPES:
        yield name, keyword, accumulator, average, False
    for name, keyword, accumulator, average in TYPES:
        yield "Nullable" + name, keyword + "?", accumulator, average + "?", True


def result_type(op, t, average, nullable):
    return average if op == "Average" else t


def emit_public(out, op, name, t, average, nullable):
    r = result_type(op, t, average, nullable)
    core = "{}{}Core".format(op, name)
    verb = {"Sum": "Sums", "Average": "Averages", "Min": "Finds the smallest of", "Max": "Finds the largest of"}[op]
    if op in ("Min", "Max"):
        what = "the values" if not nullable else "the non-null values"
    else:
        what = "the values" if not nullable else "the non-null values"
    empty = {
        "Sum": "An empty stream yields zero.",
        "Average": ("An empty stream or one without values yields null." if nullable
                    else "An empty stream faults with InvalidOperationException."),
        "Min": ("An empty stream or one without values yields null." if nullable
                else "An empty stream faults with InvalidOperationException."),
        "Max": ("An empty stream or one without values yields null." if nullable
                else "An empty stream faults with InvalidOperationException."),
    }[op]
    # selector-less overload
    out.append("""        /// <summary>{verb} {what} of a stream of {t} values.</summary>
        /// <param name="source">Upstream description.</param>
        /// <param name="cancellationToken">Cooperative enumeration token.</param>
        /// <returns>The result. {empty} Cleanup runs on every exit and its failure takes precedence.</returns>
        /// <exception cref="ArgumentNullException">Source is null.</exception>
        public static OnityTask<{r}> {op}Async(
            this IOnityAsyncEnumerable<{t}> source, CancellationToken cancellationToken = default)
        {{
            OnityLinqCore.NotNull(source, nameof(source));
            return {core}(source, OnityLinqFunc<{t}, {t}>.FromSync(OnityLinqIdentity<{t}>.Instance), cancellationToken);
        }}

""".format(verb=verb, what=what, t=t, r=r, op=op, core=core, empty=empty))
    for suffix, parameter, description, factory in VARIANTS:
        flavor = {"": "a synchronous selector", "Await": "an asynchronous selector",
                  "AwaitWithCancellation": "an asynchronous token-aware selector"}[suffix]
        out.append("""        /// <summary>{verb} {what} produced by {flavor} for each item.</summary>
        /// <typeparam name="TSource">Item type.</typeparam>
        /// <param name="source">Upstream description.</param>
        /// <param name="selector">{description}</param>
        /// <param name="cancellationToken">Cooperative enumeration token.</param>
        /// <returns>The result. {empty} Cleanup runs on every exit and its failure takes precedence.</returns>
        /// <exception cref="ArgumentNullException">Source or selector is null.</exception>
        public static OnityTask<{r}> {op}{suffix}Async<TSource>(
            this IOnityAsyncEnumerable<TSource> source, {parameter},
            CancellationToken cancellationToken = default)
        {{
            OnityLinqCore.NotNull(source, nameof(source));
            OnityLinqCore.NotNull(selector, nameof(selector));
            return {core}(source, OnityLinqFunc<TSource, {t}>.{factory}(selector), cancellationToken);
        }}

""".format(verb=verb, flavor=flavor, what=what, description=description, t=t, r=r, op=op,
           suffix=suffix, parameter=parameter.format(t=t), core=core, factory=factory, empty=empty))


def emit_core(out, op, name, t, accumulator, average, nullable):
    base = t[:-1] if nullable else t
    core = "{}{}Core".format(op, name)
    r = result_type(op, t, average, nullable)
    head = """        private static async OnityTask<{r}> {core}<TSource>(IOnityAsyncEnumerable<TSource> source,
            OnityLinqFunc<TSource, {t}> selector, CancellationToken cancellationToken)
        {{
            IOnityAsyncEnumerator<TSource> enumerator = OnityLinqCore.Acquire(source, cancellationToken);
            try
            {{
""".format(r=r, core=core, t=t)
    tail = """            }
            finally
            {
                await enumerator.DisposeAsync();
            }
        }

"""
    if op == "Sum":
        body = ["                {b} sum = 0;".format(b=base),
                "                while (await enumerator.MoveNextAsync())",
                "                {",
                "                    {t} value = await selector.Invoke(enumerator.Current, cancellationToken);".format(t=t),
                "                    checked",
                "                    {",
                "                        sum += value{s};".format(s=".GetValueOrDefault()" if nullable else ""),
                "                    }",
                "                }",
                "                return sum;"]
    elif op == "Average":
        body = ["                long count = 0;",
                "                {a} sum = 0;".format(a=accumulator),
                "                while (await enumerator.MoveNextAsync())",
                "                {",
                "                    {t} value = await selector.Invoke(enumerator.Current, cancellationToken);".format(t=t)]
        if nullable:
            body += ["                    if (!value.HasValue)",
                     "                    {",
                     "                        continue;",
                     "                    }",
                     ""]
        body += ["                    checked",
                 "                    {",
                 "                        sum += value{s};".format(s=".Value" if nullable else ""),
                 "                        count++;",
                 "                    }",
                 "                }",
                 "                if (count == 0)",
                 "                {"]
        body += (["                    return null;"] if nullable else ["                    throw OnityLinqCore.NoElements();"])
        body += ["                }"]
        if base in ("int", "long"):
            calc = "(double)sum / count"
        elif base == "float":
            calc = "(float)(sum / count)"
        else:
            calc = "sum / count"
        body += ["                return {c};".format(c=calc)]
    else:
        comparison = ">" if op == "Min" else "<"
        body = ["                {b} result = default;".format(b=base),
                "                bool hasValue = false;",
                "                while (await enumerator.MoveNextAsync())",
                "                {",
                "                    {t} value = await selector.Invoke(enumerator.Current, cancellationToken);".format(t=t)]
        if nullable:
            body += ["                    if (!value.HasValue)",
                     "                    {",
                     "                        continue;",
                     "                    }",
                     ""]
        candidate = "value.Value" if nullable else "value"
        body += ["                    {c_t} candidate = {c};".format(c_t=base, c=candidate),
                 "                    if (!hasValue || result {op} candidate)".format(op=comparison),
                 "                    {",
                 "                        result = candidate;",
                 "                        hasValue = true;",
                 "                    }",
                 "                }",
                 "                if (!hasValue)",
                 "                {"]
        body += (["                    return null;"] if nullable else ["                    throw OnityLinqCore.NoElements();"])
        body += ["                }", "                return result;"]
    out.append(head + "\n".join(body) + "\n" + tail)


def generate():
    out = [HEADER]
    for op in ("Sum", "Average", "Min", "Max"):
        for name, t, accumulator, average, nullable in type_pairs():
            emit_public(out, op, name, t, average, nullable)
            emit_core(out, op, name, t, accumulator, average, nullable)
    text = "".join(out)
    # Drop the blank line left before the closing brace and close the class and namespace.
    text = text.rstrip("\n") + "\n" + FOOTER
    return text


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    if args.check:
        try:
            with open(args.output, "r", encoding="utf-8", newline="") as handle:
                current = handle.read().replace("\r\n", "\n")
        except FileNotFoundError:
            current = ""
        if current != text:
            print("STALE: " + args.output)
            return 1
        print("UP_TO_DATE: " + args.output)
        return 0
    with open(args.output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print("WROTE: {} ({} lines)".format(args.output, text.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
