#!/usr/bin/env python3
"""Generates the Subscribe and SubscribeAwait overloads of OnityAsyncEnumerableExtensions.

Mirrors the 16 Subscribe and 12 SubscribeAwait overloads of UniTask 2.5.11 (Subscribe.cs), with Onity types:
UniTaskVoid becomes OnityTaskVoid, UniTask becomes OnityTask, and the BCL IObserver shape is kept.

Usage:
    python generate_subscribe_overloads.py            # rewrite the generated file
    python generate_subscribe_overloads.py --check    # exit 1 when the file is stale

Shapes (handler x optional tail x lifetime):
  Subscribe       Action<T>, Func<T, OnityTaskVoid>, Func<T, CancellationToken, OnityTaskVoid>   (tail: none)
                  Action<T>, Func<T, OnityTaskVoid>                                              (tail: onError | onCompleted)
                  IObserver<T>
  SubscribeAwait  Func<T, OnityTask>, Func<T, CancellationToken, OnityTask>                       (tail: none | onError | onCompleted)
  Lifetime        returns an IDisposable that cancels the subscription, or takes a CancellationToken and returns void.
"""

import argparse
import os
import sys

DEFAULT_OUTPUT = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "Packages", "com.onity.framework",
    "Runtime", "Unity", "Scripts", "Async", "OnityAsyncEnumerableExtensions.Subscribe.Generated.cs"))

HEADER = """// <auto-generated>
// Generated by tools/async-linq-codegen/generate_subscribe_overloads.py. Do not edit by hand;
// change the generator and rerun it.
// </auto-generated>
using System;
using System.Threading;

namespace Onity.Unity.Async
{
    public static partial class OnityAsyncEnumerableExtensions
    {
"""

FOOTER = """    }
}
"""

INDENT = "        "
DOC_WIDTH = 112

# key -> (parameter type, factory, summary clause, parameter description, awaited)
HANDLERS = {
    "Action": ("Action<T>", "FromAction", "invokes an action for each item",
               "Action invoked synchronously for each item.", False),
    "Void": ("Func<T, OnityTaskVoid>", "FromVoid", "starts a fire-and-forget async handler for each item",
             "Handler started for each item without being awaited, so handlers may overlap.", False),
    "VoidToken": ("Func<T, CancellationToken, OnityTaskVoid>", "FromVoidWithToken",
                  "starts a fire-and-forget async handler that receives the subscription token for each item",
                  "Handler started for each item without being awaited; it receives the subscription token.", False),
    "Await": ("Func<T, OnityTask>", "FromAwait", "awaits an async handler for each item",
              "Handler awaited before the next item is requested.", True),
    "AwaitToken": ("Func<T, CancellationToken, OnityTask>", "FromAwaitWithToken",
                   "awaits an async handler that receives the subscription token for each item",
                   "Handler awaited before the next item is requested; it receives the subscription token.", True),
}

TAILS = {
    "": ("", ""),
    "onError": (" and reports failures to a callback", "Receives a stream failure other than cancellation."),
    "onCompleted": (" and reports normal completion to a callback",
                    "Invoked once after normal completion and upstream cleanup."),
}

COMMON_REMARKS = (
    "The enumeration starts synchronously on the calling thread and continues wherever the stream completes its "
    "moves; no thread or context hop is added, so a synchronous stream is consumed before this call returns. "
    "{handler_remark}Cancellation ends the subscription silently; any other stream failure goes to onError, or is "
    "reported as an unobserved exception when no onError was supplied. Upstream cleanup is awaited before onCompleted "
    "or onError runs, and a cleanup failure replaces the normal completion.")

HANDLER_REMARKS = {
    False: "A handler that throws is reported as an unobserved exception (OperationCanceledException is ignored) "
           "and the next item is still delivered. ",
    True: "A handler that throws or faults is reported as an unobserved exception (OperationCanceledException is "
          "ignored) and the next item is still delivered. ",
}

TOKEN_DOC = ("Token that stops the subscription cooperatively; it is also the token the stream is enumerated with.")
DISPOSABLE_DOC = ("A disposable that cancels the subscription token and so stops the stream cooperatively; "
                  "disposing it after the subscription ended does nothing.")


def pack_words(text, first_prefix, next_prefix, width=DOC_WIDTH):
    """Greedy word wrap; the first line starts with first_prefix, continuation lines with next_prefix."""
    lines, current = [], first_prefix
    for word in text.split(" "):
        candidate = current + ("" if current in (first_prefix, next_prefix) else " ") + word
        if len(candidate) > width and current not in (first_prefix, next_prefix):
            lines.append(current)
            current = next_prefix + word
        else:
            current = candidate
    lines.append(current)
    return lines


def tag(name, text, attribute=None):
    """A documentation element wrapped over as many /// lines as needed."""
    open_tag = "<{} {}>".format(name, attribute) if attribute else "<{}>".format(name)
    full = open_tag + text + "</{}>".format(name)
    return pack_words(full, INDENT + "/// ", INDENT + "/// ")


def remarks(handler_remark):
    body = pack_words(COMMON_REMARKS.format(handler_remark=handler_remark), INDENT + "/// ", INDENT + "/// ")
    return [INDENT + "/// <remarks>"] + body + [INDENT + "/// </remarks>"]


def doc_block(summary, params, extra, handler_remark, exception_text):
    lines = tag("summary", summary)
    lines += tag("typeparam", "Item type.", "name=\"T\"")
    lines += tag("param", "Reusable upstream description.", "name=\"source\"")
    for name, text in params:
        lines += tag("param", text, "name=\"{}\"".format(name))
    for kind, text in extra:
        lines += tag(kind, text)
    lines += remarks(handler_remark)
    lines += tag("exception", exception_text, "cref=\"ArgumentNullException\"")
    return "".join(line + "\n" for line in lines)


def signature(return_type, name, parameters, width=116):
    """Packs the parameters greedily onto continuation lines indented by four extra spaces."""
    head = "{}public static {} {}<T>(".format(INDENT, return_type, name)
    continuation = INDENT + "    "
    items = ["this IOnityAsyncEnumerable<T> source"] + parameters
    lines, current = [], head
    for index, item in enumerate(items):
        piece = item + ("," if index < len(items) - 1 else ")")
        at_start = current in (head, continuation)
        candidate = current + ("" if at_start else " ") + piece
        if len(candidate) > width and not at_start:
            lines.append(current)
            current = continuation + piece
        else:
            current = candidate
    lines.append(current)
    return "\n".join(lines) + "\n"


def emit(out, name, handler_key, tail_key, lifetime):
    """lifetime: 'disposable' or 'token'."""
    param_type, factory, clause, param_doc, awaited = HANDLERS[handler_key]
    tail_clause, tail_doc = TAILS[tail_key]
    parameters = [param_type + " onNext"]
    params = [("onNext", param_doc)]
    if tail_key == "onError":
        parameters.append("Action<Exception> onError")
        params.append(("onError", tail_doc))
    elif tail_key == "onCompleted":
        parameters.append("Action onCompleted")
        params.append(("onCompleted", tail_doc))
    extra = []
    if lifetime == "token":
        parameters.append("CancellationToken cancellationToken")
        params.append(("cancellationToken", TOKEN_DOC))
        return_type = "void"
    else:
        extra.append(("returns", DISPOSABLE_DOC))
        return_type = "IDisposable"
    summary = "Subscribes to the stream and " + clause + tail_clause + "."
    out.append(doc_block(summary, params, extra, HANDLER_REMARKS[awaited], "Source or a callback is null."))
    out.append(signature(return_type, name, parameters))
    out.append("        {\n")
    out.append("            OnityLinqCore.NotNull(source, nameof(source));\n")
    out.append("            OnityLinqCore.NotNull(onNext, nameof(onNext));\n")
    if tail_key:
        out.append("            OnityLinqCore.NotNull({0}, nameof({0}));\n".format(tail_key))
    on_error = "onError" if tail_key == "onError" else "null"
    on_completed = "onCompleted" if tail_key == "onCompleted" else "null"
    out.append("            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.{}(onNext);\n".format(factory))
    if lifetime == "token":
        out.append("            OnityAsyncSubscribeCore.Start(source, handler, {}, {}, cancellationToken);\n".format(
            on_error, on_completed))
    else:
        out.append("            return OnityAsyncSubscribeCore.Start(source, handler, {}, {});\n".format(
            on_error, on_completed))
    out.append("        }\n\n")


def emit_observer(out, lifetime):
    parameters = ["IObserver<T> observer"]
    params = [("observer", "Receives OnNext for each item, OnError for a failure other than cancellation and "
                           "OnCompleted after normal completion and upstream cleanup.")]
    extra = []
    if lifetime == "token":
        parameters.append("CancellationToken cancellationToken")
        params.append(("cancellationToken", TOKEN_DOC))
        return_type = "void"
    else:
        extra.append(("returns", DISPOSABLE_DOC))
        return_type = "IDisposable"
    summary = "Subscribes to the stream and forwards items, failure and completion to an observer."
    out.append(doc_block(summary, params, extra, HANDLER_REMARKS[False], "Source or observer is null."))
    out.append(signature(return_type, "Subscribe", parameters))
    out.append("        {\n")
    out.append("            OnityLinqCore.NotNull(source, nameof(source));\n")
    out.append("            OnityLinqCore.NotNull(observer, nameof(observer));\n")
    out.append("            OnitySubscribeHandler<T> handler = OnitySubscribeHandler<T>.FromAction(observer.OnNext);\n")
    if lifetime == "token":
        out.append("            OnityAsyncSubscribeCore.Start(\n"
                   "                source, handler, observer.OnError, observer.OnCompleted, cancellationToken);\n")
    else:
        out.append("            return OnityAsyncSubscribeCore.Start(\n"
                   "                source, handler, observer.OnError, observer.OnCompleted);\n")
    out.append("        }\n\n")


def generate():
    out = [HEADER]
    for tail_key, handlers in (("", ("Action", "Void", "VoidToken")), ("onError", ("Action", "Void")),
                               ("onCompleted", ("Action", "Void"))):
        for handler_key in handlers:
            for lifetime in ("disposable", "token"):
                emit(out, "Subscribe", handler_key, tail_key, lifetime)
    for lifetime in ("disposable", "token"):
        emit_observer(out, lifetime)
    for tail_key in ("", "onError", "onCompleted"):
        for handler_key in ("Await", "AwaitToken"):
            for lifetime in ("disposable", "token"):
                emit(out, "SubscribeAwait", handler_key, tail_key, lifetime)
    text = "".join(out)
    text = text.rstrip("\n") + "\n" + FOOTER
    return text


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    if args.check:
        try:
            with open(args.output, "r", encoding="utf-8", newline="") as handle:
                current = handle.read().replace("\r\n", "\n")
        except FileNotFoundError:
            current = ""
        if current != text:
            print("STALE: " + args.output)
            return 1
        print("UP_TO_DATE: " + args.output)
        return 0
    with open(args.output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print("WROTE: {} ({} lines)".format(args.output, text.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
