// <auto-generated>
// Generated by tools/codegen/generate_onitytask_composition.py; do not edit by hand.
// Regenerate with: python tools/codegen/generate_onitytask_composition.py
// Verify with: python tools/codegen/generate_onitytask_composition.py --check
// </auto-generated>

namespace Onity.Unity.Async
{
    public static partial class OnityTaskCompositionAwaitExtensions
    {
        /// <summary>
        /// Awaits a tuple of two typed tasks and returns their results in tuple order,
        /// as <see cref="OnityTask.WhenAll{T1, T2}(OnityTask{T1}, OnityTask{T2})"/>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2)> GetAwaiter<T1, T2>(
            this (OnityTask<T1> task1, OnityTask<T2> task2) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of three typed tasks and returns their results in tuple order,
        /// as <see cref="OnityTask.WhenAll{T1, T2, T3}(OnityTask{T1}, OnityTask{T2}, OnityTask{T3})"/>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3)> GetAwaiter<T1, T2, T3>(
            this (OnityTask<T1> task1, OnityTask<T2> task2, OnityTask<T3> task3) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of four typed tasks and returns their results in tuple order,
        /// as <c>OnityTask.WhenAll</c>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <typeparam name="T4">Result type of task 4.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3, T4)> GetAwaiter<T1, T2, T3, T4>(
            this (OnityTask<T1> task1, OnityTask<T2> task2, OnityTask<T3> task3, OnityTask<T4> task4) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of five typed tasks and returns their results in tuple order,
        /// as <c>OnityTask.WhenAll</c>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <typeparam name="T4">Result type of task 4.</typeparam>
        /// <typeparam name="T5">Result type of task 5.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3, T4, T5)> GetAwaiter<T1, T2, T3, T4, T5>(
            this (
                OnityTask<T1> task1,
                OnityTask<T2> task2,
                OnityTask<T3> task3,
                OnityTask<T4> task4,
                OnityTask<T5> task5) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of six typed tasks and returns their results in tuple order,
        /// as <c>OnityTask.WhenAll</c>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <typeparam name="T4">Result type of task 4.</typeparam>
        /// <typeparam name="T5">Result type of task 5.</typeparam>
        /// <typeparam name="T6">Result type of task 6.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3, T4, T5, T6)> GetAwaiter<T1, T2, T3, T4, T5, T6>(
            this (
                OnityTask<T1> task1,
                OnityTask<T2> task2,
                OnityTask<T3> task3,
                OnityTask<T4> task4,
                OnityTask<T5> task5,
                OnityTask<T6> task6) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of seven typed tasks and returns their results in tuple order,
        /// as <c>OnityTask.WhenAll</c>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <typeparam name="T4">Result type of task 4.</typeparam>
        /// <typeparam name="T5">Result type of task 5.</typeparam>
        /// <typeparam name="T6">Result type of task 6.</typeparam>
        /// <typeparam name="T7">Result type of task 7.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3, T4, T5, T6, T7)> GetAwaiter<T1, T2, T3, T4, T5, T6, T7>(
            this (
                OnityTask<T1> task1,
                OnityTask<T2> task2,
                OnityTask<T3> task3,
                OnityTask<T4> task4,
                OnityTask<T5> task5,
                OnityTask<T6> task6,
                OnityTask<T7> task7) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of eight typed tasks and returns their results in tuple order,
        /// as <c>OnityTask.WhenAll</c>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <typeparam name="T4">Result type of task 4.</typeparam>
        /// <typeparam name="T5">Result type of task 5.</typeparam>
        /// <typeparam name="T6">Result type of task 6.</typeparam>
        /// <typeparam name="T7">Result type of task 7.</typeparam>
        /// <typeparam name="T8">Result type of task 8.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3, T4, T5, T6, T7, T8)> GetAwaiter<T1, T2, T3, T4, T5, T6, T7, T8>(
            this (
                OnityTask<T1> task1,
                OnityTask<T2> task2,
                OnityTask<T3> task3,
                OnityTask<T4> task4,
                OnityTask<T5> task5,
                OnityTask<T6> task6,
                OnityTask<T7> task7,
                OnityTask<T8> task8) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of nine typed tasks and returns their results in tuple order,
        /// as <c>OnityTask.WhenAll</c>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <typeparam name="T4">Result type of task 4.</typeparam>
        /// <typeparam name="T5">Result type of task 5.</typeparam>
        /// <typeparam name="T6">Result type of task 6.</typeparam>
        /// <typeparam name="T7">Result type of task 7.</typeparam>
        /// <typeparam name="T8">Result type of task 8.</typeparam>
        /// <typeparam name="T9">Result type of task 9.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3, T4, T5, T6, T7, T8, T9)> GetAwaiter<
            T1, T2, T3, T4, T5, T6, T7, T8, T9>(
            this (
                OnityTask<T1> task1,
                OnityTask<T2> task2,
                OnityTask<T3> task3,
                OnityTask<T4> task4,
                OnityTask<T5> task5,
                OnityTask<T6> task6,
                OnityTask<T7> task7,
                OnityTask<T8> task8,
                OnityTask<T9> task9) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of ten typed tasks and returns their results in tuple order,
        /// as <c>OnityTask.WhenAll</c>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <typeparam name="T4">Result type of task 4.</typeparam>
        /// <typeparam name="T5">Result type of task 5.</typeparam>
        /// <typeparam name="T6">Result type of task 6.</typeparam>
        /// <typeparam name="T7">Result type of task 7.</typeparam>
        /// <typeparam name="T8">Result type of task 8.</typeparam>
        /// <typeparam name="T9">Result type of task 9.</typeparam>
        /// <typeparam name="T10">Result type of task 10.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)> GetAwaiter<
            T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(
            this (
                OnityTask<T1> task1,
                OnityTask<T2> task2,
                OnityTask<T3> task3,
                OnityTask<T4> task4,
                OnityTask<T5> task5,
                OnityTask<T6> task6,
                OnityTask<T7> task7,
                OnityTask<T8> task8,
                OnityTask<T9> task9,
                OnityTask<T10> task10) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9,
                tasks.Item10).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of eleven typed tasks and returns their results in tuple order,
        /// as <c>OnityTask.WhenAll</c>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <typeparam name="T4">Result type of task 4.</typeparam>
        /// <typeparam name="T5">Result type of task 5.</typeparam>
        /// <typeparam name="T6">Result type of task 6.</typeparam>
        /// <typeparam name="T7">Result type of task 7.</typeparam>
        /// <typeparam name="T8">Result type of task 8.</typeparam>
        /// <typeparam name="T9">Result type of task 9.</typeparam>
        /// <typeparam name="T10">Result type of task 10.</typeparam>
        /// <typeparam name="T11">Result type of task 11.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)> GetAwaiter<
            T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(
            this (
                OnityTask<T1> task1,
                OnityTask<T2> task2,
                OnityTask<T3> task3,
                OnityTask<T4> task4,
                OnityTask<T5> task5,
                OnityTask<T6> task6,
                OnityTask<T7> task7,
                OnityTask<T8> task8,
                OnityTask<T9> task9,
                OnityTask<T10> task10,
                OnityTask<T11> task11) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9,
                tasks.Item10,
                tasks.Item11).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of twelve typed tasks and returns their results in tuple order,
        /// as <c>OnityTask.WhenAll</c>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <typeparam name="T4">Result type of task 4.</typeparam>
        /// <typeparam name="T5">Result type of task 5.</typeparam>
        /// <typeparam name="T6">Result type of task 6.</typeparam>
        /// <typeparam name="T7">Result type of task 7.</typeparam>
        /// <typeparam name="T8">Result type of task 8.</typeparam>
        /// <typeparam name="T9">Result type of task 9.</typeparam>
        /// <typeparam name="T10">Result type of task 10.</typeparam>
        /// <typeparam name="T11">Result type of task 11.</typeparam>
        /// <typeparam name="T12">Result type of task 12.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)> GetAwaiter<
            T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(
            this (
                OnityTask<T1> task1,
                OnityTask<T2> task2,
                OnityTask<T3> task3,
                OnityTask<T4> task4,
                OnityTask<T5> task5,
                OnityTask<T6> task6,
                OnityTask<T7> task7,
                OnityTask<T8> task8,
                OnityTask<T9> task9,
                OnityTask<T10> task10,
                OnityTask<T11> task11,
                OnityTask<T12> task12) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9,
                tasks.Item10,
                tasks.Item11,
                tasks.Item12).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of thirteen typed tasks and returns their results in tuple order,
        /// as <c>OnityTask.WhenAll</c>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <typeparam name="T4">Result type of task 4.</typeparam>
        /// <typeparam name="T5">Result type of task 5.</typeparam>
        /// <typeparam name="T6">Result type of task 6.</typeparam>
        /// <typeparam name="T7">Result type of task 7.</typeparam>
        /// <typeparam name="T8">Result type of task 8.</typeparam>
        /// <typeparam name="T9">Result type of task 9.</typeparam>
        /// <typeparam name="T10">Result type of task 10.</typeparam>
        /// <typeparam name="T11">Result type of task 11.</typeparam>
        /// <typeparam name="T12">Result type of task 12.</typeparam>
        /// <typeparam name="T13">Result type of task 13.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)> GetAwaiter<
            T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(
            this (
                OnityTask<T1> task1,
                OnityTask<T2> task2,
                OnityTask<T3> task3,
                OnityTask<T4> task4,
                OnityTask<T5> task5,
                OnityTask<T6> task6,
                OnityTask<T7> task7,
                OnityTask<T8> task8,
                OnityTask<T9> task9,
                OnityTask<T10> task10,
                OnityTask<T11> task11,
                OnityTask<T12> task12,
                OnityTask<T13> task13) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9,
                tasks.Item10,
                tasks.Item11,
                tasks.Item12,
                tasks.Item13).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of fourteen typed tasks and returns their results in tuple order,
        /// as <c>OnityTask.WhenAll</c>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <typeparam name="T4">Result type of task 4.</typeparam>
        /// <typeparam name="T5">Result type of task 5.</typeparam>
        /// <typeparam name="T6">Result type of task 6.</typeparam>
        /// <typeparam name="T7">Result type of task 7.</typeparam>
        /// <typeparam name="T8">Result type of task 8.</typeparam>
        /// <typeparam name="T9">Result type of task 9.</typeparam>
        /// <typeparam name="T10">Result type of task 10.</typeparam>
        /// <typeparam name="T11">Result type of task 11.</typeparam>
        /// <typeparam name="T12">Result type of task 12.</typeparam>
        /// <typeparam name="T13">Result type of task 13.</typeparam>
        /// <typeparam name="T14">Result type of task 14.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14)> GetAwaiter<
            T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(
            this (
                OnityTask<T1> task1,
                OnityTask<T2> task2,
                OnityTask<T3> task3,
                OnityTask<T4> task4,
                OnityTask<T5> task5,
                OnityTask<T6> task6,
                OnityTask<T7> task7,
                OnityTask<T8> task8,
                OnityTask<T9> task9,
                OnityTask<T10> task10,
                OnityTask<T11> task11,
                OnityTask<T12> task12,
                OnityTask<T13> task13,
                OnityTask<T14> task14) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9,
                tasks.Item10,
                tasks.Item11,
                tasks.Item12,
                tasks.Item13,
                tasks.Item14).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of fifteen typed tasks and returns their results in tuple order,
        /// as <c>OnityTask.WhenAll</c>.
        /// </summary>
        /// <typeparam name="T1">Result type of task 1.</typeparam>
        /// <typeparam name="T2">Result type of task 2.</typeparam>
        /// <typeparam name="T3">Result type of task 3.</typeparam>
        /// <typeparam name="T4">Result type of task 4.</typeparam>
        /// <typeparam name="T5">Result type of task 5.</typeparam>
        /// <typeparam name="T6">Result type of task 6.</typeparam>
        /// <typeparam name="T7">Result type of task 7.</typeparam>
        /// <typeparam name="T8">Result type of task 8.</typeparam>
        /// <typeparam name="T9">Result type of task 9.</typeparam>
        /// <typeparam name="T10">Result type of task 10.</typeparam>
        /// <typeparam name="T11">Result type of task 11.</typeparam>
        /// <typeparam name="T12">Result type of task 12.</typeparam>
        /// <typeparam name="T13">Result type of task 13.</typeparam>
        /// <typeparam name="T14">Result type of task 14.</typeparam>
        /// <typeparam name="T15">Result type of task 15.</typeparam>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter<(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15)> GetAwaiter<
            T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(
            this (
                OnityTask<T1> task1,
                OnityTask<T2> task2,
                OnityTask<T3> task3,
                OnityTask<T4> task4,
                OnityTask<T5> task5,
                OnityTask<T6> task6,
                OnityTask<T7> task7,
                OnityTask<T8> task8,
                OnityTask<T9> task9,
                OnityTask<T10> task10,
                OnityTask<T11> task11,
                OnityTask<T12> task12,
                OnityTask<T13> task13,
                OnityTask<T14> task14,
                OnityTask<T15> task15) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9,
                tasks.Item10,
                tasks.Item11,
                tasks.Item12,
                tasks.Item13,
                tasks.Item14,
                tasks.Item15).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of two untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask, OnityTask)"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (OnityTask task1, OnityTask task2) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of three untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (OnityTask task1, OnityTask task2, OnityTask task3) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of four untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (OnityTask task1, OnityTask task2, OnityTask task3, OnityTask task4) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of five untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (OnityTask task1, OnityTask task2, OnityTask task3, OnityTask task4, OnityTask task5) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of six untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (
                OnityTask task1,
                OnityTask task2,
                OnityTask task3,
                OnityTask task4,
                OnityTask task5,
                OnityTask task6) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of seven untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (
                OnityTask task1,
                OnityTask task2,
                OnityTask task3,
                OnityTask task4,
                OnityTask task5,
                OnityTask task6,
                OnityTask task7) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of eight untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (
                OnityTask task1,
                OnityTask task2,
                OnityTask task3,
                OnityTask task4,
                OnityTask task5,
                OnityTask task6,
                OnityTask task7,
                OnityTask task8) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of nine untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (
                OnityTask task1,
                OnityTask task2,
                OnityTask task3,
                OnityTask task4,
                OnityTask task5,
                OnityTask task6,
                OnityTask task7,
                OnityTask task8,
                OnityTask task9) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of ten untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (
                OnityTask task1,
                OnityTask task2,
                OnityTask task3,
                OnityTask task4,
                OnityTask task5,
                OnityTask task6,
                OnityTask task7,
                OnityTask task8,
                OnityTask task9,
                OnityTask task10) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9,
                tasks.Item10).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of eleven untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (
                OnityTask task1,
                OnityTask task2,
                OnityTask task3,
                OnityTask task4,
                OnityTask task5,
                OnityTask task6,
                OnityTask task7,
                OnityTask task8,
                OnityTask task9,
                OnityTask task10,
                OnityTask task11) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9,
                tasks.Item10,
                tasks.Item11).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of twelve untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (
                OnityTask task1,
                OnityTask task2,
                OnityTask task3,
                OnityTask task4,
                OnityTask task5,
                OnityTask task6,
                OnityTask task7,
                OnityTask task8,
                OnityTask task9,
                OnityTask task10,
                OnityTask task11,
                OnityTask task12) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9,
                tasks.Item10,
                tasks.Item11,
                tasks.Item12).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of thirteen untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (
                OnityTask task1,
                OnityTask task2,
                OnityTask task3,
                OnityTask task4,
                OnityTask task5,
                OnityTask task6,
                OnityTask task7,
                OnityTask task8,
                OnityTask task9,
                OnityTask task10,
                OnityTask task11,
                OnityTask task12,
                OnityTask task13) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9,
                tasks.Item10,
                tasks.Item11,
                tasks.Item12,
                tasks.Item13).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of fourteen untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (
                OnityTask task1,
                OnityTask task2,
                OnityTask task3,
                OnityTask task4,
                OnityTask task5,
                OnityTask task6,
                OnityTask task7,
                OnityTask task8,
                OnityTask task9,
                OnityTask task10,
                OnityTask task11,
                OnityTask task12,
                OnityTask task13,
                OnityTask task14) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9,
                tasks.Item10,
                tasks.Item11,
                tasks.Item12,
                tasks.Item13,
                tasks.Item14).GetAwaiter();
        }

        /// <summary>
        /// Awaits a tuple of fifteen untyped tasks, as <see cref="OnityTask.WhenAll(OnityTask[])"/>.
        /// </summary>
        /// <param name="tasks">Tasks to await. Each single-consumer task is consumed once.</param>
        /// <returns>The awaiter of the combined task.</returns>
        public static OnityTaskAwaiter GetAwaiter(
            this (
                OnityTask task1,
                OnityTask task2,
                OnityTask task3,
                OnityTask task4,
                OnityTask task5,
                OnityTask task6,
                OnityTask task7,
                OnityTask task8,
                OnityTask task9,
                OnityTask task10,
                OnityTask task11,
                OnityTask task12,
                OnityTask task13,
                OnityTask task14,
                OnityTask task15) tasks)
        {
            return OnityTask.WhenAll(
                tasks.Item1,
                tasks.Item2,
                tasks.Item3,
                tasks.Item4,
                tasks.Item5,
                tasks.Item6,
                tasks.Item7,
                tasks.Item8,
                tasks.Item9,
                tasks.Item10,
                tasks.Item11,
                tasks.Item12,
                tasks.Item13,
                tasks.Item14,
                tasks.Item15).GetAwaiter();
        }
    }
}
